import { paramCase, pascalCase, pascalCaseTransformMerge } from 'change-case'
import { outputFile, readFile, remove } from 'fs-extra'
import globby from 'globby'
import { basename, extname, join, resolve } from 'path'
import { optimize } from 'svgo'

type SvgFile = {
  dimension: number
  componentName: string
  baseName: string
  svgPath: string
}

async function main(): Promise<void> {
  const svgFilesGlob = './icons/**/*.svg'
  const filePaths = await globby([svgFilesGlob])
  if (filePaths.length === 0) {
    throw new Error(`No files match the pattern \`${svgFilesGlob}\``)
  }
  const svgFiles = await readSvgFilesAsync(filePaths)
  const dimensions: Record<string, Array<SvgFile>> = groupSvgFilesByDimension(
    svgFiles
  )
  const iconDirectoryPath = resolve(
    __dirname,
    '..',
    'src',
    'components',
    'icon'
  )
  const directories = await globby([join(iconDirectoryPath, 'icon-*')], {
    onlyFiles: false
  })
  for (const directory of directories) {
    await remove(directory)
  }
  for (const dimension in dimensions) {
    const outputDirectory = join(iconDirectoryPath, `icon-${dimension}`)
    await writePreactComponentsAsync(dimensions[dimension], outputDirectory)
    await writeStoriesAsync(dimensions[dimension], dimension, outputDirectory)
  }
}
main()

async function readSvgFilesAsync(
  filePaths: Array<string>
): Promise<Array<SvgFile>> {
  const result: Array<SvgFile> = []
  const usedNames: Record<string, true> = {}
  for (const filePath of filePaths.sort()) {
    const svgFile = await readSvgFileAsync(filePath)
    const { componentName } = svgFile
    if (usedNames[componentName] === true) {
      throw new Error(`Name clash \`${componentName}\`: ${filePath}`)
    }
    usedNames[componentName] = true
    result.push(svgFile)
  }
  return result
}

async function readSvgFileAsync(filePath: string): Promise<SvgFile> {
  const baseName = basename(filePath, extname(filePath))
  const svgString = await readFile(filePath, 'utf8')
  const result = optimize(svgString, {
    plugins: [
      {
        name: 'convertPathData',
        params: {
          floatPrecision: 5
        }
      }
    ]
  })
  const { width, height } = result.info
  if (width !== height) {
    throw new Error(`Different \`width\` and \`height\`: ${filePath}`)
  }
  const dimension = parseInt(result.info.width, 10)
  return {
    baseName: paramCase(`icon-${baseName}-${dimension}`),
    componentName: pascalCase(`Icon ${baseName} ${dimension}`, {
      transform: pascalCaseTransformMerge
    }),
    dimension,
    svgPath: extractSvgPath(result.data, filePath)
  }
}

function extractSvgPath(svgString: string, filePath: string): string {
  const result: Array<string> = []
  const matches = svgString.matchAll(/d="([^"]+)"/g)
  for (const match of matches) {
    result.push(match[1])
  }
  if (result.length > 1) {
    throw new Error(`More than 1 \`path\` in ${filePath}`)
  }
  return result[0]
}

function groupSvgFilesByDimension(
  svgFiles: Array<SvgFile>
): Record<string, Array<SvgFile>> {
  const result: Record<string, Array<SvgFile>> = {}
  for (const svgFile of svgFiles) {
    const dimension = `${svgFile.dimension}`
    if (typeof result[dimension] === 'undefined') {
      result[dimension] = []
    }
    result[dimension].push(svgFile)
  }
  return result
}

async function writePreactComponentsAsync(
  svgFiles: Array<SvgFile>,
  directoryPath: string
): Promise<void> {
  for (const { baseName, componentName, svgPath, dimension } of svgFiles) {
    const fileContents = `import { createIcon } from '../create-icon'

export const ${componentName} = createIcon(
  '${svgPath}',
  { height: ${dimension}, width: ${dimension} }
)
`
    const filePath = join(directoryPath, `${baseName}.ts`)
    await writeFileAsync(filePath, fileContents)
  }
}

async function writeStoriesAsync(
  svgFiles: Array<SvgFile>,
  dimension: string,
  directoryPath: string
): Promise<void> {
  const imports = []
  const stories = []
  for (const { baseName, componentName } of svgFiles) {
    imports.push(`import { ${componentName} } from './${baseName}'`)
    stories.push(`export const ${componentName
      .replace(/^Icon/, '')
      .replace(/\d+$/, '')} = function () {
  return <${componentName} />
}`)
  }
  const fileContents = `/** @jsx h */
import { h } from 'preact'

${imports.join('\n')}

export default { title: 'Components/Icon/Size ${dimension}' }

${stories.join('\n\n')}
`
  const filePath = join(directoryPath, `icon-${dimension}.stories.tsx`)
  await writeFileAsync(filePath, fileContents)
}

async function writeFileAsync(
  filePath: string,
  fileContents: string
): Promise<void> {
  await outputFile(
    filePath,
    `// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n${fileContents}`
  )
}
