// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { IconAlignBottom16 } from '../icon-align-bottom-16.js'
import { IconAlignMiddle16 } from '../icon-align-middle-16.js'
import { IconAlignTop16 } from '../icon-align-top-16.js'
import { IconAnchorHorizontal16 } from '../icon-anchor-horizontal-16.js'
import { IconAnchorVertical16 } from '../icon-anchor-vertical-16.js'
import { IconArrowDown16 } from '../icon-arrow-down-16.js'
import { IconArrowLeft16 } from '../icon-arrow-left-16.js'
import { IconArrowLeftRight16 } from '../icon-arrow-left-right-16.js'
import { IconArrowRight16 } from '../icon-arrow-right-16.js'
import { IconArrowUp16 } from '../icon-arrow-up-16.js'
import { IconArrowUpDown16 } from '../icon-arrow-up-down-16.js'
import { IconAutoLayoutHorizontalBottom16 } from '../icon-auto-layout-horizontal-bottom-16.js'
import { IconAutoLayoutHorizontalCenter16 } from '../icon-auto-layout-horizontal-center-16.js'
import { IconAutoLayoutHorizontalTop16 } from '../icon-auto-layout-horizontal-top-16.js'
import { IconAutoLayoutVerticalCenter16 } from '../icon-auto-layout-vertical-center-16.js'
import { IconAutoLayoutVerticalLeft16 } from '../icon-auto-layout-vertical-left-16.js'
import { IconAutoLayoutVerticalRight16 } from '../icon-auto-layout-vertical-right-16.js'
import { IconCaretDown16 } from '../icon-caret-down-16.js'
import { IconCaretLeft16 } from '../icon-caret-left-16.js'
import { IconCaretRight16 } from '../icon-caret-right-16.js'
import { IconCaretUp16 } from '../icon-caret-up-16.js'
import { IconChevronDown16 } from '../icon-chevron-down-16.js'
import { IconChevronUp16 } from '../icon-chevron-up-16.js'
import { IconCircleHelp16 } from '../icon-circle-help-16.js'
import { IconCircleInfo16 } from '../icon-circle-info-16.js'
import { IconCode16 } from '../icon-code-16.js'
import { IconConnector16 } from '../icon-connector-16.js'
import { IconHyperlink16 } from '../icon-hyperlink-16.js'
import { IconLayerAnimated16 } from '../icon-layer-animated-16.js'
import { IconLayerComponent16 } from '../icon-layer-component-16.js'
import { IconLayerEllipse16 } from '../icon-layer-ellipse-16.js'
import { IconLayerFrame16 } from '../icon-layer-frame-16.js'
import { IconLayerFrameCoverArt16 } from '../icon-layer-frame-cover-art-16.js'
import { IconLayerFrameScrolling16 } from '../icon-layer-frame-scrolling-16.js'
import { IconLayerFrameScrollingHorizontal16 } from '../icon-layer-frame-scrolling-horizontal-16.js'
import { IconLayerFrameScrollingVertical16 } from '../icon-layer-frame-scrolling-vertical-16.js'
import { IconLayerGroup16 } from '../icon-layer-group-16.js'
import { IconLayerImage16 } from '../icon-layer-image-16.js'
import { IconLayerInstance16 } from '../icon-layer-instance-16.js'
import { IconLayerLine16 } from '../icon-layer-line-16.js'
import { IconLayerMask16 } from '../icon-layer-mask-16.js'
import { IconLayerRectangle16 } from '../icon-layer-rectangle-16.js'
import { IconLayerSlice16 } from '../icon-layer-slice-16.js'
import { IconLayerText16 } from '../icon-layer-text-16.js'
import { IconLayerVector16 } from '../icon-layer-vector-16.js'
import { IconLockLocked16 } from '../icon-lock-locked-16.js'
import { IconLockUnlocked16 } from '../icon-lock-unlocked-16.js'
import { IconMenuCheckmarkBreadcrumb16 } from '../icon-menu-checkmark-breadcrumb-16.js'
import { IconMenuCheckmarkChecked16 } from '../icon-menu-checkmark-checked-16.js'
import { IconMenuCheckmarkMixed16 } from '../icon-menu-checkmark-mixed-16.js'
import { IconMoveDown16 } from '../icon-move-down-16.js'
import { IconMoveRight16 } from '../icon-move-right-16.js'
import { IconOptionCheck16 } from '../icon-option-check-16.js'
import { IconOptionDisabled16 } from '../icon-option-disabled-16.js'
import { IconOrientationLandscape16 } from '../icon-orientation-landscape-16.js'
import { IconOrientationPortrait16 } from '../icon-orientation-portrait-16.js'
import { IconPaddingHorizontal16 } from '../icon-padding-horizontal-16.js'
import { IconPaddingVertical16 } from '../icon-padding-vertical-16.js'
import { IconSpaceHorizontal16 } from '../icon-space-horizontal-16.js'
import { IconSpaceVertical16 } from '../icon-space-vertical-16.js'
import { IconStar16 } from '../icon-star-16.js'
import { IconStarFilled16 } from '../icon-star-filled-16.js'
import { IconSwap16 } from '../icon-swap-16.js'
import { IconTarget16 } from '../icon-target-16.js'
import { IconTextAlignCenter16 } from '../icon-text-align-center-16.js'
import { IconTextAlignJustified16 } from '../icon-text-align-justified-16.js'
import { IconTextAlignLeft16 } from '../icon-text-align-left-16.js'
import { IconTextAlignRight16 } from '../icon-text-align-right-16.js'
import { IconTextDecorationStrikethrough16 } from '../icon-text-decoration-strikethrough-16.js'
import { IconTextDecorationUnderline16 } from '../icon-text-decoration-underline-16.js'
import { IconUi3CheckboxCheck16 } from '../icon-ui-3-checkbox-check-16.js'
import { IconUi3DisclosureChevron16 } from '../icon-ui-3-disclosure-chevron-16.js'
import { IconUpload16 } from '../icon-upload-16.js'
import { IconVisibilityHidden16 } from '../icon-visibility-hidden-16.js'
import { IconVisibilityVisible16 } from '../icon-visibility-visible-16.js'
import { IconWarning16 } from '../icon-warning-16.js'
import { IconWorld16 } from '../icon-world-16.js'

export default {
  parameters: {
    fixedWidth: false
  },
  title: 'Icons/Size 16'
}

export const AlignBottom = function () {
  return <IconAlignBottom16 />
}

export const AlignMiddle = function () {
  return <IconAlignMiddle16 />
}

export const AlignTop = function () {
  return <IconAlignTop16 />
}

export const AnchorHorizontal = function () {
  return <IconAnchorHorizontal16 />
}

export const AnchorVertical = function () {
  return <IconAnchorVertical16 />
}

export const ArrowDown = function () {
  return <IconArrowDown16 />
}

export const ArrowLeftRight = function () {
  return <IconArrowLeftRight16 />
}

export const ArrowLeft = function () {
  return <IconArrowLeft16 />
}

export const ArrowRight = function () {
  return <IconArrowRight16 />
}

export const ArrowUpDown = function () {
  return <IconArrowUpDown16 />
}

export const ArrowUp = function () {
  return <IconArrowUp16 />
}

export const AutoLayoutHorizontalBottom = function () {
  return <IconAutoLayoutHorizontalBottom16 />
}

export const AutoLayoutHorizontalCenter = function () {
  return <IconAutoLayoutHorizontalCenter16 />
}

export const AutoLayoutHorizontalTop = function () {
  return <IconAutoLayoutHorizontalTop16 />
}

export const AutoLayoutVerticalCenter = function () {
  return <IconAutoLayoutVerticalCenter16 />
}

export const AutoLayoutVerticalLeft = function () {
  return <IconAutoLayoutVerticalLeft16 />
}

export const AutoLayoutVerticalRight = function () {
  return <IconAutoLayoutVerticalRight16 />
}

export const CaretDown = function () {
  return <IconCaretDown16 />
}

export const CaretLeft = function () {
  return <IconCaretLeft16 />
}

export const CaretRight = function () {
  return <IconCaretRight16 />
}

export const CaretUp = function () {
  return <IconCaretUp16 />
}

export const ChevronDown = function () {
  return <IconChevronDown16 />
}

export const ChevronUp = function () {
  return <IconChevronUp16 />
}

export const CircleHelp = function () {
  return <IconCircleHelp16 />
}

export const CircleInfo = function () {
  return <IconCircleInfo16 />
}

export const Code = function () {
  return <IconCode16 />
}

export const Connector = function () {
  return <IconConnector16 />
}

export const Hyperlink = function () {
  return <IconHyperlink16 />
}

export const LayerAnimated = function () {
  return <IconLayerAnimated16 />
}

export const LayerComponent = function () {
  return <IconLayerComponent16 />
}

export const LayerEllipse = function () {
  return <IconLayerEllipse16 />
}

export const LayerFrameCoverArt = function () {
  return <IconLayerFrameCoverArt16 />
}

export const LayerFrameScrollingHorizontal = function () {
  return <IconLayerFrameScrollingHorizontal16 />
}

export const LayerFrameScrollingVertical = function () {
  return <IconLayerFrameScrollingVertical16 />
}

export const LayerFrameScrolling = function () {
  return <IconLayerFrameScrolling16 />
}

export const LayerFrame = function () {
  return <IconLayerFrame16 />
}

export const LayerGroup = function () {
  return <IconLayerGroup16 />
}

export const LayerImage = function () {
  return <IconLayerImage16 />
}

export const LayerInstance = function () {
  return <IconLayerInstance16 />
}

export const LayerLine = function () {
  return <IconLayerLine16 />
}

export const LayerMask = function () {
  return <IconLayerMask16 />
}

export const LayerRectangle = function () {
  return <IconLayerRectangle16 />
}

export const LayerSlice = function () {
  return <IconLayerSlice16 />
}

export const LayerText = function () {
  return <IconLayerText16 />
}

export const LayerVector = function () {
  return <IconLayerVector16 />
}

export const LockLocked = function () {
  return <IconLockLocked16 />
}

export const LockUnlocked = function () {
  return <IconLockUnlocked16 />
}

export const MenuCheckmarkBreadcrumb = function () {
  return <IconMenuCheckmarkBreadcrumb16 />
}

export const MenuCheckmarkChecked = function () {
  return <IconMenuCheckmarkChecked16 />
}

export const MenuCheckmarkMixed = function () {
  return <IconMenuCheckmarkMixed16 />
}

export const MoveDown = function () {
  return <IconMoveDown16 />
}

export const MoveRight = function () {
  return <IconMoveRight16 />
}

export const OptionCheck = function () {
  return <IconOptionCheck16 />
}

export const OptionDisabled = function () {
  return <IconOptionDisabled16 />
}

export const OrientationLandscape = function () {
  return <IconOrientationLandscape16 />
}

export const OrientationPortrait = function () {
  return <IconOrientationPortrait16 />
}

export const PaddingHorizontal = function () {
  return <IconPaddingHorizontal16 />
}

export const PaddingVertical = function () {
  return <IconPaddingVertical16 />
}

export const SpaceHorizontal = function () {
  return <IconSpaceHorizontal16 />
}

export const SpaceVertical = function () {
  return <IconSpaceVertical16 />
}

export const StarFilled = function () {
  return <IconStarFilled16 />
}

export const Star = function () {
  return <IconStar16 />
}

export const Swap = function () {
  return <IconSwap16 />
}

export const Target = function () {
  return <IconTarget16 />
}

export const TextAlignCenter = function () {
  return <IconTextAlignCenter16 />
}

export const TextAlignJustified = function () {
  return <IconTextAlignJustified16 />
}

export const TextAlignLeft = function () {
  return <IconTextAlignLeft16 />
}

export const TextAlignRight = function () {
  return <IconTextAlignRight16 />
}

export const TextDecorationStrikethrough = function () {
  return <IconTextDecorationStrikethrough16 />
}

export const TextDecorationUnderline = function () {
  return <IconTextDecorationUnderline16 />
}

export const Ui3CheckboxCheck = function () {
  return <IconUi3CheckboxCheck16 />
}

export const Ui3DisclosureChevron = function () {
  return <IconUi3DisclosureChevron16 />
}

export const Upload = function () {
  return <IconUpload16 />
}

export const VisibilityHidden = function () {
  return <IconVisibilityHidden16 />
}

export const VisibilityVisible = function () {
  return <IconVisibilityVisible16 />
}

export const Warning = function () {
  return <IconWarning16 />
}

export const World = function () {
  return <IconWorld16 />
}
