// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../../create-icon.js'

export const IconChevronLeft16 = createIcon(
  'M9.232 10.475a.5.5 0 0 1-.707 0L6.05 8l2.475-2.474a.5.5 0 0 1 .707.706L7.464 8l1.768 1.768a.5.5 0 0 1 0 .707',
  { height: 16, width: 16 }
)
