// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../../create-icon.js'

export const IconChevronUp16 = createIcon(
  'M5.525 9.232a.5.5 0 0 1 0-.707L8 6.05l2.474 2.475a.5.5 0 0 1-.706.707L8 7.464 6.232 9.232a.5.5 0 0 1-.707 0',
  { height: 16, width: 16 }
)
