// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon.js'

export const IconControlCheckboxMixed12 = createIcon('M9 7H3V5h6z', {
  height: 12,
  width: 12
})
