// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconCorners32 = createIcon(
  'M11 11h3v1h-2v2h-1v-3Zm7 0h3v3h-1v-2h-2v-1Zm-6 9v-2h-1v3h3v-1h-2Zm9-2v3h-3v-1h2v-2h1Z',
  { height: 32, width: 32 }
)
