// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconLayoutGridUniform32 = createIcon(
  'M9 9h3v3H9zm11 0h3v3h-3zm-2.5 0h-3v3h3zM9 14.5h3v3H9zm14 0h-3v3h3zm-8.5 0h3v3h-3zM12 20H9v3h3zm8 0h3v3h-3zm-2.5 0h-3v3h3z',
  { height: 32, width: 32 }
)
