// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconLayoutGridUniform32 = createIcon(
  'M9 9h3v3H9V9Zm11 0h3v3h-3V9Zm-2.5 0h-3v3h3V9ZM9 14.5h3v3H9v-3Zm14 0h-3v3h3v-3Zm-8.5 0h3v3h-3v-3ZM12 20H9v3h3v-3Zm8 0h3v3h-3v-3Zm-2.5 0h-3v3h3v-3Z',
  { height: 32, width: 32 }
)
