// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconPlay32 = createIcon(
  'm13 10.0979.765.4781 8 5 .6784.424-.6784.424-8 5-.765.4781V10.0979Zm1 1.8042v8.1958L20.5566 16 14 11.9021Z',
  { height: 32, width: 32 }
)
