// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconListDetailed32 = createIcon(
  'M12 10h-2v1h2v-1Zm0 10h-2v1h2v-1Zm-2-5h2v1h-2v-1Zm12-5h-8v1h8v-1Zm-8 10h8v1h-8v-1Zm8-5h-8v1h8v-1Z',
  { height: 32, width: 32 }
)
