// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconTidyListVertical32 = createIcon(
  'M9.5 10h13v2h-13zm0 5h13v2h-13zm13 5h-13v2h13z',
  { height: 32, width: 32 }
)
