// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconScale32 = createIcon(
  'M24 23.5v.5H8V8h5v1H9v14h14v-4h1v4.5ZM13.5 19H13v-6h1v4.2929L22.2929 9H18V8h6v6h-1V9.70711L14.7071 18H19v1h-5.5Z',
  { height: 32, width: 32 }
)
