// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconStrokeWeight32 = createIcon(
  'M10 10h12v1H10v-1Zm0 4h12v2H10v-2Zm12 5H10v3h12v-3Z',
  { height: 32, width: 32 }
)
