// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconInfo32 = createIcon(
  'M9 16c0-3.866 3.134-7 7-7s7 3.134 7 7-3.134 7-7 7-7-3.134-7-7Zm7 8c-4.4183 0-8-3.5817-8-8s3.5817-8 8-8 8 3.5817 8 8-3.5817 8-8 8Zm-.5-4.5v-4h1v4h-1Zm1.25-6.4999c0 .4142-.3358.75-.75.75s-.75-.3358-.75-.75v-.0686c0-.4142.3358-.75.75-.75s.75.3358.75.75v.0686Z',
  { height: 32, width: 32 }
)
