// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconLayoutGridRows32 = createIcon(
  'M9 9h14v3H9V9Zm0 5.5h14v3H9v-3ZM23 20H9v3h14v-3Z',
  { height: 32, width: 32 }
)
