// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconAngle32 = createIcon(
  'M12 12v8h8v-1h-3c0-2.2091-1.7909-4-4-4v-3h-1Zm1 4v3h3c0-1.6569-1.3431-3-3-3Z',
  { height: 32, width: 32 }
)
