// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon.js'

export const IconTidyListHorizontal32 = createIcon(
  'M10 22.5v-13h2v13zm5 0v-13h2v13zm5-13v13h2v-13z',
  { height: 32, width: 32 }
)
