// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconDistributeHorizontalSpacing32 = createIcon(
  'M11 22.5v-13h-1v13zm11-13v13h-1v-13zm-5 3v7h-2v-7z',
  { height: 32, width: 32 }
)
