// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon.js'

export const IconLayoutGridColumns32 = createIcon(
  'M9 9h3v14H9zm5.5 0h3v14h-3zM23 9h-3v14h3z',
  { height: 32, width: 32 }
)
