// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconTidyListHorizontal32 = createIcon(
  'M10 22.5v-13h2v13h-2Zm5 0v-13h2v13h-2Zm5-13v13h2v-13h-2Z',
  { height: 32, width: 32 }
)
