// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconAnimation32 = createIcon(
  'M10 10h12v12H10V10Zm-1 0c0-.55228.44772-1 1-1h12c.5523 0 1 .44772 1 1v12c0 .5523-.4477 1-1 1H10c-.55228 0-1-.4477-1-1V10Zm10 6-5-3v6l5-3Z',
  { height: 32, width: 32 }
)
