// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconList32 = createIcon(
  'M23 10H9v1h14v-1ZM9 15.5h14v1H9v-1ZM9 21h14v1H9v-1Z',
  { height: 32, width: 32 }
)
