// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon.js'

export const IconLayoutVertical32 = createIcon(
  'M11 11h10v3H11zm-1-1h12v5H10v-5m1 8h10v3H11zm-1-1h12v5H10v-5',
  { height: 32, width: 32 }
)
