// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconStarFilled32 = createIcon(
  'M15.9894 7.00012 18.5001 13.5h7l-5.8967 4.1742 2.2638 6.916L15.9894 20.3l-5.8779 4.2902 2.2639-6.916L6.50006 13.5h7.00004l2.4893-6.49988Z',
  { height: 32, width: 32 }
)
