// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconFolder32 = createIcon(
  'M9 10h7v2H9v-2Zm-1 2V9h9v3h7v11H8V12Zm9 1H9v9h14v-9h-6Z',
  { height: 32, width: 32 }
)
