// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconGrid32 = createIcon(
  'M11 11h3v3h-3zm-1-1h5v5h-5v-4zm1 8h3v3h-3zm-1-1h5v5h-5v-4zm11-6h-3v3h3zm-3-1h-1v5h5v-5h-1zm0 8h3v3h-3zm-1-1h5v5h-5v-4z',
  { height: 32, width: 32 }
)
