// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/** @jsx h */
import { h } from 'preact'

import { IconControlChevronDown8 } from '../icon-control-chevron-down-8'
import { IconControlChevronUp8 } from '../icon-control-chevron-up-8'

export default {
  parameters: {
    fixedWidth: false
  },
  title: 'Icons/Size 8'
}

export const ControlChevronDown = function () {
  return <IconControlChevronDown8 />
}

export const ControlChevronUp = function () {
  return <IconControlChevronUp8 />
}
