// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { IconCheck16 } from '../icon-check-16.js'
import { IconChevronDown16 } from '../icon-chevron-down-16.js'
import { IconChevronLeft16 } from '../icon-chevron-left-16.js'
import { IconChevronRight16 } from '../icon-chevron-right-16.js'
import { IconChevronUp16 } from '../icon-chevron-up-16.js'
import { IconCircleInfo16 } from '../icon-circle-info-16.js'
import { IconLayerComponent16 } from '../icon-layer-component-16.js'
import { IconLayerFrame16 } from '../icon-layer-frame-16.js'

export default {
  parameters: {
    fixedWidth: false
  },
  title: 'Icons/UI3/Size 16'
}

export const Check = function () {
  return <IconCheck16 />
}

export const ChevronDown = function () {
  return <IconChevronDown16 />
}

export const ChevronLeft = function () {
  return <IconChevronLeft16 />
}

export const ChevronRight = function () {
  return <IconChevronRight16 />
}

export const ChevronUp = function () {
  return <IconChevronUp16 />
}

export const CircleInfo = function () {
  return <IconCircleInfo16 />
}

export const LayerComponent = function () {
  return <IconLayerComponent16 />
}

export const LayerFrame = function () {
  return <IconLayerFrame16 />
}
