// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
export { validateGumroadLicenseKeyMainAsync } from './gumroad/validate-gumroad-license-key-main-async.js'
export { validateGumroadLicenseKeyUiAsync } from './gumroad/validate-gumroad-license-key-ui-async.js'
export {
  getDocumentUseCount,
  incrementDocumentUseCount,
  resetDocumentUseCount
} from './utilities/document-use-count.js'
export {
  getTotalUseCountAsync,
  incrementTotalUseCountAsync,
  resetTotalUseCountAsync
} from './utilities/total-use-count.js'
export { LicenseKeyValidationResult } from './utilities/types.js'
