// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
export { validateGumroadLicenseKeyMainAsync } from './gumroad/validate-gumroad-license-key-main-async.js'
export { validateGumroadLicenseKeyUiAsync } from './gumroad/validate-gumroad-license-key-ui-async.js'
export {
  getDocumentUseCountAsync,
  incrementDocumentUseCountAsync
} from './utilities/document-use-count.js'
export {
  getPluginTotalUseCountAsync,
  incrementPluginTotalUseCountAsync
} from './utilities/plugin-total-use-count.js'
export {
  DocumentUseCountPluginData,
  LicenseKeyValidationResult
} from './utilities/types.js'
