// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconRotation24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M9 8.5c0-.27614-.22386-.5-.5-.5s-.5.22386-.5.5v7c0 .2761.22386.5.5.5h7c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5H13c0-2.2091-1.7909-4-4-4zM9 12v3h3c0-1.6569-1.3431-3-3-3"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
