// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconCollapse24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M17.1464 6.14645c.1953-.19527.5119-.19527.7072 0 .1952.19526.1952.51184 0 .7071L14.7071 10H17.5c.2761 0 .5.2239.5.5s-.2239.5-.5.5h-4c-.2761 0-.5-.2239-.5-.5v-4c0-.27614.2239-.5.5-.5s.5.22386.5.5v2.79289zM6.85355 17.8536c-.19526.1952-.51184.1952-.7071 0-.19527-.1953-.19527-.5119 0-.7072L9.29289 14H6.5c-.27614 0-.5-.2239-.5-.5s.22386-.5.5-.5h4c.2761 0 .5.2239.5.5v4c0 .2761-.2239.5-.5.5s-.5-.2239-.5-.5v-2.7929z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
