// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconSidebarsHideDefault24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M17 6h2c.5523 0 1 .44772 1 1v10c0 .5523-.4477 1-1 1h-2zm-1 0H8v12h8zM7 18V6H5c-.55228 0-1 .44772-1 1v10c0 .5523.44772 1 1 1zM3 7c0-1.10457.89543-2 2-2h14c1.1046 0 2 .89543 2 2v10c0 1.1046-.8954 2-2 2H5c-1.10457 0-2-.8954-2-2z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
