// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutAddVertical24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7 9.5v-2c0-.27614.22386-.5.5-.5h9c.2761 0 .5.22386.5.5v2c0 .27614-.2239.5-.5.5h-9c-.27614 0-.5-.22386-.5-.5m-1-2C6 6.67157 6.67157 6 7.5 6h9c.8284 0 1.5.67157 1.5 1.5v2c0 .8284-.6716 1.5-1.5 1.5h-9C6.67157 11 6 10.3284 6 9.5zm1 9v-2c0-.2761.22386-.5.5-.5h2c.27614 0 .5.2239.5.5v2c0 .2761-.22386.5-.5.5h-2c-.27614 0-.5-.2239-.5-.5m-1-2c0-.8284.67157-1.5 1.5-1.5h2c.8284 0 1.5.6716 1.5 1.5v2c0 .8284-.6716 1.5-1.5 1.5h-2c-.82843 0-1.5-.6716-1.5-1.5zm7.5 1.5c-.2761 0-.5-.2239-.5-.5s.2239-.5.5-.5H15v-1.5c0-.2761.2239-.5.5-.5s.5.2239.5.5V15h1.5c.2761 0 .5.2239.5.5s-.2239.5-.5.5H16v1.5c0 .2761-.2239.5-.5.5s-.5-.2239-.5-.5V16z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
