// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconLayoutGridUniform24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5 5h3v3H5zm10 0h3v3h-3zm-2 0h-3v3h3zm-8 5h3v3H5zm13 0h-3v3h3zm-8 0h3v3h-3zm-2 5H5v3h3zm7 0h3v3h-3zm-2 0h-3v3h3z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
