// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconShadowsSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="M12 18.9293C8.6081 18.4447 6 15.5262 6 12c0-3.52611 2.6081-6.4446 6-6.9292z"
      fill="currentColor"
      fillOpacity="0.3"
    />
    <path
      clip-rule="evenodd"
      d="M6 12.0001c0 3.5261 2.6081 6.4446 6 6.9292V5.07085c-3.3919.4846-6 3.40308-6 6.92925m6.002 7.9383C8.05471 19.4472 5 16.0804 5 12.0001c0-4.08032 3.05471-7.44715 7.002-7.93837.548-.0682.998.38607.998.93836V6.083l.0002.00004c2.8378.47608 5 2.94405 5 5.91706 0 2.973-2.1622 5.4409-5 5.917 0 0-.0001.0001-.0002.0001v1.0829c0 .5523-.45 1.0065-.998.9383m.9982-3.0383c2.2823-.4633 4-2.4811 4-4.9 0-2.41897-1.7177-4.43673-4-4.9z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
