// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconCheckLarge24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M16.765 7.07607c.2342.14635.3054.45483.159.689l-5 8.00003a.4999.4999 0 0 1-.4028.2345.4999.4999 0 0 1-.4212-.1995l-2.99997-4.0002c-.16569-.2209-.12091-.5343.10001-.7.22091-.1656.53431-.1209.69999.1001l2.56247 3.4167 4.6135-7.38163c.1464-.23417.4549-.30536.689-.159"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
