// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconPause24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M6 5h2.5c.55229 0 1 .44771 1 1v12c0 .5523-.44771 1-1 1H6c-.55229 0-1-.4477-1-1V6c0-.55229.44771-1 1-1M4 6c0-1.10457.89543-2 2-2h2.5c1.10457 0 2 .89543 2 2v12c0 1.1046-.89543 2-2 2H6c-1.10457 0-2-.8954-2-2zm11.5-1H18c.5523 0 1 .44771 1 1v12c0 .5523-.4477 1-1 1h-2.5c-.5523 0-1-.4477-1-1V6c0-.55229.4477-1 1-1m-2 1c0-1.10457.8954-2 2-2H18c1.1046 0 2 .89543 2 2v12c0 1.1046-.8954 2-2 2h-2.5c-1.1046 0-2-.8954-2-2z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
