// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconOverflowDisplaySmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M16.5 6c.2761 0 .5.22386.5.5V7h.5c.2761 0 .5.22386.5.5s-.2239.5-.5.5H17v5h.5c.2761 0 .5.2239.5.5s-.2239.5-.5.5H17v.5c0 .2761-.2239.5-.5.5s-.5-.2239-.5-.5V14h-2v-1h2V8h-5v2h-1V8h-.5c-.27614 0-.5-.22386-.5-.5s.22386-.5.5-.5h.5v-.5c0-.27614.2239-.5.5-.5s.5.22386.5.5V7h5v-.5c0-.27614.2239-.5.5-.5M13 13h-2v-2h-1v2h-.5c-.27614 0-.5.2239-.5.5s.22386.5.5.5h.5v.5c0 .2761.2239.5.5.5s.5-.2239.5-.5V14h2z"
      fill="currentColor"
      fill-rule="evenodd"
      fillOpacity="0.3"
    />
    <path
      clip-rule="evenodd"
      d="M6 11c0-.5523.44772-1 1-1h6c.5523 0 1 .4477 1 1v6c0 .5523-.4477 1-1 1H7c-.55228 0-1-.4477-1-1zm4 0H7v6h6v-6z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
