// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconInstanceSwapSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M6.5 6c-.27614 0-.5.22386-.5.5v3c0 .27614.22386.5.5.5s.5-.22386.5-.5V7h2.5c.27614 0 .5-.22386.5-.5S9.77614 6 9.5 6zm8 0c-.2761 0-.5.22386-.5.5s.2239.5.5.5H17v2.5c0 .27614.2239.5.5.5s.5-.22386.5-.5v-3c0-.27614-.2239-.5-.5-.5zM7 14.5c0-.2761-.22386-.5-.5-.5s-.5.2239-.5.5v3c0 .2761.22386.5.5.5h3c.27614 0 .5-.2239.5-.5s-.22386-.5-.5-.5H7zm11 0c0-.2761-.2239-.5-.5-.5s-.5.2239-.5.5V17h-2.5c-.2761 0-.5.2239-.5.5s.2239.5.5.5h3c.2761 0 .5-.2239.5-.5zm-5.6465-5.85355c-.1952-.19526-.5118-.19526-.707 0L8.64645 11.6465c-.19526.1952-.19526.5118 0 .707l3.00005 3c.1952.1953.5118.1953.707 0l3-3c.1953-.1952.1953-.5118 0-.707zM12 14.2929 9.70711 12 12 9.70711 14.2929 12z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
