// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconNotificationBellFilledSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M12.9924 6.12406A1.02 1.02 0 0 0 13 6c0-.55228-.4477-1-1-1s-1 .44772-1 1a1.02 1.02 0 0 0 .0076.12407C9.27854 6.56547 8.00003 8.13343 8.00003 10v1.1716c0 1.5458-.61407 3.0283-1.70711 4.1213-.286.286-.37155.7161-.21677 1.0898S6.59557 17 7.00003 17H17c.4045 0 .7691-.2436.9239-.6173s.0692-.8038-.2168-1.0898A5.8285 5.8285 0 0 1 16 11.1716V10c0-1.86659-1.2785-3.43457-3.0076-3.87594M16.1742 15c.2412.3563.5172.6914.8258 1-1.2806-1.2806-2-3.0174-2-4.8284V10c0-1.38418-.9374-2.54941-2.212-2.89546C14.0626 7.45058 15 8.61581 15 10v1.1716c0 1.3745.4145 2.7064 1.1742 3.8284m-2.4417 3c-.3458.5978-.9922 1-1.7325 1s-1.3866-.4022-1.7324-1h3.4649"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
