// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconPropText24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="m9.97949 8 1.98831 3.2266h.0625L14.0186 8h1.2695l-2.5039 4 2.5117 4h-1.2734l-1.9922-3.1758h-.0625L9.97559 16H8.70215l2.56645-4-2.55864-4z"
      fill="currentColor"
    />
  </svg>
)
