// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconBorderLargeSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5 10c0-.55228.44772-1 1-1h12c.5523 0 1 .44772 1 1v4c0 .5523-.4477 1-1 1H6c-.55228 0-1-.4477-1-1zm2 0H6v4h12v-4H7"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
