// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconPropWidth24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="M9.13232 16 6.9292 8h1.12891l1.61328 6.3555h.07422L11.4097 8h1.1757l1.6602 6.3594h.0781L15.937 8h1.1289l-2.2031 8h-1.1094l-1.7265-6.18359h-.0625L10.2417 16z"
      fill="currentColor"
    />
  </svg>
)
