// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconFilterFilled24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M12 4.1001c-4.36307 0-7.90002 3.53695-7.90002 7.9 0 4.363 3.53695 7.9 7.90002 7.9 4.363 0 7.9-3.537 7.9-7.9 0-4.36305-3.537-7.9-7.9-7.9m-2.50002 7.9c-.27615 0-.5.2239-.5.5s.22385.5.5.5H14.5c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5zm.5 3.5c0-.2761.22382-.5.50002-.5h3c.2761 0 .5.2239.5.5s-.2239.5-.5.5h-3c-.2762 0-.50002-.2239-.50002-.5m-1.5-6.5c-.27615 0-.5.22386-.5.5s.22385.5.5.5H15.5c.2761 0 .5-.22386.5-.5s-.2239-.5-.5-.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
