// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconTemperatureSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M13 11h-2v3.208c-.883.3858-1.5 1.2668-1.5 2.292 0 1.3807 1.1193 2.5 2.5 2.5s2.5-1.1193 2.5-2.5c0-1.0252-.617-1.9062-1.5-2.292z"
      fill="currentColor"
      fill-rule="evenodd"
      fillOpacity="0.3"
    />
    <path
      clip-rule="evenodd"
      d="M12 5c-.5523 0-1 .44771-1 1v4h2V6c0-.55229-.4477-1-1-1m-1 8.9014V11h2v3.1897l.2496.1445c.7486.433 1.2504 1.2411 1.2504 2.1658 0 1.3807-1.1193 2.5-2.5 2.5s-2.5-1.1193-2.5-2.5c0-.9247.5018-1.7328 1.2504-2.1658L11 14.1897zM10 6c0-1.10457.8954-2 2-2s2 .89543 2 2v7.6274c.9059.6319 1.5 1.6826 1.5 2.8726 0 1.933-1.567 3.5-3.5 3.5s-3.5-1.567-3.5-3.5c0-1.19.59409-2.2407 1.5-2.8726zm6.5 0c-.2761 0-.5.22386-.5.5s.2239.5.5.5h2c.2761 0 .5-.22386.5-.5s-.2239-.5-.5-.5zM16 9.5c0-.27614.2239-.5.5-.5h2c.2761 0 .5.22386.5.5s-.2239.5-.5.5h-2c-.2761 0-.5-.22386-.5-.5m.5 2.5c-.2761 0-.5.2239-.5.5s.2239.5.5.5h2c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
