// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconActionTimeSetSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M14 7h1v10h-1V7m-1 1V7c0-.55228.4477-1 1-1h1c.5523 0 1 .44772 1 1v1h2c.5523 0 1 .44772 1 1v6c0 .5523-.4477 1-1 1h-2v1c0 .5523-.4477 1-1 1h-1c-.5523 0-1-.4477-1-1v-1H6c-.55228 0-1-.4477-1-1V9c0-.55228.44772-1 1-1zm0 1H6v6h7zm3 6h2V9h-2z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
