// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconLayoutOverlayBottom24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M8 5h8c.5523 0 1 .44772 1 1v8H7V6c0-.55228.44772-1 1-1M6 15V6c0-1.10457.89543-2 2-2h8c1.1046 0 2 .89543 2 2v12c0 1.1046-.8954 2-2 2H8c-1.10457 0-2-.8954-2-2zm11 0v3c0 .5523-.4477 1-1 1H8c-.55228 0-1-.4477-1-1v-3z"
      fill="currentColor"
      fill-rule="evenodd"
    />
    <path
      d="M6 14h12v4c0 1.1046-.8954 2-2 2H8c-1.10457 0-2-.8954-2-2z"
      fill="currentColor"
      fillOpacity="0.3"
    />
  </svg>
)
