// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconWandSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M9.5 5c-.27614 0-.5.22386-.5.5V9H5.5c-.27614 0-.5.22386-.5.5s.22386.5.5.5H9v3.5c0 .2761.22386.5.5.5s.5-.2239.5-.5V10h3.5c.2761 0 .5-.22386.5-.5s-.2239-.5-.5-.5H10V5.5c0-.27614-.22386-.5-.5-.5M14 6c0 .55228-.4477 1-1 1s-1-.44772-1-1 .4477-1 1-1 1 .44772 1 1M6 7c.55228 0 1-.44772 1-1s-.44772-1-1-1-1 .44772-1 1 .44772 1 1 1m1 6c0 .5523-.44772 1-1 1s-1-.4477-1-1 .44772-1 1-1 1 .4477 1 1m11.8536 5.1464-6.5-6.5c-.1953-.1952-.5119-.1952-.7072 0-.1952.1953-.1952.5119 0 .7072l6.5 6.5c.1953.1952.5119.1952.7072 0 .1952-.1953.1952-.5119 0-.7072"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
