// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutPaddingLeft24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M8 7.5c0-.27614-.22386-.5-.5-.5s-.5.22386-.5.5v9c0 .2761.22386.5.5.5s.5-.2239.5-.5zm5 3.5v2h-2v-2zm0-1c.5523 0 1 .4477 1 1v2c0 .5523-.4477 1-1 1h-2c-.5523 0-1-.4477-1-1v-2c0-.5523.4477-1 1-1z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
