// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconMonospaceLowercaseNumber24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="M10.1179 10.8663c0-.4439-.35983-.8038-.80373-.8038a.804.804 0 0 0-.4425.1328l-1.54489 1.0188a.435.435 0 0 0-.19543.363c0 .3462.38486.5536.67398.3632l1.1981-.7891a.03508.03508 0 0 1 .05437.0293v3.6638H7.78693c-.27614 0-.5.2239-.5.5s.22386.5.5.5h3.49997c.2762 0 .5-.2239.5-.5s-.2238-.5-.5-.5h-1.169z"
      fill="currentColor"
    />
    <path
      d="M12.698 17.1289c-.1658.3279.0725.7154.44.7154a.493.493 0 0 0 .4405-.2716l3.2081-6.3842a.777.777 0 0 0 .0827-.3489c0-.4292-.3479-.7771-.777-.7771h-3.8282c-.2539 0-.4598.2058-.4598.4598 0 .2539.2059.4597.4598.4597h3.4618c.0272 0 .0491.022.0491.0491 0 .0077-.0018.0153-.0052.0222z"
      fill="currentColor"
    />
  </svg>
)
