// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconImport24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M8 6c-1.10457 0-2 .89543-2 2v8c0 1.1046.89543 2 2 2h8c1.1046 0 2-.8954 2-2V9.5c0-.27614-.2239-.5-.5-.5s-.5.22386-.5.5V16c0 .5523-.4477 1-1 1H8c-.55229 0-1-.4477-1-1V8c0-.55229.44771-1 1-1h3c.2761 0 .5-.22386.5-.5S11.2761 6 11 6zm9 0c-3.0376 0-5.5 2.46243-5.5 5.5v1.7929l-1.64645-1.6464c-.19526-.1953-.51184-.1953-.7071 0-.19526.1952-.19526.5118 0 .707l2.50005 2.5c.1952.1953.5118.1953.707 0l2.5-2.5c.1953-.1952.1953-.5118 0-.707-.1952-.1953-.5118-.1953-.707 0L12.5 13.2929V11.5C12.5 9.01472 14.5147 7 17 7h.5c.2761 0 .5-.22386.5-.5s-.2239-.5-.5-.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
