// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconExportSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M12 5c.2761 0 .5.22386.5.5v6.7929l2.1464-2.1465c.1953-.19522.5119-.19522.7072 0 .1952.1953.1952.5119 0 .7072l-3 3c-.1953.1952-.5119.1952-.7072 0l-2.99995-3c-.19527-.1953-.19527-.5119 0-.7072.19526-.19522.51184-.19522.7071 0L11.5 12.2929V5.5c0-.27614.2239-.5.5-.5M6.5 15c.27614 0 .5.2239.5.5v1c0 .2761.22386.5.5.5h9c.2761 0 .5-.2239.5-.5v-1c0-.2761.2239-.5.5-.5s.5.2239.5.5v1c0 .8284-.6716 1.5-1.5 1.5h-9c-.82843 0-1.5-.6716-1.5-1.5v-1c0-.2761.22386-.5.5-.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
