// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconCheck24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M15.2519 8.56819c.2386.13914.3191.4453.18.68383l-3.5 5.99998a.4998.4998 0 0 1-.3903.2463.5.5 0 0 1-.4257-.1781l-2.5-3c-.17678-.2122-.14812-.5274.06402-.7042s.52742-.1481.7042.064l2.04338 2.4521 3.1406-5.38395c.1392-.23853.4453-.3191.6838-.17996"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
