// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconLayoutTidyUpListHorizontal24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M6.75 18c-.41421 0-.75-.3358-.75-.75V5.75c0-.41421.33579-.75.75-.75h.5c.41421 0 .75.33579.75.75v11.5c0 .4142-.33579.75-.75.75zm5 0c-.4142 0-.75-.3358-.75-.75V5.75c0-.41421.3358-.75.75-.75h.5c.4142 0 .75.33579.75.75v11.5c0 .4142-.3358.75-.75.75zm4.25-.75c0 .4142.3358.75.75.75h.5c.4142 0 .75-.3358.75-.75V5.75c0-.41421-.3358-.75-.75-.75h-.5c-.4142 0-.75.33579-.75.75z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
