// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconScaleSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7.5 7c-.27614 0-.5.22386-.5.5v2c0 .27614-.22386.5-.5.5S6 9.77614 6 9.5v-2C6 6.67157 6.67157 6 7.5 6h9c.8284 0 1.5.67157 1.5 1.5v9c0 .8284-.6716 1.5-1.5 1.5h-2c-.2761 0-.5-.2239-.5-.5s.2239-.5.5-.5h2c.2761 0 .5-.2239.5-.5v-9c0-.27614-.2239-.5-.5-.5zM6 12c0-.5523.44771-1 1-1h2.5c.27614 0 .5.2239.5.5s-.22386.5-.5.5H7v5h5v-2.5c0-.2761.2239-.5.5-.5s.5.2239.5.5V17c0 .5523-.4477 1-1 1H7c-.55229 0-1-.4477-1-1zm5.5-3c-.2761 0-.5.22386-.5.5s.2239.5.5.5h1.7929l-4.14645 4.1465c-.19526.1952-.19526.5118 0 .707.19526.1953.51184.1953.7071 0L14 10.7071V12.5c0 .2761.2239.5.5.5s.5-.2239.5-.5v-3c0-.27614-.2239-.5-.5-.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
