// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconLockLocked24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M9 8c0-1.65686 1.3431-3 3-3s3 1.34314 3 3v2H9zm-1 2V8c0-2.20914 1.79086-4 4-4 2.2091 0 4 1.79086 4 4v2h.125c1.0355 0 1.875.8395 1.875 1.875v5.25C18 18.1605 17.1605 19 16.125 19h-8.25C6.83946 19 6 18.1605 6 17.125v-5.25C6 10.8395 6.83946 10 7.875 10zm-1 1.875c0-.4832.39175-.875.875-.875h8.25c.4832 0 .875.3918.875.875v5.25c0 .4832-.3918.875-.875.875h-8.25C7.39175 18 7 17.6082 7 17.125z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
