// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconActionTimeJumpSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M12.5 7h-1v10h1zm-1-1c-.5523 0-1 .44771-1 1v10c0 .5523.4477 1 1 1h1c.5523 0 1-.4477 1-1V7c0-.55229-.4477-1-1-1zM5 12c0-.3148.14819-.6111.39999-.8l2-1.5c.30303-.22727.70844-.26381 1.04723-.09442C8.786 9.77496 9 10.1212 9 10.5v3c0 .3788-.214.725-.55278.8944s-.7442.1329-1.04723-.0944l-2-1.5A1 1 0 0 1 5 12m1.83333-.625L6 12l.83333.625L7 12.75l1 .75v-3l-1 .75zM18.6 11.2a1.00002 1.00002 0 0 1 0 1.6l-2 1.5c-.303.2273-.7084.2638-1.0472.0944S15 13.8788 15 13.5v-3c0-.3788.214-.72504.5528-.89442.3388-.16939.7442-.13285 1.0472.09442zm-.6.8-.8333-.625L17 11.25l-1-.75v3l1-.75.1667-.125z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
