// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconLayoutAlignRight24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M6.75 10C6.33579 10 6 9.66421 6 9.25v-.5c0-.41421.33579-.75.75-.75h8.5c.4142 0 .75.33579.75.75v.5c0 .41421-.3358.75-.75.75zm4 5c-.4142 0-.75-.3358-.75-.75v-.5c0-.4142.3358-.75.75-.75h4.5c.4142 0 .75.3358.75.75v.5c0 .4142-.3358.75-.75.75z"
      fill="currentColor"
      fill-rule="evenodd"
    />
    <path
      d="M18 17.5c0 .2761.2239.5.5.5s.5-.2239.5-.5v-12c0-.27614-.2239-.5-.5-.5s-.5.22386-.5.5z"
      fill="currentColor"
      fillOpacity="0.3"
    />
  </svg>
)
