// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconActionOverlayCloseSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M8 7h8c.5523 0 1 .44772 1 1v8c0 .5523-.4477 1-1 1H8c-.55228 0-1-.4477-1-1V8c0-.55228.44772-1 1-1M6 8c0-1.10457.89543-2 2-2h8c1.1046 0 2 .89543 2 2v8c0 1.1046-.8954 2-2 2H8c-1.10457 0-2-.8954-2-2zm8.1213 2.5858c.1953-.1953.1953-.5118 0-.70711-.1952-.19526-.5118-.19526-.7071 0L12 11.2929l-1.4142-1.41421c-.1953-.19526-.5119-.19526-.70712 0-.19526.19531-.19526.51181 0 .70711L11.2929 12l-1.41422 1.4142c-.19526.1953-.19526.5119 0 .7071.19522.1953.51182.1953.70712 0L12 12.7071l1.4142 1.4142c.1953.1953.5119.1953.7071 0 .1953-.1952.1953-.5118 0-.7071L12.7071 12z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
