// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconMail24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M19.0001 8.7v-.82c0-.48601-.394-.88-.88-.88h-12.24c-.48601 0-.88.39399-.88.88v.82l.47059.25098 6.52941 3.48232 6.5294-3.48232zm0 1.13333-1 .53337-5.5294 2.949-.2353.1255-.2353.1255-.2353-.1255-.2353-.1255-5.5294-2.949-1-.53337V16.12c0 .486.39399.88.88.88h12.24c.486 0 .88-.394.88-.88V9.83333M18.1201 6c1.0383 0 1.88.8417 1.88 1.88v1.10966a.7.7 0 0 1 0 .01982V16.12c0 1.0383-.8417 1.88-1.88 1.88h-12.24c-1.0383 0-1.88-.8417-1.88-1.88V9.00949a.5.5 0 0 1 0-.01984V7.88c0-1.0383.8417-1.88 1.88-1.88z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
