// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconTextLineHeight24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5 5.5c0-.27614.22386-.5.5-.5h13c.2761 0 .5.22386.5.5s-.2239.5-.5.5h-13c-.27614 0-.5-.22386-.5-.5m0 13c0-.2761.22386-.5.5-.5h13c.2761 0 .5.2239.5.5s-.2239.5-.5.5h-13c-.27614 0-.5-.2239-.5-.5M8.56445 16h1.01563l.80422-2.2656h3.2353L14.4238 16h1.0157L12.502 8h-1zm4.75005-3.125-1.2813-3.60938h-.0625L10.6894 12.875z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
