// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconKeySmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="m10.7988 11.1154.3806-.3806-.1081-.5273C11.0247 9.97983 11 9.74332 11 9.5 11 7.567 12.567 6 14.5 6S18 7.567 18 9.5 16.433 13 14.5 13c-.2687 0-.5292-.0301-.7787-.0867L12.5 12.6362V14h-2v2h-2v2H6v-2.0858zM13.5 14c0 .1878-.0518.3636-.1419.5137-.1747.2913-.4937.4863-.8581.4863h-1v1c0 .5523-.4477 1-1 1h-1v1c0 .5523-.44772 1-1 1H6c-.55228 0-1-.4477-1-1v-2.0858c0-.2652.10536-.5196.29289-.7071l4.79881-4.7988C10.0316 10.1149 10 9.81115 10 9.5 10 7.01472 12.0147 5 14.5 5S19 7.01472 19 9.5c0 2.4853-2.0147 4.5-4.5 4.5-.3437 0-.6784-.0385-1-.1115zm1.5-4c.5523 0 1-.44772 1-1s-.4477-1-1-1-1 .44772-1 1 .4477 1 1 1"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
