// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconDocPlus24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7 20h10c.5523 0 1-.4477 1-1V9h-3c-1.1046 0-2-.89543-2-2V4l-6.00001.00004c-.55228.00001-.99999.44772-.99999 1V19c0 .5523.44771 1 1 1m7-15.55397L17.5805 8H15c-.5523 0-1-.44772-1-1V4.44603M17 21H7c-1.10457 0-2-.8954-2-2V5.00004c0-1.10456.89542-1.99999 1.99999-2L13.3446 3c.3959 0 .7757.1565 1.0567.4354l4.1554 4.12459A1.5 1.5 0 0 1 19 8.62459V19c0 1.1046-.8954 2-2 2m-4.9492-11c.2761 0 .5.2239.5.5v2.0498H14.5c.2761 0 .5.2239.5.5s-.2239.5-.5.5h-1.9492V15.5c0 .2761-.2239.5-.5.5-.2762 0-.5-.2239-.5-.5v-1.9502H9.5c-.27614 0-.5-.2239-.5-.5s.22386-.5.5-.5h2.0508V10.5c0-.2761.2238-.5.5-.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
