// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconLayoutDistributeVerticalSpacing24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M19 6.5c0-.27614-.2239-.5-.5-.5h-12c-.27614 0-.5.22386-.5.5s.22386.5.5.5h12c.2761 0 .5-.22386.5-.5m0 11c0-.2761-.2239-.5-.5-.5h-12c-.27614 0-.5.2239-.5.5s.22386.5.5.5h12c.2761 0 .5-.2239.5-.5"
      fill="currentColor"
      fill-rule="evenodd"
      fillOpacity="0.3"
    />
    <path
      d="M9 12.25c0 .4142.33579.75.75.75h5.5c.4142 0 .75-.3358.75-.75v-.5c0-.4142-.3358-.75-.75-.75h-5.5c-.41421 0-.75.3358-.75.75z"
      fill="currentColor"
    />
  </svg>
)
