// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconRadiusTopRight24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M11.5219 8H8.5c-.27614 0-.5.22386-.5.5s.22386.5.5.5h3c.7083 0 1.2095.00039 1.6013.0324.3859.03153.6215.09125.8067.18559a1.9998 1.9998 0 0 1 .874.87401c.0944.1852.1541.4208.1856.8067.032.3918.0324.893.0324 1.6013v3c0 .2761.2239.5.5.5s.5-.2239.5-.5v-3.0219c0-.6815 0-1.2235-.0357-1.6608-.0366-.4478-.1131-.82965-.2913-1.17927a2.9997 2.9997 0 0 0-1.311-1.31105c-.3497-.17814-.7315-.25467-1.1793-.29126C12.7454 7.99999 12.2034 8 11.5219 8"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
