// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconReplaceTextStyle24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M3.5 5c-.27614 0-.5.22386-.5.5v1c0 .27614.22386.5.5.5s.5-.22386.5-.5V6h3v7h-.5c-.27614 0-.5.2239-.5.5s.22386.5.5.5h2c.27614 0 .5-.2239.5-.5s-.22386-.5-.5-.5H8V6h3v.5c0 .27614.2239.5.5.5s.5-.22386.5-.5v-1c0-.27614-.2239-.5-.5-.5h-8m9.5 5c-.5523 0-1 .4477-1 1v1c0 .5523.4477 1 1 1h2v5c0 .5523.4477 1 1 1h1c.5523 0 1-.4477 1-1v-5h2c.5523 0 1-.4477 1-1v-1c0-.5523-.4477-1-1-1zm0 1h7v1h-3v6h-1v-6h-3z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
