// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconHighlightsSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7 12.0001c0 2.4189 1.71776 4.4367 4 4.9v-9.8c-2.28224.46327-4 2.48102-4 4.9"
      fill="currentColor"
      fill-rule="evenodd"
      fillOpacity="0.3"
    />
    <path
      clip-rule="evenodd"
      d="M18.0002 12.0001c0 3.5261-2.6081 6.4446-6 6.9292V5.07085c3.3919.4846 6 3.40308 6 6.92925m-6.0019 7.9383c3.9472-.4912 7.0019-3.858 7.0019-7.9383 0-4.08032-3.0547-7.44715-7.0019-7.93837-.5481-.0682-.9981.38607-.9981.93836V6.083c0 .00002-.0001.00003-.0002.00004-2.83771.47608-5 2.94405-5 5.91706 0 2.973 2.16229 5.4409 5 5.917.0001 0 .0002.0001.0002.0001v1.0829c0 .5523.45 1.0065.9981.9383M11 16.9001c-2.28224-.4633-4-2.4811-4-4.9 0-2.41897 1.71776-4.43673 4-4.9z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
