// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconReturn24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M10.3536 5.64645c.1952.19526.1952.51184 0 .7071L7.70711 9H11.5c3.5761 0 6.5 2.9239 6.5 6.5v2c0 .2761-.2239.5-.5.5s-.5-.2239-.5-.5v-2c0-3.0239-2.4761-5.5-5.5-5.5H7.70711l2.64649 2.6464c.1952.1953.1952.5119 0 .7072-.1953.1952-.51189.1952-.70715 0l-3.5-3.50005c-.19527-.19526-.19527-.51184 0-.7071l3.5-3.5c.19526-.19527.51185-.19527.70715 0"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
