// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconCrop24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M8 3.5c0-.27614-.22386-.5-.5-.5s-.5.22386-.5.5V7H3.5c-.27614 0-.5.22386-.5.5s.22386.5.5.5H7v8.5c0 .2761.22386.5.5.5H16v3.5c0 .2761.2239.5.5.5s.5-.2239.5-.5V17h3.5c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5H17V7.5c0-.27614-.2239-.5-.5-.5H8zM8 8v8h8V8z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
