// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconVersionMerged24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M11.6464 6.14645c.1953-.19527.5119-.19527.7072 0l2 2c.1952.19526.1952.51184 0 .7071-.1953.19527-.5119.19527-.7072 0L12.5 7.70711v3.82379c1.9732.2461 3.5 1.9293 3.5 3.9691v2c0 .2761-.2239.5-.5.5s-.5-.2239-.5-.5v-2c0-1.6569-1.3431-3-3-3s-3 1.3431-3 3v2c0 .2761-.22386.5-.5.5s-.5-.2239-.5-.5v-2c0-2.0398 1.52684-3.723 3.5-3.9691V7.70711l-1.1464 1.14644c-.1953.19527-.51189.19527-.70715 0-.19527-.19526-.19527-.51184 0-.7071z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
