// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconH124 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7 6.5c0-.27614-.22386-.5-.5-.5s-.5.22386-.5.5v11c0 .2761.22386.5.5.5s.5-.2239.5-.5V12h6v5.5c0 .2761.2239.5.5.5s.5-.2239.5-.5v-11c0-.27614-.2239-.5-.5-.5s-.5.22386-.5.5V11H7zm11 6a.4999.4999 0 0 0-.2641-.4408.5.5 0 0 0-.5133.0248l-1.5 1c-.2297.1532-.2918.4636-.1386.6933.1532.2298.4636.2919.6934.1387L17 13.4343V17.5c0 .2761.2239.5.5.5s.5-.2239.5-.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
