// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconLockOpen24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M9 7c0-1.65686 1.3431-3 3-3s3 1.34314 3 3v.5c0 .27614.2239.5.5.5s.5-.22386.5-.5V7c0-2.20914-1.7909-4-4-4-2.20914 0-4 1.79086-4 4v3h-.125C6.83946 10 6 10.8395 6 11.875v5.25C6 18.1605 6.83946 19 7.875 19h8.25C17.1605 19 18 18.1605 18 17.125v-5.25C18 10.8395 17.1605 10 16.125 10H9zm-2 4.875c0-.4832.39175-.875.875-.875h8.25c.4832 0 .875.3918.875.875v5.25c0 .4832-.3918.875-.875.875h-8.25C7.39175 18 7 17.6082 7 17.125z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
