// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconTextAlignJustified24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5 7.5c0-.27614.22386-.5.5-.5h13c.2761 0 .5.22386.5.5s-.2239.5-.5.5h-13c-.27614 0-.5-.22386-.5-.5m0 4c0-.2761.22386-.5.5-.5h13c.2761 0 .5.2239.5.5s-.2239.5-.5.5h-13c-.27614 0-.5-.2239-.5-.5m.5 3.5c-.27614 0-.5.2239-.5.5s.22386.5.5.5h13c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
