// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconClosedCaptioningSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7 7h10c.5523 0 1 .44772 1 1v8c0 .5523-.4477 1-1 1H7c-.55228 0-1-.4477-1-1V8c0-.55228.44772-1 1-1M5 8c0-1.10457.89543-2 2-2h10c1.1046 0 2 .89543 2 2v8c0 1.1046-.8954 2-2 2H7c-1.10457 0-2-.8954-2-2zm4.5 7c-.27614 0-.5.2239-.5.5s.22386.5.5.5h2c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5zm4.5-1.5c0-.2761.2239-.5.5-.5h2c.2761 0 .5.2239.5.5s-.2239.5-.5.5h-2c-.2761 0-.5-.2239-.5-.5m-3.5-.5c-.2761 0-.5.2239-.5.5s.2239.5.5.5h2c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5zm2.5 2.5c0-.2761.2239-.5.5-.5h1c.2761 0 .5.2239.5.5s-.2239.5-.5.5h-1c-.2761 0-.5-.2239-.5-.5M7.5 13c-.27614 0-.5.2239-.5.5s.22386.5.5.5h1c.27614 0 .5-.2239.5-.5s-.22386-.5-.5-.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
