// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconTextAlignTop24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5.5 5c-.27614 0-.5.22386-.5.5s.22386.5.5.5h12c.2761 0 .5-.22386.5-.5s-.2239-.5-.5-.5zm6.3536 2.14645c-.1953-.19527-.5119-.19527-.7072 0L8.14645 10.1464c-.19527.1953-.19527.5119 0 .7072.19526.1952.51184.1952.7071 0L11 8.70711V16.5c0 .2761.2239.5.5.5s.5-.2239.5-.5V8.70711l2.1464 2.14649c.1953.1952.5119.1952.7072 0 .1952-.1953.1952-.5119 0-.7072z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
