// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconTextResizeWidth24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M14.1464 8.14645c.1953-.19527.5119-.19527.7072 0l3 2.99995c.0937.0938.1464.221.1464.3536s-.0527.2598-.1464.3536l-3 3c-.1953.1952-.5119.1952-.7072 0-.1952-.1953-.1952-.5119 0-.7072L16.2929 12l-8.58582.0002 2.14647 2.1465c.19525.1953.19525.5118 0 .7071s-.51184.1953-.7071 0l-3-3c-.19527-.1953-.19527-.5118 0-.7071l3-3.00001c.19526-.19526.51184-.19526.7071 0s.19525.51185 0 .70711l-2.14642 2.1464L16.2929 11l-2.1465-2.14645c-.1952-.19526-.1952-.51184 0-.7071"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
