// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconStickySmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7.5 7h9c.2761 0 .5.22386.5.5V12h-4.5c-.2761 0-.5.2239-.5.5V17H7.5c-.27614 0-.5-.2239-.5-.5v-9c0-.27614.22386-.5.5-.5m5.5 9.9996a1 1 0 0 0 .6787-.2925l3.0284-3.0284A1 1 0 0 0 16.9996 13H13zM16.5 6h-9C6.67157 6 6 6.67157 6 7.5v9c0 .8284.67157 1.5 1.5 1.5h5.4716c.5304 0 1.0391-.2107 1.4142-.5858l3.0284-3.0284c.3751-.3751.5858-.8838.5858-1.4142V7.5c0-.82843-.6716-1.5-1.5-1.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
