// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconKeyboardShortcutsSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M8 8h2v2H8zm5 2h-2V8h2zm4 0h1V9c0-.55228-.4477-1-1-1zm-1 0V8h-2v2zM6 9c0-.55228.44772-1 1-1v2H6zm6 4v-2h2v2zm3 0v-2h3v2zm-7-2H6v2h2zm1 0v2h2v-2zm-3 3v1c0 .5523.44772 1 1 1h1v-2zm10 2h1c.5523 0 1-.4477 1-1v-1h-2zM5 9c0-1.10457.89543-2 2-2h10c1.1046 0 2 .89543 2 2v6c0 1.1046-.8954 2-2 2H7c-1.10457 0-2-.8954-2-2zm4 5h6v2H9z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
