// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconActionGoSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M13.1463 7.14645c.1953-.19526.5119-.19527.7071-.00001l4.0001 3.99996A.5.5 0 0 1 18 11.5a.5.5 0 0 1-.1465.3536l-4.0001 4c-.1952.1952-.5118.1952-.7071-.0001-.1952-.1952-.1952-.5118 0-.7071L16.2929 12H6.5c-.27614 0-.5-.2239-.5-.5s.22386-.5.5-.5h9.7929l-3.1466-3.14644c-.1952-.19526-.1952-.51184 0-.70711"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
