// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconShapeTextSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M8 7h8c.5523 0 1 .44771 1 1v8c0 .5523-.4477 1-1 1H8c-.55229 0-1-.4477-1-1V8c0-.55229.44771-1 1-1M6 8c0-1.10457.89543-2 2-2h8c1.1046 0 2 .89543 2 2v8c0 1.1046-.8954 2-2 2H8c-1.10457 0-2-.8954-2-2zm3.5 1c-.27614 0-.5.22386-.5.5v1c0 .2761.22386.5.5.5s.5-.2239.5-.5V10h1.5v4H11c-.2761 0-.5.2239-.5.5s.2239.5.5.5h2c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5h-.5v-4H14v.5c0 .2761.2239.5.5.5s.5-.2239.5-.5v-1c0-.27614-.2239-.5-.5-.5h-5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
