// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconFigjamSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5.01362 6.16441a1 1 0 0 1 .27929-.8715 1 1 0 0 1 .8715-.27929l3 .5a1 1 0 0 1 .54271.27929l8.64648 8.64649c.5858.5857.5858 1.5355 0 2.1213l-1.7929 1.7929c-.5858.5858-1.5356.5858-2.1213 0L5.79291 9.70712a1 1 0 0 1-.27929-.54271zm.98639-.1644.1738 1.04276.3262 1.95724.89645.89645 2.5-2.5-.89645-.89645-1.95724-.3262zm4.60359 2.10356L8.10357 10.6036l7.04293 7.0429c.1952.1952.5118.1952.7071 0l1.7929-1.7929c.1952-.1953.1952-.5119 0-.7071z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
