// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconFlipHorizontalSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M12.5 6.5c0-.27614-.2239-.5-.5-.5s-.5.22386-.5.5v11c0 .2761.2239.5.5.5s.5-.2239.5-.5zM6 9.10355c0-.66817.80786-1.0028 1.28033-.53032L10 11.2929c.3905.3905.3905 1.0237 0 1.4142l-2.71967 2.7197C6.80785 15.8993 6 15.5646 6 14.8965zm1 5.18935L9.29289 12 7 9.70711zm11-5.18935c0-.66817-.8079-1.0028-1.2803-.53032L14 11.2929c-.3905.3905-.3905 1.0237 0 1.4142l2.7197 2.7197c.4725.4725 1.2803.1378 1.2803-.5303zm-1 5.18935L14.7071 12 17 9.70711z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
