// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconBold24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M14.5 9.25c0 .9665-.7835 1.75-1.75 1.75H9.5V8c0-.27614.22386-.5.5-.5h2.75c.9665 0 1.75.78351 1.75 1.75M8 11V8c0-1.10457.89543-2 2-2h2.75C14.5449 6 16 7.45508 16 9.25c0 .835-.3149 1.5964-.8324 2.1721C16.259 12.0146 17 13.1708 17 14.5c0 1.933-1.567 3.5-3.5 3.5H10c-1.10457 0-2-.8954-2-2v-5m1.5 1.5V16c0 .2761.22386.5.5.5h3.5c1.1046 0 2-.8954 2-2s-.8954-2-2-2h-4"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
