// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutLayoutHorizontal24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M8 11.5c0 .2761.22386.5.5.5h6.789l-2.3991 2.3883c-.1957.1948-.1964.5114-.0016.7071s.5114.1964.7071.0016l3.2574-3.2427A.5.5 0 0 0 17 11.5c0-.133-.053-.2606-.1472-.3544l-3.2574-3.24263c-.1957-.19482-.5123-.1941-.7071.0016-.1948.19571-.1941.51229.0016.70711L15.289 11H8.5c-.27614 0-.5.2238-.5.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
