// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconRadiusTopLeft24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M12.4781 8H15.5c.2761 0 .5.22386.5.5s-.2239.5-.5.5h-3c-.7083 0-1.2095.00039-1.6013.0324-.3859.03153-.6215.09125-.8067.18559a2 2 0 0 0-.87401.87401c-.09434.1852-.15406.4208-.18559.8067C9.00039 11.2905 9 11.7917 9 12.5v3c0 .2761-.22386.5-.5.5s-.5-.2239-.5-.5v-3.0219c0-.6815-.00001-1.2235.03572-1.6608.03659-.4478.11312-.82965.29126-1.17927a3 3 0 0 1 1.31105-1.31105c.34962-.17814.73147-.25467 1.17927-.29126C11.2546 7.99999 11.7966 8 12.4781 8"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
