// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconMeasureSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5.29289 10.2071c-.39052-.39052-.39052-1.02368 0-1.41421l3.5-3.5c.39053-.39052 1.02369-.39052 1.41421 0l8.5 8.50001c.3905.3905.3905 1.0237 0 1.4142l-3.5 3.5c-.3905.3905-1.0237.3905-1.4142 0zm1.41422 0L6 9.5l.70711-.70711 2.08578-2.08578L9.5 6l.7071.70711 7.0858 7.08579L18 14.5l-.7071.7071-2.0858 2.0858L14.5 18l-.7071-.7071-3.6893-3.6893 1.75-1.75c.1952-.1953.1952-.5119 0-.7072-.1953-.1952-.5119-.1952-.7072 0l-1.74995 1.75-1.2929-1.2928.75-.75c.19527-.1953.19527-.5119 0-.7072-.19526-.19522-.51184-.19522-.7071 0l-.75.75zM13.5 14.5c0 .5523.4477 1 1 1s1-.4477 1-1-.4477-1-1-1-1 .4477-1 1"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
