// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconStrokeDiamondArrow24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5.29289 10.793c-.39052.3905-.39052 1.0237 0 1.4142l2.5 2.5c.39053.3906 1.02369.3906 1.41422 0l2.49999-2.5c.0633-.0633.1164-.133.1592-.2071H18.5c.2761 0 .5-.2238.5-.5 0-.2761-.2239-.5-.5-.5h-6.6337a1.006 1.006 0 0 0-.1592-.2071L9.20711 8.29302c-.39053-.39053-1.02369-.39053-1.41422 0zM11 11.5001l-.7071-.7071-1.08579-1.08577L8.5 9.00012l-.70711.70711L6.70711 10.793 6 11.5001l.70711.7071 1.08578 1.0858.70711.7071.70711-.7071 1.08579-1.0858z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
