// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconArrow24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M12.5 4.5c0-.27614.2239-.5.5-.5h6.5c.2761 0 .5.22386.5.5V11c0 .2761-.2239.5-.5.5s-.5-.2239-.5-.5V5.70711L4.85355 19.8536c-.19526.1952-.51184.1952-.7071 0-.19527-.1953-.19527-.5119 0-.7072L18.2929 5H13c-.2761 0-.5-.22386-.5-.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
