// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconBooleanSubtractSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M10 14v3h7v-7h-3v4z"
      fill="currentColor"
      fill-rule="evenodd"
      fillOpacity="0.3"
    />
    <path
      clip-rule="evenodd"
      d="M17 17h-7v-2h4c.5523 0 1-.4477 1-1v-4h2zm-7-3h4V7H7v7h3m-3 1h2v2c0 .5523.44771 1 1 1h7c.5523 0 1-.4477 1-1v-7c0-.55229-.4477-1-1-1h-2V7c0-.55229-.4477-1-1-1H7c-.55229 0-1 .44771-1 1v7c0 .5523.44771 1 1 1"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
