// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconComment24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7.2 19H12c3.866 0 7-3.134 7-7 0-3.86599-3.134-7-7-7-3.86599 0-7 3.13401-7 7v4.8c0 .5766.00078.9488.02393 1.2322.02219.2716.05987.3723.08506.4218a1 1 0 0 0 .43702.437c.04944.0252.15016.0629.42183.0851C6.25117 18.9992 6.62345 19 7.2 19M12 4c-4.41828 0-8 3.58172-8 8v4.8c0 1.1201 0 1.6802.21799 2.108.19174.3763.4977.6823.87403.874C5.51984 20 6.0799 20 7.2 20H12c4.4183 0 8-3.5817 8-8 0-4.41828-3.5817-8-8-8"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
