// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconNotificationBellBadgedSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <circle cx="16.5" cy="7.5" fill="var(--figma-color-icon-danger)" r="2.5" />
    <path
      clip-rule="evenodd"
      d="M13 6c0 .04201-.0026.08341-.0076.12406C14.7215 6.56543 16 8.13341 16 10v1.1716c0 1.5458.6141 3.0283 1.7071 4.1213.286.286.3716.7161.2168 1.0898S17.4045 17 17 17h-3c0 1.1046-.8954 2-2 2-1.1045 0-2-.8954-2-2H7.00003c-.40446 0-.7691-.2436-.92388-.6173s-.06923-.8038.21677-1.0898c1.09304-1.093 1.70711-2.5755 1.70711-4.1213V10c0-1.86657 1.27851-3.43453 3.00757-3.87593A1.02 1.02 0 0 1 11 6c0-.55228.4477-1 1-1s1 .44772 1 1m-2 11c0 .5523.4477 1 1 1s1-.4477 1-1zm5.1742-2c.2412.3563.5172.6914.8258 1H7.00003a6.825 6.825 0 0 0 .82586-1 6.8285 6.8285 0 0 0 1.17414-3.8284V10c0-1.65685 1.34317-3 2.99997-3 1.6569 0 3 1.34315 3 3v1.1716c0 1.3745.4145 2.7064 1.1742 3.8284"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
