// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconInstanceSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M11.8233 6.59105 6.59105 11.8233c-.09763.0976-.09764.2559 0 .3535l5.23225 5.2323c.0976.0976.2559.0976.3535 0l5.2323-5.2323c.0976-.0976.0976-.2559 0-.3535l-5.2323-5.23225c-.0976-.09763-.2559-.09764-.3535 0m-.7071-.70711L5.88394 11.1162c-.48816.4881-.48816 1.2796 0 1.7677l5.23226 5.2323c.4881.4881 1.2796.4881 1.7677 0l5.2323-5.2323c.4881-.4881.4881-1.2796 0-1.7677l-5.2323-5.23226c-.4881-.48816-1.2796-.48816-1.7677 0"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
