// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconPortrait24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M15 5H9c-.55228 0-1 .44772-1 1v12c0 .5523.44772 1 1 1h6c.5523 0 1-.4477 1-1V6c0-.55228-.4477-1-1-1M9 4c-1.10457 0-2 .89543-2 2v12c0 1.1046.89543 2 2 2h6c1.1046 0 2-.8954 2-2V6c0-1.10457-.8954-2-2-2z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
