// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconStrokeTriangleArrow24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M9.47 8.15176c.30827-.19267.6968-.20287 1.0148-.02665.3179.17623.5152.51112.5152.87465v1.99974h7.5c.2762 0 .5.2238.5.5 0 .2761-.2238.5-.5.5H11v2.0003c0 .3635-.1973.6984-.5152.8746-.318.1762-.70653.166-1.0148-.0266l-4-2.5c-.29238-.1828-.47-.5033-.47-.848 0-.3448.17762-.6653.47-.848zM10 10.179V8.99976l-1 .625-2.0566 1.28534L6 11.4998l.9434.5896L9 13.3748l1 .625V10.179"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
