// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconSwap24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M8.35355 6.35355c.19527-.19526.19527-.51184 0-.7071-.19526-.19527-.51184-.19527-.7071 0l-2.5 2.5c-.19527.19526-.19527.51184 0 .7071l2.5 2.50005c.19526.1952.51184.1952.7071 0 .19527-.1953.19527-.5119 0-.7072L6.70711 9H18.5c.2761 0 .5-.22386.5-.5s-.2239-.5-.5-.5H6.70711zm7.29285 7.00005c-.1952-.1953-.1952-.5119 0-.7072.1953-.1952.5119-.1952.7072 0l2.5 2.5c.1952.1953.1952.5119 0 .7072l-2.5 2.5c-.1953.1952-.5119.1952-.7072 0-.1952-.1953-.1952-.5119 0-.7072L17.2929 16H5.5c-.27614 0-.5-.2239-.5-.5s.22386-.5.5-.5h11.7929z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
