// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconPlayPauseSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M16 7.5c0-.27614-.2239-.5-.5-.5s-.5.22386-.5.5v9c0 .2761.2239.5.5.5s.5-.2239.5-.5zm3 0c0-.27614-.2239-.5-.5-.5s-.5.22386-.5.5v9c0 .2761.2239.5.5.5s.5-.2239.5-.5zM6 8.70578c0-.55476.61452-.88907 1.08028-.58771l5.09112 3.29423c.4263.2758.4263.8996 0 1.1754l-5.09112 3.2942C6.61452 16.1833 6 15.849 6 15.2942zM7.62352 7.2785C6.4924 6.5466 5 7.35852 5 8.70578v6.58842c0 1.3473 1.49242 2.1592 2.62352 1.4273l5.09108-3.2942c1.0353-.6699 1.0353-2.1847 0-2.8546z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
