// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconBranchSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5 7.5c0-.27614.22386-.5.5-.5h2C9.433 7 11 8.567 11 10.5v2c0 1.3807 1.1193 2.5 2.5 2.5h3.7929l-1.1465-1.1464c-.1952-.1953-.1952-.5119 0-.7072.1953-.1952.5119-.1952.7072 0l2 2c.1952.1953.1952.5119 0 .7072l-2 2c-.1953.1952-.5119.1952-.7072 0-.1952-.1953-.1952-.5119 0-.7072L17.2929 16H13.5c-1.933 0-3.5-1.567-3.5-3.5v-2C10 9.11929 8.88071 8 7.5 8h-2c-.27614 0-.5-.22386-.5-.5m8 0c0-.27614.2239-.5.5-.5h5c.2761 0 .5.22386.5.5s-.2239.5-.5.5h-5c-.2761 0-.5-.22386-.5-.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
