// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconBooleanExclude24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5 5h9v5h-4v4H5zm5 9h4v-4h5v9h-9z"
      fill="currentColor"
      fill-rule="evenodd"
      fillOpacity="0.3"
    />
    <path
      clip-rule="evenodd"
      d="M10 15v4h9v-9h-4v4c0 .5523-.4477 1-1 1h-4m.5-1H10v-4h4v4zM9 14H5V5h9v4h-4c-.55229 0-1 .44771-1 1v4m-1 1H5c-.55229 0-1-.4477-1-1V5c0-.55229.44771-1 1-1h9c.5523 0 1 .44771 1 1v4h4c.5523 0 1 .44771 1 1v9c0 .5523-.4477 1-1 1h-9c-.55229 0-1-.4477-1-1v-4z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
