// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconTextLetterSpacing24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M4.5 6c.27614 0 .5.22386.5.5v11c0 .2761-.22386.5-.5.5s-.5-.2239-.5-.5v-11c0-.27614.22386-.5.5-.5m15 0c.2761 0 .5.22386.5.5v11c0 .2761-.2239.5-.5.5s-.5-.2239-.5-.5v-11c0-.27614.2239-.5.5-.5M8.56445 16h1.01563l.80422-2.2656h3.2353L14.4238 16h1.0157L12.502 8h-1zm4.75005-3.125-1.2813-3.60938h-.0625L10.6894 12.875z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
