// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconLayoutOverlayCenter24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M8 5h8c.5523 0 1 .44772 1 1v12c0 .5523-.4477 1-1 1H8c-.55228 0-1-.4477-1-1V6c0-.55228.44772-1 1-1M6 6c0-1.10457.89543-2 2-2h8c1.1046 0 2 .89543 2 2v12c0 1.1046-.8954 2-2 2H8c-1.10457 0-2-.8954-2-2zm4 3c-.55228 0-1 .44772-1 1v4c0 .5523.44772 1 1 1h4c.5523 0 1-.4477 1-1v-4c0-.55228-.4477-1-1-1z"
      fill="currentColor"
      fill-rule="evenodd"
      fillOpacity="0.3"
    />
    <path
      clip-rule="evenodd"
      d="M16 4c1.1046 0 2 .89543 2 2v12c0 1.1046-.8954 2-2 2H8c-1.10457 0-2-.8954-2-2V6c0-1.10457.89543-2 2-2zM8 5c-.55228 0-1 .44772-1 1v12c0 .5523.44772 1 1 1h8c.5523 0 1-.4477 1-1V6c0-.55228-.4477-1-1-1zm2 5v4h4v-4zm-1 0c0-.55228.44772-1 1-1h4c.5523 0 1 .44772 1 1v4c0 .5523-.4477 1-1 1h-4c-.55228 0-1-.4477-1-1z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
