// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconLinkConnected24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M10 8c0-1.10457.8954-2 2-2s2 .89543 2 2v1.5c0 .27614.2239.5.5.5s.5-.22386.5-.5V8c0-1.65686-1.3431-3-3-3S9 6.34314 9 8v1.5c0 .27614.22386.5.5.5s.5-.22386.5-.5zm0 8c0 1.1046.8954 2 2 2s2-.8954 2-2v-1.5c0-.2761.2239-.5.5-.5s.5.2239.5.5V16c0 1.6569-1.3431 3-3 3s-3-1.3431-3-3v-1.5c0-.2761.22386-.5.5-.5s.5.2239.5.5zm2.5-6c0-.27614-.2239-.5-.5-.5s-.5.22386-.5.5v4c0 .2761.2239.5.5.5s.5-.2239.5-.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
