// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconNavigateBack24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M13.8536 7.14645c.1952.19526.1952.51184 0 .7071L9.70711 12l4.14649 4.1464c.1952.1953.1952.5119 0 .7072-.1953.1952-.5119.1952-.7072 0l-4.49995-4.5001A.4998.4998 0 0 1 8.5 12c0-.1326.05268-.2598.14645-.3536l4.49995-4.49995c.1953-.19527.5119-.19527.7072 0"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
