// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutHeightMinmax24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M18 5.5c0 .27614-.2239.5-.5.5h-11c-.27614 0-.5-.22386-.5-.5s.22386-.5.5-.5h11c.2761 0 .5.22386.5.5m0 13c0 .2761-.2239.5-.5.5h-11c-.27614 0-.5-.2239-.5-.5s.22386-.5.5-.5h11c.2761 0 .5.2239.5.5M8.84521 8v8h1.08985v-3.5313H14.064V16h1.0859V8H14.064v3.5195H9.93506V8z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
