// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconTextCapsSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="M17.476 10.5249H18.6c-.245-1.41697-1.456-2.39697-3.025-2.39697-1.882 0-3.256 1.417-3.256 3.73997 0 2.3 1.335 3.731 3.306 3.731 1.764 0 3.025-1.157 3.025-2.993v-.828h-2.858v.906h1.796c-.024 1.172-.799 1.914-1.963 1.914-1.282 0-2.216-.97-2.216-2.738 0-1.761.94-2.72997 2.173-2.72997.966 0 1.62.532 1.893 1.39497zm-11.06395 4.975.668-1.925h2.84l.66495 1.925h1.165L9.13305 8.22693h-1.268l-2.617 7.27297zm.988-2.848 1.072-3.10397h.057l1.071 3.10397z"
      fill="currentColor"
    />
  </svg>
)
