// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconBooleanSubtract24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M10 14v5h9v-9h-5v4z"
      fill="currentColor"
      fill-rule="evenodd"
      fillOpacity="0.3"
    />
    <path
      clip-rule="evenodd"
      d="M10 19v-4h4c.5523 0 1-.4477 1-1v-4h4v9zm0-5h4V5H5v9h5m-5 1h4v4c0 .5523.44771 1 1 1h9c.5523 0 1-.4477 1-1v-9c0-.55229-.4477-1-1-1h-4V5c0-.55229-.4477-1-1-1H5c-.55229 0-1 .44771-1 1v9c0 .5523.44771 1 1 1"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
