// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconSliceSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M17.1661 7.78095c-.3705-.39362-.9931-.40304-1.3753-.02079L12 11.5507v2.7107l5.146-5.14599c.3663-.36627.3752-.9573.0201-1.33446m-5.1752 7.90385 5.8622-5.86228c.7485-.74848.7667-1.95625.0412-2.727-.7572-.80437-2.0295-.82361-2.8106-.04248l-3.9372 3.93706h-.0001l-6.15619 6.1562c-.143.143-.18578.3581-.10839.5449s.25971.3087.46194.3087H9.4687c1.3252 0 2.4125-1.0183 2.5222-2.3151M11 12.5507l-4.44913 4.4492H9.4687c.8457 0 1.5313-.6856 1.5313-1.5313z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
