// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconFillImageSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M16 7H8c-.55229 0-1 .44771-1 1v5.6679l2.52145-2.5214c.19526-.1953.51185-.1953.70705 0l5.8505 5.8504c.5153-.0403.921-.4712.921-.9969V8c0-.55229-.4477-1-1-1m-9 9v-.9179l2.875-2.875L14.6679 17H8c-.55229 0-1-.4477-1-1M8 6c-1.10457 0-2 .89543-2 2v8c0 1.1046.89543 2 2 2h8c1.1046 0 2-.8954 2-2V8c0-1.10457-.8954-2-2-2zm7 4c0 .5523-.4477 1-1 1s-1-.4477-1-1c0-.55229.4477-1 1-1s1 .44771 1 1m1 0c0 1.1046-.8954 2-2 2s-2-.8954-2-2c0-1.10457.8954-2 2-2s2 .89543 2 2"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
