// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconPauseSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7.5 7h2c.27614 0 .5.22386.5.5v9c0 .2761-.22386.5-.5.5h-2c-.27614 0-.5-.2239-.5-.5v-9c0-.27614.22386-.5.5-.5M6 7.5C6 6.67157 6.67157 6 7.5 6h2c.8284 0 1.5.67157 1.5 1.5v9c0 .8284-.6716 1.5-1.5 1.5h-2c-.82843 0-1.5-.6716-1.5-1.5zm8.5-.5h2c.2761 0 .5.22386.5.5v9c0 .2761-.2239.5-.5.5h-2c-.2761 0-.5-.2239-.5-.5v-9c0-.27614.2239-.5.5-.5m-1.5.5c0-.82843.6716-1.5 1.5-1.5h2c.8284 0 1.5.67157 1.5 1.5v9c0 .8284-.6716 1.5-1.5 1.5h-2c-.8284 0-1.5-.6716-1.5-1.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
