// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconStrokeRound24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M19 7.5c0-.27614-.2239-.5-.5-.5H10c-2.76142 0-5 2.23858-5 5 0 2.7614 2.23858 5 5 5h8.5c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5H10c-2.20914 0-4-1.7909-4-4 0-2.20914 1.79086-4 4-4h8.5c.2761 0 .5-.22386.5-.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
