// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconBorderTopLeftBottomSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7 6c-.55229 0-1 .44771-1 1v10c0 .5523.44771 1 1 1h10c.5523 0 1-.4477 1-1v-1c0-.5523-.4477-1-1-1H9V9h8c.5523 0 1-.44771 1-1V7c0-.55229-.4477-1-1-1H7m0 1h10v1H8v8h9v1H7V7m10 3c0-.27614-.2239-.5-.5-.5s-.5.22386-.5.5v1c0 .2761.2239.5.5.5s.5-.2239.5-.5zm0 3c0-.2761-.2239-.5-.5-.5s-.5.2239-.5.5v1c0 .2761.2239.5.5.5s.5-.2239.5-.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
