// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconEffectsSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M10.1056 5.55279C10.275 5.214 10.6212 5 11 5h4c.3603 0 .6927.19379.8702.5073s.1727.69827-.0127 1.0072L13.7662 10H16c.4045 0 .7691.2436.9239.6173s.0692.8038-.2168 1.0898l-6.99999 7c-.33572.3357-.86123.3891-1.2576.1277-.39637-.2613-.55432-.7654-.37799-1.2062L9.52297 14H7.5a1.0001 1.0001 0 0 1-.85065-.4743.9999.9999 0 0 1-.04378-.9729zM9.92297 13H11l-.4 1-.65719 1.643L9 18l1.7951-1.7951L15 12l1-1h-4l.6-1 1.8-3 .6-1h-4l-3 6-.5 1h2.42297"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
