// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconHelp24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M10 10c0-1.10457.8954-2 2-2s2 .89543 2 2c0 .6352-.2926 1.024-.7623 1.2539-.7732.3786-1.7377 1.1079-1.7377 2.2461v.5c0 .2761.2239.5.5.5s.5-.2239.5-.5v-.5c0-.5187.4626-.9979 1.1775-1.348C14.4704 11.7638 15 11.0384 15 10c0-1.65685-1.3431-3-3-3s-3 1.34315-3 3c0 .2761.22386.5.5.5s.5-.2239.5-.5m2 7c.4142 0 .75-.3358.75-.75s-.3358-.75-.75-.75-.75.3358-.75.75.3358.75.75.75"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
