// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconZoomInSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M10.5 15c2.4853 0 4.5-2.0147 4.5-4.5C15 8.01472 12.9853 6 10.5 6 8.01472 6 6 8.01472 6 10.5c0 2.4853 2.01472 4.5 4.5 4.5m0 1c1.3504 0 2.5872-.4867 3.5444-1.2942a.5.5 0 0 0 .1023.1477l3 3c.1953.1953.5118.1953.7071 0 .1953-.1952.1953-.5118 0-.7071l-3-3a.499.499 0 0 0-.1478-.1023C15.5134 13.0869 16 11.8503 16 10.5 16 7.46243 13.5376 5 10.5 5 7.46243 5 5 7.46243 5 10.5c0 3.0376 2.46243 5.5 5.5 5.5m.5-7.5c0-.27614-.2239-.5-.5-.5s-.5.22386-.5.5V10H8.5c-.27614 0-.5.2239-.5.5s.22386.5.5.5H10v1.5c0 .2761.2239.5.5.5s.5-.2239.5-.5V11h1.5c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5H11z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
