// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconDevBrackets24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M13.6464 8.14645c-.1952.19526-.1952.51184 0 .7071L16.7929 12l-3.1465 3.1464c-.1952.1953-.1952.5119 0 .7072.1953.1952.5119.1952.7072 0l3.5-3.5c.1952-.1953.1952-.5119 0-.7072l-3.5-3.49995c-.1953-.19527-.5119-.19527-.7072 0m-3.2928 0c-.1953-.19527-.51189-.19527-.70715 0l-3.5 3.49995c-.19527.1953-.19527.5119 0 .7072l3.5 3.5c.19526.1952.51185.1952.70715 0 .1952-.1953.1952-.5119 0-.7072L7.20711 12l3.14649-3.14645c.1952-.19526.1952-.51184 0-.7071"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
