// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconEmbedCodeSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M16 7H8c-.55229 0-1 .44771-1 1v8c0 .5523.44771 1 1 1h8c.5523 0 1-.4477 1-1V8c0-.55229-.4477-1-1-1M8 6c-1.10457 0-2 .89543-2 2v8c0 1.1046.89543 2 2 2h8c1.1046 0 2-.8954 2-2V8c0-1.10457-.8954-2-2-2zm2.8535 4.1465c.1953.1952.1953.5118 0 .707L9.70711 12l1.14639 1.1465c.1953.1952.1953.5118 0 .707-.1952.1953-.5118.1953-.707 0l-1.50005-1.5c-.19526-.1952-.19526-.5118 0-.707l1.50005-1.5c.1952-.19531.5118-.19531.707 0m2.293.707c-.1953-.1952-.1953-.5118 0-.707.1952-.19531.5118-.19531.707 0l1.5 1.5c.1953.1952.1953.5118 0 .707l-1.5 1.5c-.1952.1953-.5118.1953-.707 0-.1953-.1952-.1953-.5118 0-.707L14.2929 12z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
