// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutHeightHug24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M14.8535 7.14645c.1953.19526.1953.51184 0 .7071l-2.9999 3.00005A.5004.5004 0 0 1 11.5 11a.5004.5004 0 0 1-.3536-.1464L8.14645 7.85355c-.19527-.19526-.19527-.51184 0-.7071.19526-.19527.51184-.19527.7071 0L11.5 9.79289l2.6464-2.64644c.1953-.19526.5119-.19527.7071 0m0 9.70715c-.1952.1952-.5118.1952-.7071 0L11.5 14.2071l-2.64645 2.6465c-.19526.1952-.51184.1952-.7071 0-.19527-.1953-.19527-.5119 0-.7072l2.99995-3A.5004.5004 0 0 1 11.5 13c.1326 0 .2598.0527.3536.1464l2.9999 3c.1953.1953.1953.5119 0 .7072"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
