// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutHeightMax24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M6.5 5c-.27614 0-.5.22386-.5.5s.22386.5.5.5h10c.2761 0 .5-.22386.5-.5s-.2239-.5-.5-.5zm0 13c-.27614 0-.5.2239-.5.5s.22386.5.5.5h10c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5zm4.6464-10.85355c.1953-.19527.5119-.19527.7072 0l2.5 2.5c.1952.19526.1952.51185 0 .70715-.1953.1952-.5119.1952-.7072 0L12 8.70711v6.58579l1.6464-1.6465c.1953-.1952.5119-.1952.7072 0 .1952.1953.1952.5119 0 .7072l-2.5 2.5A.5004.5004 0 0 1 11.5 17a.5004.5004 0 0 1-.3536-.1464l-2.49995-2.5c-.19527-.1953-.19527-.5119 0-.7072.19526-.1952.51184-.1952.7071 0L11 15.2929V8.70711L9.35355 10.3536c-.19526.1952-.51184.1952-.7071 0-.19527-.1953-.19527-.51189 0-.70715z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
