// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconConstraintsSmallLeftCenter24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M9 5c-.27614 0-.5.22386-.5.5s.22386.5.5.5h6c.2761 0 .5-.22386.5-.5S15.2761 5 15 5zm9.5 10.5c-.2761 0-.5-.2239-.5-.5V9c0-.27614.2239-.5.5-.5s.5.22386.5.5v6c0 .2761-.2239.5-.5.5m-10 3c0-.2761.22386-.5.5-.5h6c.2761 0 .5.2239.5.5s-.2239.5-.5.5H9c-.27614 0-.5-.2239-.5-.5m3.5-10c.2761 0 .5.22386.5.5v1c0 .2761-.2239.5-.5.5s-.5-.2239-.5-.5V9c0-.27614.2239-.5.5-.5m0 5c.2761 0 .5.2239.5.5v1c0 .2761-.2239.5-.5.5s-.5-.2239-.5-.5v-1c0-.2761.2239-.5.5-.5"
      fill="currentColor"
      fill-rule="evenodd"
      fillOpacity="0.3"
    />
    <path
      clip-rule="evenodd"
      d="M6 9c0-.27614-.22386-.5-.5-.5S5 8.72386 5 9v6c0 .2761.22386.5.5.5s.5-.2239.5-.5V9m9 3.5c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5H9c-.27614 0-.5.2239-.5.5s.22386.5.5.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
