// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconSend24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M11.6464 5.64645c.1953-.19527.5119-.19527.7072 0l4.5 4.49995c.1952.1953.1952.5119 0 .7072-.1953.1952-.5119.1952-.7072 0L12.5 7.20711V18c0 .2761-.2239.5-.5.5s-.5-.2239-.5-.5V7.20711L7.85355 10.8536c-.19526.1952-.51184.1952-.7071 0-.19527-.1953-.19527-.5119 0-.7072z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
