// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconTableSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M6 13v-3h3v3zm0 1v2c0 .5523.44771 1 1 1h2v-3zm4 3h7c.5523 0 1-.4477 1-1v-2h-8zm8-4v-3h-8v3zm0-4V7c0-.55229-.4477-1-1-1h-7v3zM9 6H7c-.55229 0-1 .44771-1 1v2h3zM5 16V7c0-1.10457.89543-2 2-2h10c1.1046 0 2 .89543 2 2v9c0 1.1046-.8954 2-2 2H7c-1.10457 0-2-.8954-2-2"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
