// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutLayoutWrap24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M15 7c1.1046 0 2 .89543 2 2 0 1.1046-.8954 2-2 2H9.71098l2.39912-2.38829c.1957-.19482.1964-.5114.0016-.7071-.1948-.19571-.5114-.19642-.7071-.0016L8.14725 11.1456A.5002.5002 0 0 0 8 11.5c0 .133.05299.2605.14725.3544l3.25735 3.2426c.1957.1948.5123.1941.7071-.0016s.1941-.5123-.0016-.7071L9.71098 12H15c1.6569 0 3-1.3431 3-3 0-1.65685-1.3431-3-3-3h-.5c-.2761 0-.5.22386-.5.5s.2239.5.5.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
