// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconCommentSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7.89474 17H12c2.7614 0 5-2.2386 5-5 0-2.76142-2.2386-5-5-5-2.76142 0-5 2.23858-5 5v4.1053c0 .1905.00015.3071.00334.3957.00266.0739.00676.0987.0073.1016.04074.1943.19251.346.38675.3868-.00316-.0007.01713.0042.1016.0073.08857.0031.20517.0033.39575.0033M12 6c-3.31371 0-6 2.68629-6 6v4.1053c0 .3668 0 .5503.03192.7025.1222.5828.5775 1.0381 1.16026 1.1603.15225.0319.33569.0319.70256.0319H12c3.3137 0 6-2.6863 6-6 0-3.31371-2.6863-6-6-6"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
