// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconNotesOnRectangleSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7 7h8c.5523 0 1 .44772 1 1H9c-1.10457 0-2 .89543-2 2v5c-.55228 0-1-.4477-1-1V8c0-.55228.44772-1 1-1m0 9c-1.10457 0-2-.8954-2-2V8c0-1.10457.89543-2 2-2h8c1.1046 0 2 .89543 2 2 1.1046 0 2 .89543 2 2v6c0 1.1046-.8954 2-2 2H9c-1.10457 0-2-.8954-2-2m3.5-5c-.2761 0-.5.2239-.5.5s.2239.5.5.5h5c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5zm0 2c-.2761 0-.5.2239-.5.5s.2239.5.5.5h3c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5zM9 9h8c.5523 0 1 .44772 1 1v6c0 .5523-.4477 1-1 1H9c-.55228 0-1-.4477-1-1v-6c0-.55228.44772-1 1-1"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
