// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconNewTab24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M17 16.5c0 .2761-.2239.5-.5.5h-9c-.27614 0-.5-.2239-.5-.5v-9c0-.27614.22386-.5.5-.5h2c.27614 0 .5-.22386.5-.5S9.77614 6 9.5 6h-2C6.67157 6 6 6.67157 6 7.5v9c0 .8284.67157 1.5 1.5 1.5h9c.8284 0 1.5-.6716 1.5-1.5v-2c0-.2761-.2239-.5-.5-.5s-.5.2239-.5.5zm-5-10c0 .27614.2239.5.5.5h3.7929l-4.1464 4.1465c-.1953.1952-.1953.5118 0 .707.1952.1953.5118.1953.707 0L17 7.70711V11.5c0 .2761.2239.5.5.5s.5-.2239.5-.5v-5c0-.27614-.2239-.5-.5-.5h-5c-.2761 0-.5.22386-.5.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
