// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconSticky24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5.5 5h13c.2761 0 .5.22386.5.5V13h-5.5c-.2761 0-.5.2239-.5.5V19H5.5c-.27614 0-.5-.2239-.5-.5v-13c0-.27614.22386-.5.5-.5M14 18.9036c.1025-.0486.1969-.1148.2787-.1965l4.4284-4.4284c.0817-.0818.1479-.1762.1965-.2787H14zM18.5 4h-13C4.67157 4 4 4.67157 4 5.5v13c0 .8284.67157 1.5 1.5 1.5h8.0716c.5304 0 1.0391-.2107 1.4142-.5858l4.4284-4.4284c.3751-.3751.5858-.8838.5858-1.4142V5.5c0-.82843-.6716-1.5-1.5-1.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
