// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconPolygonSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="m12.0003 6.9989-5.76727 9.9814H17.7673zm.487-1.15591c-.2165-.37479-.7575-.3748-.9741-.00001L4.98792 17.1364c-.21668.375.05394.8439.48704.8439H18.5253c.4331 0 .7037-.4689.4871-.8439z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
