// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutPaddingBottom24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M11 11h2v2h-2zm-1 0c0-.5523.4477-1 1-1h2c.5523 0 1 .4477 1 1v2c0 .5523-.4477 1-1 1h-2c-.5523 0-1-.4477-1-1zm-2.5 5c-.27614 0-.5.2239-.5.5s.22386.5.5.5h9c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
