// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconCountStar24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M12.5 6c0-.27614-.2239-.5-.5-.5s-.5.22386-.5.5v4.7929L8.11095 7.40381c-.19526-.19526-.51185-.19526-.70711 0s-.19526.51185 0 .70711L10.7929 11.5H6c-.27614 0-.5.2239-.5.5s.22386.5.5.5h4.7929l-3.3891 3.3891c-.19526.1953-.19526.5118 0 .7071s.51185.1953.70711 0L11.5 13.2071V18c0 .2761.2239.5.5.5s.5-.2239.5-.5v-4.7929l3.3891 3.3891c.1953.1953.5119.1953.7071 0 .1953-.1953.1953-.5118 0-.7071L13.2071 12.5H18c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5h-4.7929l3.3891-3.38908c.1953-.19527.1953-.51185 0-.70711s-.5119-.19526-.7071 0L12.5 10.7929z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
