// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutVertical24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M16.5 7h-9c-.27614 0-.5.22386-.5.5v2c0 .27614.22386.5.5.5h9c.2761 0 .5-.22386.5-.5v-2c0-.27614-.2239-.5-.5-.5m-9-1C6.67157 6 6 6.67157 6 7.5v2c0 .8284.67157 1.5 1.5 1.5h9c.8284 0 1.5-.6716 1.5-1.5v-2c0-.82843-.6716-1.5-1.5-1.5zm2 8h-2c-.27614 0-.5.2239-.5.5v2c0 .2761.22386.5.5.5h2c.27614 0 .5-.2239.5-.5v-2c0-.2761-.22386-.5-.5-.5m-2-1c-.82843 0-1.5.6716-1.5 1.5v2c0 .8284.67157 1.5 1.5 1.5h2c.8284 0 1.5-.6716 1.5-1.5v-2c0-.8284-.6716-1.5-1.5-1.5zm10.3841 1.3201c.1768-.2121.1481-.5274-.064-.7042s-.5274-.1481-.7042.064l-2.1495 2.5794-1.1129-1.1128c-.1952-.1953-.5118-.1953-.707 0-.1953.1952-.1953.5118 0 .707l1.5 1.5a.4995.4995 0 0 0 .3762.146.5.5 0 0 0 .3614-.1794z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
