// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconSidebarsShowDefault24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5 6h14c.5523 0 1 .44771 1 1v10c0 .5523-.4477 1-1 1H5c-.55229 0-1-.4477-1-1V7c0-.55229.44771-1 1-1M3 7c0-1.10457.89543-2 2-2h14c1.1046 0 2 .89543 2 2v10c0 1.1046-.8954 2-2 2H5c-1.10457 0-2-.8954-2-2zm3.14645 3.1465c-.19526.1952-.19526.5118 0 .707L7.29289 12l-1.14644 1.1465c-.19526.1952-.19526.5118 0 .707.19526.1953.51184.1953.7071 0l1.5-1.5c.19526-.1952.19526-.5118 0-.707l-1.5-1.5c-.19526-.19531-.51184-.19531-.7071 0m11.70705 0c.1953.1952.1953.5118 0 .707L16.7071 12l1.1464 1.1465c.1953.1952.1953.5118 0 .707-.1952.1953-.5118.1953-.707 0l-1.5-1.5c-.1953-.1952-.1953-.5118 0-.707l1.5-1.5c.1952-.19531.5118-.19531.707 0"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
