// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconPlaySmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M10.1587 7.17447C9.6598 6.85016 9 7.20822 9 7.8033v8.3933c0 .5951.6598.9531 1.1587.6288l6.6499-4.3224c.364-.2366.364-.7695 0-1.0061zM8 7.8033c0-1.38852 1.53954-2.224 2.7037-1.46727l6.6499 4.32237c.9707.631.9707 2.0521 0 2.6831l-6.6499 4.3224C9.53954 18.4206 8 17.5851 8 16.1966z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
