// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconGradientDiamondSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M8 6c-1.10457 0-2 .89543-2 2v8c0 1.1046.89543 2 2 2h8c1.1046 0 2-.8954 2-2V8c0-1.10457-.8954-2-2-2zm.46449 5.2929c-.39052.3905-.39052 1.0237 0 1.4142l2.82841 2.8284c.3905.3906 1.0237.3906 1.4142 0l2.8285-2.8284c.3905-.3905.3905-1.0237 0-1.4142l-2.8285-2.82843c-.3905-.39053-1.0237-.39053-1.4142 0z"
      fill="currentColor"
      fill-rule="evenodd"
      fillOpacity="0.3"
    />
    <path
      clip-rule="evenodd"
      d="M8 7h8c.5523 0 1 .44772 1 1v8c0 .5523-.4477 1-1 1H8c-.55228 0-1-.4477-1-1V8c0-.55228.44772-1 1-1M6 8c0-1.10457.89543-2 2-2h8c1.1046 0 2 .89543 2 2v8c0 1.1046-.8954 2-2 2H8c-1.10457 0-2-.8954-2-2zm3.17157 4L12 9.17157 14.8284 12 12 14.8284zm-.7071.7071c-.39053-.3905-.39053-1.0237 0-1.4142l2.82843-2.82843c.3905-.39053 1.0237-.39053 1.4142 0l2.8284 2.82843c.3906.3905.3906 1.0237 0 1.4142l-2.8284 2.8284c-.3905.3906-1.0237.3906-1.4142 0z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
