// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconMicrophoneSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M13 7v5c0 .5523-.4477 1-1 1s-1-.4477-1-1V7c0-.55228.4477-1 1-1s1 .44772 1 1m-3 0c0-1.10457.8954-2 2-2s2 .89543 2 2v5c0 1.1046-.8954 2-2 2s-2-.8954-2-2zm-1.5 4.5c0-.2761-.22386-.5-.5-.5s-.5.2239-.5.5v.5c0 2.3163 1.75002 4.2238 4 4.4725V18h-2c-.27614 0-.5.2239-.5.5s.22386.5.5.5h5c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5h-2v-1.5275c2.25-.2487 4-2.1562 4-4.4725v-.5c0-.2761-.2239-.5-.5-.5s-.5.2239-.5.5v.5c0 1.933-1.567 3.5-3.5 3.5S8.5 13.933 8.5 12z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
