// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconFigjam24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M4.00773 5.12404a.99998.99998 0 0 1 1.11631-1.11631l4 .5a1 1 0 0 1 .58307.28517L19.5 14.5858c.7811.781.7811 2.0474 0 2.8284L17.4142 19.5c-.781.7811-2.0474.7811-2.8284 0L4.7929 9.70711a1 1 0 0 1-.28517-.58307zM16.7071 18.7929l2.0858-2.0858c.3905-.3905.3905-1.0237 0-1.4142l-8.4393-8.43933-3.50002 3.50003h-.00001l8.43933 8.4393c.3905.3905 1.0237.3905 1.4142 0M6.14646 9.64646l.00002-.00001 3.49998-3.49999-.64645-.64645-2.97622-.37203-1.02378-.12797.12797 1.02378.37203 2.97622z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
