// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconSearchSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M15 10.5c0 2.4853-2.0147 4.5-4.5 4.5C8.01472 15 6 12.9853 6 10.5 6 8.01472 8.01472 6 10.5 6c2.4853 0 4.5 2.01472 4.5 4.5m-.9556 4.2058C13.0872 15.5133 11.8504 16 10.5 16 7.46243 16 5 13.5376 5 10.5 5 7.46243 7.46243 5 10.5 5c3.0376 0 5.5 2.46243 5.5 5.5 0 1.3503-.4866 2.5869-1.294 3.5441a.499.499 0 0 1 .1478.1023l3 3c.1953.1953.1953.5119 0 .7071-.1953.1953-.5118.1953-.7071 0l-3-3a.5.5 0 0 1-.1023-.1477"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
