// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconApprovedCheckmark24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M18 12c0 3.3137-2.6863 6-6 6-3.31371 0-6-2.6863-6-6 0-3.31371 2.68629-6 6-6 3.3137 0 6 2.68629 6 6m1 0c0 3.866-3.134 7-7 7s-7-3.134-7-7 3.134-7 7-7 7 3.134 7 7m-4.0713-2.24275c.1421-.23679.0653-.54392-.1715-.68599-.2367-.14208-.5439-.06529-.6859.17149l-2.5935 4.32245-1.56177-2.3425c-.15318-.2298-.46362-.2919-.69337-.1387-.22977.1532-.29186.4636-.13869.6933l2.00003 3c.095.1427.2565.2266.4279.2226a.5.5 0 0 0 .4168-.2427z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
