// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconNotesOnRectangle24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5 6h10c.5523 0 1 .44772 1 1v1H9c-1.10457 0-2 .89543-2 2v5H5c-.55228 0-1-.4477-1-1V7c0-.55228.44772-1 1-1m2 10H5c-1.10457 0-2-.8954-2-2V7c0-1.10457.89543-2 2-2h10c1.1046 0 2 .89543 2 2v1h2c1.1046 0 2 .89543 2 2v7c0 1.1046-.8954 2-2 2H9c-1.10457 0-2-.8954-2-2zm3.5-5c-.2761 0-.5.2239-.5.5s.2239.5.5.5h7c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5zm0 2c-.2761 0-.5.2239-.5.5s.2239.5.5.5h5c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5zM9 9h10c.5523 0 1 .44772 1 1v7c0 .5523-.4477 1-1 1H9c-.55228 0-1-.4477-1-1v-7c0-.55228.44772-1 1-1"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
