// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconMicrophone24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M14 6v5c0 1.1046-.8954 2-2 2s-2-.8954-2-2V6c0-1.10457.8954-2 2-2s2 .89543 2 2M9 6c0-1.65685 1.3431-3 3-3s3 1.34315 3 3v5c0 1.6569-1.3431 3-3 3s-3-1.3431-3-3zm-2 5c0-.2761-.22386-.5-.5-.5s-.5.2239-.5.5v.1667c0 3.1098 2.43344 5.6512 5.5 5.8239V20h-3c-.27614 0-.5.2239-.5.5s.22386.5.5.5h7c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5h-3v-3.0094c3.0666-.1727 5.5-2.7141 5.5-5.8239V11c0-.2761-.2239-.5-.5-.5s-.5.2239-.5.5v.1667C17 13.836 14.836 16 12.1667 16h-.3334C9.16396 16 7 13.836 7 11.1667z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
