// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconNoodle24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="m20.8536 6.85355-3 3c-.1953.19525-.5119.19525-.7072 0-.1952-.19526-.1952-.51184 0-.7071L19.2929 7H15.5C14.1193 7 13 8.11929 13 9.5v5c0 1.933-1.567 3.5-3.5 3.5h-.55001C8.71836 19.1411 7.70948 20 6.5 20 5.11929 20 4 18.8807 4 17.5S5.11929 15 6.5 15c1.20948 0 2.21836.8589 2.44999 2H9.5c1.3807 0 2.5-1.1193 2.5-2.5v-5C12 7.567 13.567 6 15.5 6h3.7929l-2.1465-2.14645c-.1952-.19526-.1952-.51184 0-.7071.1953-.19527.5119-.19527.7072 0l3 3c.1952.19526.1952.51184 0 .7071M8 17.5c0-.8284-.67157-1.5-1.5-1.5S5 16.6716 5 17.5 5.67157 19 6.5 19 8 18.3284 8 17.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
