// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconInspect24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5 6.5C5 5.67157 5.67157 5 6.5 5h10c.8284 0 1.5.67157 1.5 1.5v5c0 .2761.2239.5.5.5s.5-.2239.5-.5v-5C19 5.11929 17.8807 4 16.5 4h-10C5.11929 4 4 5.11929 4 6.5v10C4 17.8807 5.11929 19 6.5 19h5c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5h-5c-.82843 0-1.5-.6716-1.5-1.5zm15.2941 9.5986c.4062-.125.6891-.4931.7052-.9178.0161-.4248-.238-.8133-.6337-.9687l-8-3.1429c-.3702-.1454-.7914-.0576-1.0727.2237s-.3691.7025-.2237 1.0727l3.1429 8c.1554.3957.5439.6498.9687.6337.4247-.0161.7928-.299.9178-.7052l.9872-3.2083zm-1.8278-.4839-2.1806.671-.671 2.1806L15.1429 20l-.5868-1.4935-2.057-5.236L12 12l1.2705.4991 5.236 2.057L20 15.1429z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
