// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconInsertSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M18 12c0 3.3137-2.6863 6-6 6-3.31371 0-6-2.6863-6-6 0-3.31371 2.68629-6 6-6 3.3137 0 6 2.68629 6 6m1 0c0 3.866-3.134 7-7 7s-7-3.134-7-7 3.134-7 7-7 7 3.134 7 7m-6.5-2.5c0-.27614-.2239-.5-.5-.5s-.5.22386-.5.5v2h-2c-.27614 0-.5.2239-.5.5s.22386.5.5.5h2v2c0 .2761.2239.5.5.5s.5-.2239.5-.5v-2h2c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5h-2z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
