// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconFillScreenSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M6.5 7h11c.2761 0 .5.22386.5.5v9c0 .2761-.2239.5-.5.5h-11c-.27614 0-.5-.2239-.5-.5v-9c0-.27614.22386-.5.5-.5M5 7.5C5 6.67157 5.67157 6 6.5 6h11c.8284 0 1.5.67157 1.5 1.5v9c0 .8284-.6716 1.5-1.5 1.5h-11c-.82843 0-1.5-.6716-1.5-1.5zm2.5.5c-.27614 0-.5.22386-.5.5v2c0 .2761.22386.5.5.5s.5-.2239.5-.5V9h1.5c.27614 0 .5-.22386.5-.5S9.77614 8 9.5 8zm7 0c-.2761 0-.5.22386-.5.5s.2239.5.5.5H16v1.5c0 .2761.2239.5.5.5s.5-.2239.5-.5v-2c0-.27614-.2239-.5-.5-.5zM8 13.5c0-.2761-.22386-.5-.5-.5s-.5.2239-.5.5v2c0 .2761.22386.5.5.5h2c.27614 0 .5-.2239.5-.5s-.22386-.5-.5-.5H8zm9 0c0-.2761-.2239-.5-.5-.5s-.5.2239-.5.5V15h-1.5c-.2761 0-.5.2239-.5.5s.2239.5.5.5h2c.2761 0 .5-.2239.5-.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
