// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconNotificationBellFilledBadgedSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <circle cx="16.5" cy="7.5" fill="var(--figma-color-icon-danger)" r="2.5" />
    <path
      clip-rule="evenodd"
      d="M13 6c0 .04201-.0026.08341-.0076.12406C14.7215 6.56543 16 8.13341 16 10v1.1716c0 1.5458.6141 3.0283 1.7071 4.1213.286.286.3716.7161.2168 1.0898S17.4045 17 17 17H7.00003c-.40447 0-.7691-.2436-.92388-.6173s-.06923-.8038.21677-1.0898c1.09304-1.093 1.70711-2.5755 1.70711-4.1213V10c0-1.86657 1.27851-3.43453 3.00757-3.87593A1.02 1.02 0 0 1 11 6c0-.55228.4477-1 1-1s1 .44772 1 1m4 10a6.824 6.824 0 0 1-.8258-1C15.4145 13.878 15 12.5461 15 11.1716V10c0-1.25297-.7681-2.32653-1.8592-2.77547C14.2319 7.67347 15 8.74704 15 10v1.1716c0 1.811.7194 3.5478 2 4.8284m-5 3c.7403 0 1.3867-.4022 1.7325-1h-3.4649c.3458.5978.9921 1 1.7324 1"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
