// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconActionBackSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M8.85355 7.14645c.19526.19526.19527.51184 0 .7071L6.7071 10H15.5c1.933 0 3.5 1.567 3.5 3.5S17.433 17 15.5 17h-1c-.2761 0-.5-.2238-.5-.5 0-.2761.2239-.5.5-.5h1c1.3807 0 2.5-1.1193 2.5-2.5S16.8807 11 15.5 11H6.70711l2.14644 2.1464c.19526.1953.19527.5119 0 .7072-.19526.1952-.51184.1952-.7071 0l-3-3A.5002.5002 0 0 1 5 10.5c0-.1326.05268-.2598.14645-.3535l3-3.00005c.19526-.19526.51184-.19527.7071 0"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
