// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconSection24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M13 5h5c.5523 0 1 .44771 1 1v12c0 .5523-.4477 1-1 1H6c-.55229 0-1-.4477-1-1v-8h7c.5523 0 1-.44771 1-1zm-1 0H6c-.55229 0-1 .44771-1 1v3h7zm0-1h6c1.1046 0 2 .89543 2 2v12c0 1.1046-.8954 2-2 2H6c-1.10457 0-2-.8954-2-2V6c0-1.10457.89543-2 2-2z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
