// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconRecentSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M12 19c3.866 0 7-3.134 7-7 0-3.86599-3.134-7-7-7-3.86599 0-7 3.13401-7 7 0 3.866 3.13401 7 7 7m6-7c0 3.3137-2.6863 6-6 6-3.31371 0-6-2.6863-6-6 0-3.31371 2.68629-6 6-6 3.3137 0 6 2.68629 6 6m-5.5-3.5c0-.27614-.2239-.5-.5-.5s-.5.22386-.5.5V12c0 .1326.0527.2598.1464.3536l2 2c.1953.1952.5119.1952.7072 0 .1952-.1953.1952-.5119 0-.7072L12.5 11.7929z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
