// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconConstraintsSmallLeftBottom24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M9 5c-.27614 0-.5.22386-.5.5s.22386.5.5.5h6c.2761 0 .5-.22386.5-.5S15.2761 5 15 5zm3.5 4c0-.27614-.2239-.5-.5-.5s-.5.22386-.5.5v2.5H9c-.27614 0-.5.2239-.5.5s.22386.5.5.5h2.5V15c0 .2761.2239.5.5.5s.5-.2239.5-.5v-2.5H15c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5h-2.5zm5.5 6c0 .2761.2239.5.5.5s.5-.2239.5-.5V9c0-.27614-.2239-.5-.5-.5s-.5.22386-.5.5v6"
      fill="currentColor"
      fill-rule="evenodd"
      fillOpacity="0.3"
    />
    <path
      clip-rule="evenodd"
      d="M6 9c0-.27614-.22386-.5-.5-.5S5 8.72386 5 9v6c0 .2761.22386.5.5.5s.5-.2239.5-.5V9m3 9c-.27614 0-.5.2239-.5.5s.22386.5.5.5h6c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
