// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconLine24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M19.8536 4.14645c.1952.19526.1952.51184 0 .7071L4.85355 19.8536c-.19526.1952-.51184.1952-.7071 0-.19527-.1953-.19527-.5119 0-.7072L19.1464 4.14645c.1953-.19527.5119-.19527.7072 0"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
