// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconMinus24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M6 12c0-.2761.22386-.5.5-.5h11c.2761 0 .5.2239.5.5s-.2239.5-.5.5h-11c-.27614 0-.5-.2239-.5-.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
