// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconSpacingVerticalSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M16 9c0 .55229-.4477 1-1 1H9c-.55228 0-1-.44772-1-1V7c0-.55228.44772-1 1-1h6c.5523 0 1 .44772 1 1zm-2 0h1V7H9v2h5m4 2.5c0 .2761-.2239.5-.5.5h-11c-.27614 0-.5-.2239-.5-.5s.22386-.5.5-.5h11c.2761 0 .5.2239.5.5M15 17c.5523 0 1-.4477 1-1v-2c0-.5523-.4477-1-1-1H9c-.55228 0-1 .4477-1 1v2c0 .5523.44772 1 1 1zm0-1H9v-2h6v2"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
