// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconMention24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M12 6c-3.31371 0-6 2.68629-6 6 0 3.3137 2.68629 6 6 6 .2761 0 .5.2239.5.5s-.2239.5-.5.5c-3.866 0-7-3.134-7-7s3.134-7 7-7 7 3.134 7 7v.5c0 1.3807-1.1193 2.5-2.5 2.5-.8936 0-1.6776-.4688-2.1197-1.1738C13.8319 14.5399 12.9697 15 12 15c-1.6569 0-3-1.3431-3-3s1.3431-3 3-3c.7684 0 1.4692.28885 2 .76389V9.5c0-.27614.2239-.5.5-.5s.5.22386.5.5v3c0 .8284.6716 1.5 1.5 1.5s1.5-.6716 1.5-1.5V12c0-3.31371-2.6863-6-6-6m2 6c0-1.1046-.8954-2-2-2s-2 .8954-2 2 .8954 2 2 2 2-.8954 2-2"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
