// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconBorderTopRightBottomSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7 6c-.55229 0-1 .44771-1 1v1c0 .55229.44771 1 1 1h8v6H7c-.55229 0-1 .4477-1 1v1c0 .5523.44771 1 1 1h10c.5523 0 1-.4477 1-1V7c0-.55229-.4477-1-1-1H7m0 1h10v10H7v-1h9V8H7zm1 3c0-.27614-.22386-.5-.5-.5s-.5.22386-.5.5v1c0 .2761.22386.5.5.5s.5-.2239.5-.5zm0 3c0-.2761-.22386-.5-.5-.5s-.5.2239-.5.5v1c0 .2761.22386.5.5.5s.5-.2239.5-.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
