// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutWidthFill24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M9.35355 8.14645c.19527.19526.19527.51184 0 .7071L7.20713 11l9.58567-.0002-2.1463-2.14623c-.1953-.19526-.1953-.51184-.0001-.70711.1953-.19527.5119-.19528.7071-.00003l3 2.99977a.4999.4999 0 0 1 .1465.3535c0 .1326-.0527.2598-.1464.3536l-3 3.0002c-.1953.1953-.5119.1953-.7071.0001-.1953-.1953-.1953-.5119-.0001-.7071l2.1465-2.1467L7.20708 12l2.14647 2.1464c.19527.1953.19527.5119 0 .7072-.19526.1952-.51184.1952-.7071 0l-3-3c-.19527-.1953-.19527-.5119 0-.7072l3-2.99995c.19526-.19527.51184-.19527.7071 0"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
