// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconChild24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M11.5 6c.2761 0 .5.22386.5.5V11c0 .5523.4477 1 1 1h4.5c.2761 0 .5.2239.5.5s-.2239.5-.5.5H13c-1.1046 0-2-.8954-2-2V6.5c0-.27614.2239-.5.5-.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
