// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconPreviewPrototypeSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M15 7H9v1h6zm1 0v1h1V7zM7 7h1v1H7zm10 2H7v8h10zM7 6c-.55228 0-1 .44772-1 1v10c0 .5523.44772 1 1 1h10c.5523 0 1-.4477 1-1V7c0-.55228-.4477-1-1-1zm5.5361 7.5784.2047-.1229.4019-.2411c.1618-.0971.1618-.3317 0-.4288l-.4019-.2411-.2047-.1229-.0079-.0047L12 12.1l-.0145-.0087-.2496-.1498-.3573-.2143c-.1666-.1-.3786.02-.3786.2143v2.117c0 .1943.212.3143.3786.2143l.3573-.2143.2496-.1498L12 13.9l.5282-.3169zm1.1211-1.6503-1.7641-1.0584C11.06 10.3698 10 10.9699 10 11.9415v2.117c0 .9716 1.06 1.5717 1.8931 1.0718l1.7641-1.0584c.8092-.4855.8092-1.6583 0-2.1438"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
