// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutConstrainVert24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M8.5 6.50024c0-.27614.22386-.5.5-.5h5c.2761 0 .5.22386.5.5 0 .27615-.2239.5-.5.5h-2v8.99996h2c.2761 0 .5.2239.5.5 0 .2762-.2239.5-.5.5H9c-.27614 0-.5-.2238-.5-.5 0-.2761.22386-.5.5-.5h2V7.00024H9c-.27614 0-.5-.22385-.5-.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
