// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconBlendModeSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M12 15.9999c1.6569 0 3-1.3432 3-3 0-.8264-.42-1.9887-1.0776-3.24573C13.3085 8.58051 12.5596 7.45671 12 6.67141c-.5596.7853-1.3085 1.9091-1.9224 3.08276C9.42004 11.0112 9 12.1735 9 12.9999c0 1.6568 1.3431 3 3 3m0 1c2.2091 0 4-1.7909 4-4 0-2.1703-2.0934-5.38736-3.2514-7.00079-.3736-.52062-1.1236-.52062-1.4972 0C10.0934 7.61254 8 10.8296 8 12.9999c0 2.2091 1.79086 4 4 4"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
