// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutWidthMinmax24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5.5 18c-.27614 0-.5-.2239-.5-.5v-11c0-.27614.22386-.5.5-.5s.5.22386.5.5v11c0 .2761-.22386.5-.5.5m13 0c-.2761 0-.5-.2239-.5-.5v-11c0-.27614.2239-.5.5-.5s.5.22386.5.5v11c0 .2761-.2239.5-.5.5M7.604 8l1.88236 8h1.02904L12 10.0616 13.4846 16h1.0291l1.8823-8h-1.0273l-1.3834 5.8795L12.5154 8h-1.0308l-1.4699 5.8795L8.63131 8z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
