// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconDockToSide24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5 7.5C5 6.11929 6.11929 5 7.5 5h9C17.8807 5 19 6.11929 19 7.5v6.1716c0 2.2272-2.6929 3.3427-4.2678 1.7677L10 10.7071V14c0 .2761-.22386.5-.5.5S9 14.2761 9 14V9.5c0-.27614.22386-.5.5-.5H14c.2761 0 .5.22386.5.5s-.2239.5-.5.5h-3.2929l4.7322 4.7322c.945.945 2.5607.2757 2.5607-1.0606V7.5c0-.82843-.6716-1.5-1.5-1.5h-9C6.67157 6 6 6.67157 6 7.5v9c0 .8284.67157 1.5 1.5 1.5h5c.2761 0 .5.2239.5.5s-.2239.5-.5.5h-5C6.11929 19 5 17.8807 5 16.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
