// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconHomeSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M11 17c0 .5523-.4477 1-1 1H7c-.55228 0-1-.4477-1-1v-7c0-.30378.13809-.5911.3753-.78087l5-4c.3652-.29217.8842-.29217 1.2494 0l5 4C17.8619 9.4089 18 9.69622 18 10v7c0 .5523-.4477 1-1 1h-3c-.5523 0-1-.4477-1-1v-4h-2zm-3 0H7v-7l5-4 5 4v7h-3v-4c0-.5523-.4477-1-1-1h-2c-.5523 0-1 .4477-1 1v4H8"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
