// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconTemplateSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7 7h10c.5523 0 1 .44771 1 1v2H6V8c0-.55229.44771-1 1-1m-1 4v5c0 .5523.44771 1 1 1h2v-6zm4 6h7c.5523 0 1-.4477 1-1v-5h-8zM5 8c0-1.10457.89543-2 2-2h10c1.1046 0 2 .89543 2 2v8c0 1.1046-.8954 2-2 2H7c-1.10457 0-2-.8954-2-2z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
