// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutLayoutVertical24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M12.5 7c-.2762 0-.5.22386-.5.5v6.789l-2.38832-2.3991c-.19482-.1957-.5114-.1964-.70711-.0016-.1957.1948-.19642.5114-.0016.7071l3.24263 3.2574A.5003.5003 0 0 0 12.5 16c.133 0 .2605-.053.3543-.1472l3.2427-3.2574c.1948-.1957.1941-.5123-.0016-.7071s-.5123-.1941-.7071.0016L13 14.289V7.5c0-.27614-.2239-.5-.5-.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
