// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconNumberList24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M11 7c0-.27614.2238-.5.5-.5h6c.2761 0 .5.22386.5.5s-.2239.5-.5.5h-6c-.2762 0-.5-.22386-.5-.5m-5 .00001c0-.27614.22386-.5.5-.5h1c.27614 0 .5.22386.5.5V10.5c0 .2762-.22386.5-.5.5s-.5-.2238-.5-.5V7.50001h-.5c-.27614 0-.5-.22385-.5-.5M6 13.5c0-.2761.22386-.5.5-.5h2c.27614 0 .5.2239.5.5V15c0 .1894-.107.3625-.27639.4472L7 16.309v.191h1.5c.27614 0 .5.2239.5.5 0 .2762-.22386.5-.5.5h-2c-.27614 0-.5-.2238-.5-.5v-1c0-.1894.107-.3625.27639-.4472L8 14.691V14H6.5c-.27614 0-.5-.2238-.5-.5m5.5 3c-.2762 0-.5.2239-.5.5s.2238.5.5.5h6c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5zm0-5c-.2762 0-.5.2239-.5.5s.2238.5.5.5h6c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
