// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconBorderTopLeftRightSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7 6c-.55229 0-1 .44771-1 1v10c0 .5523.44771 1 1 1h1c.55229 0 1-.4477 1-1V9h6v8c0 .5523.4477 1 1 1h1c.5523 0 1-.4477 1-1V7c0-.55229-.4477-1-1-1H7m0 1h10v10h-1V8H8v9H7V7m3 9c-.27614 0-.5.2239-.5.5s.22386.5.5.5h1c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5zm3 0c-.2761 0-.5.2239-.5.5s.2239.5.5.5h1c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
