// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconChevronUp24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M11.6464 10.1464c.1953-.19522.5119-.19522.7072 0l2 2c.1952.1953.1952.5119 0 .7072-.1953.1952-.5119.1952-.7072 0L12 11.2071l-1.6464 1.6465c-.1953.1952-.51189.1952-.70715-.0001-.19527-.1952-.19527-.5118 0-.7071z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
