// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconInteractionKeySmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M10.5 5C9.67157 5 9 5.67157 9 6.5V9H6.5C5.67157 9 5 9.67157 5 10.5v3c0 .8284.67157 1.5 1.5 1.5H9v2.5c0 .8284.67157 1.5 1.5 1.5h3c.8284 0 1.5-.6716 1.5-1.5V15h2.5c.8284 0 1.5-.6716 1.5-1.5v-3c0-.82843-.6716-1.5-1.5-1.5H15V6.5c0-.82843-.6716-1.5-1.5-1.5zM10 6.5V10H6.5c-.27614 0-.5.2239-.5.5v3c0 .2761.22386.5.5.5H10v3.5c0 .2761.2239.5.5.5h3c.2761 0 .5-.2239.5-.5V14h3.5c.2761 0 .5-.2239.5-.5v-3c0-.2761-.2239-.5-.5-.5H14V6.5c0-.27614-.2239-.5-.5-.5h-3c-.2761 0-.5.22386-.5.5m3 5.5c0 .5523-.4477 1-1 1s-1-.4477-1-1 .4477-1 1-1 1 .4477 1 1m1 0c0 1.1046-.8954 2-2 2s-2-.8954-2-2 .8954-2 2-2 2 .8954 2 2"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
