// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconResolve24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M18.9 12.0001c0 3.8108-3.0893 6.9-6.9 6.9-3.81079 0-6.90002-3.0892-6.90002-6.9 0-3.81077 3.08923-6.9 6.90002-6.9 3.8107 0 6.9 3.08923 6.9 6.9m1 0c0 4.363-3.537 7.9-7.9 7.9-4.36307 0-7.90002-3.537-7.90002-7.9 0-4.36305 3.53695-7.9 7.90002-7.9 4.363 0 7.9 3.53695 7.9 7.9m-4.4681-2.74799c.1392-.23852.0586-.54468-.1799-.68382s-.5447-.05858-.6838.17995l-3.1406 5.38386-2.04343-2.452c-.17679-.2122-.49207-.2408-.70421-.064-.21214.1767-.2408.492-.06401.7042l2.49995 3a.5001.5001 0 0 0 .4258.1781.4998.4998 0 0 0 .3902-.2463z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
