// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconReplaceSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M17.8536 11.6464c.1952.1953.1952.5119 0 .7072l-3.5 3.5c-.1953.1952-.5119.1952-.7072 0-.1952-.1953-.1952-.5119 0-.7072L16.2929 12.5H6.5c-.27614 0-.5-.2239-.5-.5s.22386-.5.5-.5h9.7929l-2.6465-2.64645c-.1952-.19526-.1952-.51184 0-.7071.1953-.19527.5119-.19527.7072 0z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
