// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconBooleanUnionSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M14 7H7v7h3v3h7v-7h-3z"
      fill="currentColor"
      fill-rule="evenodd"
      fillOpacity="0.3"
    />
    <path
      clip-rule="evenodd"
      d="M10 14v3h7v-7h-3V7H7v7h3m-2 1H7c-.55228 0-1-.4477-1-1V7c0-.55228.44772-1 1-1h7c.5523 0 1 .44772 1 1v2h2c.5523 0 1 .44772 1 1v7c0 .5523-.4477 1-1 1h-7c-.55228 0-1-.4477-1-1v-2z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
