// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconConstraintsSmallCenterTopBottom24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M6 9c0-.27614-.22386-.5-.5-.5S5 8.72386 5 9v6c0 .2761.22386.5.5.5s.5-.2239.5-.5V9m12.5 6.5c-.2761 0-.5-.2239-.5-.5V9c0-.27614.2239-.5.5-.5s.5.22386.5.5v6c0 .2761-.2239.5-.5.5m-8.5-4c.2761 0 .5.2239.5.5s-.2239.5-.5.5H9c-.27614 0-.5-.2239-.5-.5s.22386-.5.5-.5zm4 1c-.2761 0-.5-.2239-.5-.5s.2239-.5.5-.5h1c.2761 0 .5.2239.5.5s-.2239.5-.5.5z"
      fill="currentColor"
      fill-rule="evenodd"
      fillOpacity="0.3"
    />
    <path
      clip-rule="evenodd"
      d="M15.5 5.5c0 .27614-.2239.5-.5.5H9c-.27614 0-.5-.22386-.5-.5S8.72386 5 9 5h6c.2761 0 .5.22386.5.5m0 13c0 .2761-.2239.5-.5.5H9c-.27614 0-.5-.2239-.5-.5s.22386-.5.5-.5h6c.2761 0 .5.2239.5.5m-3-9.5c0-.27614-.2239-.5-.5-.5s-.5.22386-.5.5v6c0 .2761.2239.5.5.5s.5-.2239.5-.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
