// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconTable24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M4 14v-4h5v4zm-1 1V6c0-1.10457.89543-2 2-2h14c1.1046 0 2 .89543 2 2v12c0 1.1046-.8954 2-2 2H5c-1.10457 0-2-.8954-2-2zm1-6h5V5H5c-.55228 0-1 .44772-1 1zm6-4v4h10V6c0-.55229-.4477-1-1-1h-9m10 5H10v4h10zm0 5H10v4h9c.5523 0 1-.4477 1-1zM9 19H5c-.55229 0-1-.4477-1-1v-3h5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
