// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconCommentNewSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M12 17H7.89474c-.19058 0-.30718-.0002-.39575-.0033-.07393-.0027-.09869-.0068-.10161-.0073h.00001c-.0002-.0001-.0003-.0001-.00031-.0001 0 0 .00009 0 .00029.0001a.5001.5001 0 0 1-.38673-.3868c-.00054-.0029-.00464-.0277-.0073-.1016C7.00015 16.4124 7 16.2958 7 16.1053V12c0-2.76142 2.23858-5 5-5 2.7614 0 5 2.23858 5 5 0 2.7614-2.2386 5-5 5m-6-5c0-3.31371 2.68629-6 6-6 3.3137 0 6 2.68629 6 6 0 3.3137-2.6863 6-6 6H7.89474c-.36687 0-.55031 0-.70256-.0319-.58276-.1222-1.03806-.5775-1.16026-1.1603C6 16.6556 6 16.4721 6 16.1053z"
      fill="currentColor"
      fill-rule="evenodd"
    />
    <circle cx="16" cy="8" fill="var(--figma-color-icon-danger)" r="2" />
  </svg>
)
