// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconPasswordSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7 9h10c.5523 0 1 .44772 1 1v4c0 .5523-.4477 1-1 1H7c-.55228 0-1-.4477-1-1v-4c0-.55228.44772-1 1-1m-2 1c0-1.10457.89543-2 2-2h10c1.1046 0 2 .89543 2 2v4c0 1.1046-.8954 2-2 2H7c-1.10457 0-2-.8954-2-2zm7 3c.5523 0 1-.4477 1-1s-.4477-1-1-1-1 .4477-1 1 .4477 1 1 1m4-1c0 .5523-.4477 1-1 1s-1-.4477-1-1 .4477-1 1-1 1 .4477 1 1m-7 1c.55228 0 1-.4477 1-1s-.44772-1-1-1-1 .4477-1 1 .44772 1 1 1"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
