// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconSidebarClosed24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M10 7h8c.5523 0 1 .44772 1 1v8c0 .5523-.4477 1-1 1h-8zM9 7H6c-.55228 0-1 .44772-1 1v8c0 .5523.44772 1 1 1h3zM4 8c0-1.10457.89543-2 2-2h12c1.1046 0 2 .89543 2 2v8c0 1.1046-.8954 2-2 2H6c-1.10457 0-2-.8954-2-2z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
