// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconBlendModeActiveSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="M16 12.9996c0 2.2092-1.7909 4-4 4-2.20914 0-4-1.7908-4-4 0-2.1703 2.0934-5.38731 3.2514-7.00073.3736-.52063 1.1236-.52063 1.4972 0C13.9066 7.61229 16 10.8293 16 12.9996"
      fill="currentColor"
      fillOpacity="0.3"
    />
    <path
      clip-rule="evenodd"
      d="M12 15.9996c1.6569 0 3-1.3431 3-3 0-.8264-.42-1.9887-1.0776-3.24567C13.3085 8.58027 12.5596 7.45646 12 6.67116c-.5596.7853-1.3085 1.90911-1.9224 3.08277C9.42004 11.0109 9 12.1732 9 12.9996c0 1.6569 1.3431 3 3 3m0 1c2.2091 0 4-1.7908 4-4 0-2.1703-2.0934-5.38731-3.2514-7.00073-.3736-.52063-1.1236-.52063-1.4972 0C10.0934 7.61229 8 10.8293 8 12.9996c0 2.2092 1.79086 4 4 4"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
