// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconFigma24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M6.5 7c0 1.04349.53275 1.96254 1.3411 2.5C7.03275 10.0375 6.5 10.9565 6.5 12s.53276 1.9625 1.34111 2.5C7.03276 15.0375 6.5 15.9565 6.5 17c0 1.6569 1.34315 3 3 3 1.6569 0 3-1.3431 3-3v-2.7639c.5308.475 1.2316.7639 2 .7639 1.6569 0 3-1.3431 3-3 0-1.0435-.5328-1.9625-1.3411-2.5C16.9672 8.96254 17.5 8.04349 17.5 7c0-1.65685-1.3431-3-3-3h-5c-1.65685 0-3 1.34315-3 3m8 2c1.1046 0 2-.89543 2-2s-.8954-2-2-2h-2v4zm-2 3c0 1.1046.8954 2 2 2s2-.8954 2-2-.8954-2-2-2-2 .8954-2 2m-1 2h-2c-1.10457 0-2-.8954-2-2s.89543-2 2-2h2v4m-2 1h2v2c0 1.1046-.8954 2-2 2-1.10457 0-2-.8954-2-2s.89543-2 2-2m2-6h-2c-1.10457 0-2-.89543-2-2s.89543-2 2-2h2z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
