// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconTextParagraphSpacing24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5 6.5c0-.27614.22386-.5.5-.5h12c.2761 0 .5.22386.5.5s-.2239.5-.5.5h-12c-.27614 0-.5-.22386-.5-.5m6.1464 1.64645c.1953-.19527.5119-.19527.7072 0l2 1.99995c.1952.1953.1952.5119 0 .7072-.1953.1952-.5119.1952-.7072 0L12 9.70711v4.58579l1.1464-1.1465c.1953-.1952.5119-.1952.7072 0 .1952.1953.1952.5119 0 .7072l-2 2c-.1953.1952-.5119.1952-.7072 0l-1.99995-2c-.19527-.1953-.19527-.5119 0-.7072.19526-.1952.51184-.1952.7071 0L11 14.2929V9.70711L9.85355 10.8536c-.19526.1952-.51184.1952-.7071 0-.19527-.1953-.19527-.5119 0-.7072zM5 17.5c0-.2761.22386-.5.5-.5h12c.2761 0 .5.2239.5.5s-.2239.5-.5.5h-12c-.27614 0-.5-.2239-.5-.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
