// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconFolder24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7 7h3.882l.5 1H7zM6 8V7c0-.55229.44771-1 1-1h3.882c.3787 0 .725.214.8944.55278L12.5 8h4c.8284 0 1.5.67157 1.5 1.5v6c0 .8284-.6716 1.5-1.5 1.5h-9c-.82843 0-1.5-.6716-1.5-1.5V8m7 1H7v6.5c0 .2761.22386.5.5.5h9c.2761 0 .5-.2239.5-.5v-6c0-.27614-.2239-.5-.5-.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
