// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconCloseFilled24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M12 4.1001c-4.36307 0-7.90002 3.53695-7.90002 7.9 0 4.363 3.53695 7.9 7.90002 7.9 4.363 0 7.9-3.537 7.9-7.9 0-4.36305-3.537-7.9-7.9-7.9m2.8535 5.75345c.1953-.19526.1953-.51184 0-.7071-.1952-.19526-.5118-.19526-.707 0L12 11.2929 9.85355 9.1465c-.19526-.19527-.51184-.19527-.70711 0-.19525.19527-.19525.51186.00001.70711L11.2929 12l-2.14645 2.1465c-.19526.1952-.19526.5118 0 .707.19526.1953.51184.1953.7071 0L12 12.7071l2.1465 2.1465c.1952.1952.5118.1952.7071-.0001.1952-.1952.1952-.5118-.0001-.7071L12.7071 12z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
