// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconSlideSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M17 7H7c-.55228 0-1 .44772-1 1v6c0 .5523.44772 1 1 1h10c.5523 0 1-.4477 1-1V8c0-.55228-.4477-1-1-1M7 6c-1.10457 0-2 .89543-2 2v6c0 1.1046.89543 2 2 2h1.28877l-.7217 1.25c-.13807.2392-.05613.545.18301.683.23915.1381.54494.0562.68302-.183L9.44347 16h5.11323l1.0104 1.75c.138.2392.4438.3211.683.183.2391-.138.3211-.4438.183-.683L15.7114 16H17c1.1046 0 2-.8954 2-2V8c0-1.10457-.8954-2-2-2zm4.5145 2.7756C10.848 8.37569 10 8.8558 10 9.6331v2.7338c0 .7773.848 1.2574 1.5145.8575l2.2782-1.3669c.6473-.3884.6473-1.3266 0-1.715zM11 9.6331 13.2782 11 11 12.3669z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
