// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconSearch24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M16 10.5c0 3.0376-2.4624 5.5-5.5 5.5C7.46243 16 5 13.5376 5 10.5 5 7.46243 7.46243 5 10.5 5c3.0376 0 5.5 2.46243 5.5 5.5m-1.2709 4.9362C13.5923 16.411 12.1149 17 10.5 17 6.91016 17 4 14.0898 4 10.5 4 6.91016 6.91016 4 10.5 4c3.5898 0 6.5 2.91016 6.5 6.5 0 1.6149-.589 3.0923-1.5638 4.2291l4.4173 4.4174c.1953.1952.1953.5118 0 .707-.1952.1953-.5118.1953-.707 0z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
