// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconTextResizeHeight24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M6.5 6c.27614 0 .5.22386.5.5v11c0 .2761-.22386.5-.5.5s-.5-.2239-.5-.5v-11c0-.27614.22386-.5.5-.5m3.00002 4.0002L14.5 10c.2762-.00001.5-.22388.5-.50002S14.7761 8.99999 14.5 9l-5.00002.00024c-.27615.00002-.49999.22389-.49998.50003s.22388.50003.50002.49993M14.5 12.5l-4.99998.0002c-.27614.0001-.50001-.2238-.50002-.4999-.00001-.2762.22383-.5.49998-.5001L14.5 11.5c.2761 0 .5.2238.5.5 0 .2761-.2238.5-.5.5m-5.5 2c0-.2761.22386-.5.5-.5h3c.2761 0 .5.2239.5.5s-.2239.5-.5.5h-3c-.27614 0-.5-.2239-.5-.5m9-8c0-.27614-.2239-.5-.5-.5s-.5.22386-.5.5v11c0 .2761.2239.5.5.5s.5-.2239.5-.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
