// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconConvertToRasterSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M11 5.5c0-.27614.2239-.5.5-.5s.5.22386.5.5v12c0 .2761-.2239.5-.5.5s-.5-.2239-.5-.5zm-1 11.68c0 .3299-.30873.574-.62066.4664C6.83076 16.7672 5 14.3475 5 11.5002c0-2.84733 1.83075-5.26704 4.37934-6.14623.31193-.1076.62066.13645.62066.46642 0 .22883-.15306.42751-.36829.50523C7.5138 7.09044 6 9.11852 6 11.5002c0 2.3816 1.5138 4.4097 3.63171 5.1745.21523.0777.36829.2764.36829.5053M13 6.5c0-.27614.2239-.5.5-.5h2c.2761 0 .5.22386.5.5V8h1.5c.2761 0 .5.22386.5.5v6c0 .2761-.2239.5-.5.5H16v1.5c0 .2761-.2239.5-.5.5h-2c-.2761 0-.5-.2239-.5-.5s.2239-.5.5-.5H15v-1.5c0-.2761.2239-.5.5-.5H17V9h-1.5c-.2761 0-.5-.22386-.5-.5V7h-1.5c-.2761 0-.5-.22386-.5-.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
