// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconVectorBendSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M16 9c.5523 0 1-.44772 1-1s-.4477-1-1-1-1 .44772-1 1 .4477 1 1 1m0 1c1.1046 0 2-.89543 2-2s-.8954-2-2-2c-.9319 0-1.715.63739-1.937 1.5H14c-3.5899 0-6.5 2.9101-6.5 6.5v.063C6.63739 14.285 6 15.0681 6 16c0 1.1046.89543 2 2 2s2-.8954 2-2c0-.9319-.63739-1.715-1.5-1.937V14c0-3.0376 2.4624-5.5 5.5-5.5h.063c.222.86261 1.0051 1.5 1.937 1.5m-8 7c.55228 0 1-.4477 1-1s-.44772-1-1-1-1 .4477-1 1 .44772 1 1 1"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
