// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconForwardSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M8.70711 7.29292c-.286-.286-.71612-.37155-1.08979-.21677S7 7.59557 7 8.00003V16c0 .4045.24364.7691.61732.9239.37367.1548.80379.0692 1.08979-.2168L12 13.4142v2.5859c0 .4044.2436.7691.6173.9239.3737.1547.8038.0692 1.0898-.2168l4-4c.3905-.3905.3905-1.0237 0-1.4142l-4-4.00002c-.286-.286-.7161-.37155-1.0898-.21677S12 7.59562 12 8.00009v2.58571zM12 12l-.7071-.7071L9 9.00003l-1-1V16l1-1 2.2929-2.2929zm2 3.0001-1 1V8.00009l1 1 2.2929 2.29291.7071.7071-.7071.7071z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
