// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconResolveFilled24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M12 19.9001c4.363 0 7.9-3.537 7.9-7.9 0-4.36305-3.537-7.9-7.9-7.9-4.36307 0-7.90002 3.53695-7.90002 7.9 0 4.363 3.53695 7.9 7.90002 7.9m3.4319-10.64804c.1391-.23853.0585-.54469-.18-.68383s-.5447-.05857-.6838.17996l-3.1406 5.38391L9.38408 11.68c-.17678-.2121-.49206-.2408-.7042-.064s-.2408.4921-.06402.7042l2.50004 3a.4996.4996 0 0 0 .4257.1782.5002.5002 0 0 0 .3903-.2463z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
