// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconGridView24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7 7h3v3H7zM6 7c0-.55229.44771-1 1-1h3c.5523 0 1 .44771 1 1v3c0 .5523-.4477 1-1 1H7c-.55229 0-1-.4477-1-1zm1 7h3v3H7zm-1 0c0-.5523.44771-1 1-1h3c.5523 0 1 .4477 1 1v3c0 .5523-.4477 1-1 1H7c-.55229 0-1-.4477-1-1zm11-7h-3v3h3zm-3-1c-.5523 0-1 .44771-1 1v3c0 .5523.4477 1 1 1h3c.5523 0 1-.4477 1-1V7c0-.55229-.4477-1-1-1zm0 8h3v3h-3zm-1 0c0-.5523.4477-1 1-1h3c.5523 0 1 .4477 1 1v3c0 .5523-.4477 1-1 1h-3c-.5523 0-1-.4477-1-1z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
