// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconTextFontSize24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5.75684 16h1.01562l.80427-2.2656h3.23517L11.6162 16h1.0156L9.69434 8h-1zm4.75006-3.125L9.22559 9.26562h-.0625L7.8818 12.875zm3.1238 3.1251h.9844l.421-1.2553H16.95l.4218 1.2553h.9844l-1.7947-5.0909H15.423zm3.0705-1.9961-.6891-2.0508h-.0398l-.6878 2.0508z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
