// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconTemplate24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M6 6h12c.5523 0 1 .44771 1 1v3H5V7c0-.55229.44771-1 1-1m-1 5v6c0 .5523.44771 1 1 1h3v-7zm5 7h8c.5523 0 1-.4477 1-1v-6h-9zM4 7c0-1.10457.89543-2 2-2h12c1.1046 0 2 .89543 2 2v10c0 1.1046-.8954 2-2 2H6c-1.10457 0-2-.8954-2-2z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
