// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAnimate24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7.5 7c-.27614 0-.5.22386-.5.5s.22386.5.5.5h4c.2761 0 .5-.22386.5-.5s-.2239-.5-.5-.5zm-4 3c-.27614 0-.5.2239-.5.5s.22386.5.5.5h6c.27614 0 .5-.2239.5-.5s-.22386-.5-.5-.5zm0 3c-.27614 0-.5.2239-.5.5s.22386.5.5.5h6c.27614 0 .5-.2239.5-.5s-.22386-.5-.5-.5zm4 3c-.27614 0-.5.2239-.5.5s.22386.5.5.5h4c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5zM20 12c0 2.2091-1.7909 4-4 4s-4-1.7909-4-4c0-2.20914 1.7909-4 4-4s4 1.79086 4 4m1 0c0 2.7614-2.2386 5-5 5s-5-2.2386-5-5c0-2.76143 2.2386-5 5-5s5 2.23857 5 5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
