// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconTextSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M6 6.5c0-.27614.22386-.5.5-.5h11c.2761 0 .5.22386.5.5V9c0 .27614-.2239.5-.5.5S17 9.27614 17 9V7h-4.5v10h2c.2761 0 .5.2239.5.5s-.2239.5-.5.5h-5c-.27614 0-.5-.2239-.5-.5s.22386-.5.5-.5h2V7H7v2c0 .27614-.22386.5-.5.5S6 9.27614 6 9z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
