// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconSlidesSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7 7h10c.5523 0 1 .44772 1 1v6c0 .5523-.4477 1-1 1H7c-.55228 0-1-.4477-1-1V8c0-.55228.44772-1 1-1m1.68078 9H7c-1.10457 0-2-.8954-2-2V8c0-1.10457.89543-2 2-2h10c1.1046 0 2 .89543 2 2v6c0 1.1046-.8954 2-2 2h-1.6808l.6623 2.3652c.0744.2659-.0808.5418-.3467.6163-.2659.0744-.5418-.0808-.6163-.3467L14.2808 16H9.71924l-.73775 2.6348c-.07446.2659-.35038.4211-.6163.3467-.26591-.0745-.42112-.3504-.34667-.6163zM8.5 8.5c-.55228 0-1 .44772-1 1 0 .5523.44772 1 1 1s1-.4477 1-1c0-.55228-.44772-1-1-1m0 3c-.55228 0-1 .4477-1 1s.44772 1 1 1 1-.4477 1-1-.44772-1-1-1"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
