// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutWidthHug24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7.14644 8.14645c.19527-.19526.51185-.19527.70711-.00001l3.00005 2.99996c.0937.0938.1464.221.1464.3536s-.0527.2598-.1464.3535l-3.00005 3c-.19526.1953-.51184.1953-.7071 0-.19527-.1952-.19527-.5118 0-.7071L9.79289 11.5 7.14645 8.85356c-.19526-.19527-.19527-.51185-.00001-.70711m9.70716 0c.1952.19526.1952.51184 0 .70711L14.2071 11.5l2.6465 2.6464c.1952.1953.1952.5119 0 .7071-.1953.1953-.5119.1953-.7072 0l-3-3A.5.5 0 0 1 13 11.5c0-.1326.0527-.2598.1464-.3536l3-2.99996c.1953-.19526.5119-.19525.7072.00001"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
