// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconSave24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="m12 16.0858.7071.7071L16 20.0858V5c0-.55228-.4477-1-1-1H9c-.55228 0-1 .44772-1 1v15.0858l3.2929-3.2929zm.7071 2.1213 2.5858 2.5858c.63.63 1.7071.1838 1.7071-.7071V5c0-1.10457-.8954-2-2-2H9c-1.10457 0-2 .89543-2 2v15.0858c0 .8909 1.07714 1.3371 1.70711.7071l2.58579-2.5858L12 17.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
