// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconGridColumn24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7.5 6c.27614 0 .5.22386.5.5V7h3.5v-.5c0-.27614.2239-.5.5-.5s.5.22386.5.5V7H16v-.5c0-.27614.2239-.5.5-.5s.5.22386.5.5V7h.5c.2761 0 .5.22386.5.5s-.2239.5-.5.5H17v8h.5c.2761 0 .5.2239.5.5s-.2239.5-.5.5H17v.5c0 .2761-.2239.5-.5.5s-.5-.2239-.5-.5V17h-3.5v.5c0 .2761-.2239.5-.5.5s-.5-.2239-.5-.5V17H8v.5c0 .2761-.22386.5-.5.5s-.5-.2239-.5-.5V17h-.5c-.27614 0-.5-.2239-.5-.5s.22386-.5.5-.5H7V8h-.5c-.27614 0-.5-.22386-.5-.5s.22386-.5.5-.5H7v-.5c0-.27614.22386-.5.5-.5M8 16h3.5V8H8zm4.5 0H16V8h-3.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
