// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconCameraSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7.5 8h6c.8284 0 1.5.67157 1.5 1.5v5c0 .8284-.6716 1.5-1.5 1.5h-6c-.82843 0-1.5-.6716-1.5-1.5v-5C6 8.67157 6.67157 8 7.5 8m8.5 5.9142V14.5c0 1.3807-1.1193 2.5-2.5 2.5h-6C6.11929 17 5 15.8807 5 14.5v-5C5 8.11929 6.11929 7 7.5 7h6C14.8807 7 16 8.11929 16 9.5v.5858l1.2929-1.29291c.286-.28599.7161-.37155 1.0898-.21676.3737.15477.6173.51941.6173.92387v5c0 .4045-.2436.7691-.6173.9239s-.8038.0692-1.0898-.2168zM16 12.5l1 1 1 1v-5l-1 1-1 1z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
