// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconFlatten24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M12.5 3.5c0-.27614-.2239-.5-.5-.5s-.5.22386-.5.5v6.7929L8.85355 7.64645c-.19526-.19527-.51184-.19527-.7071 0-.19527.19526-.19527.51184 0 .7071l3.49995 3.50005c.1953.1952.5119.1952.7072 0l3.5-3.50005c.1952-.19526.1952-.51184 0-.7071-.1953-.19527-.5119-.19527-.7072 0L12.5 10.2929zM4 15.5c0-.2761.22386-.5.5-.5h15c.2761 0 .5.2239.5.5s-.2239.5-.5.5h-15c-.27614 0-.5-.2239-.5-.5m1 3c0-.2761.22386-.5.5-.5h13c.2761 0 .5.2239.5.5s-.2239.5-.5.5h-13c-.27614 0-.5-.2239-.5-.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
