// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconSoundOnSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="m10 15 2 2 1 1V6.00003l-1 1-2 2H6.5c-.27614 0-.5.22386-.5.5V14.5c0 .2762.22386.5.5.5zm2.2929-9.70708L9.58579 8.00003H6.5c-.82843 0-1.5.67157-1.5 1.5V14.5c0 .8285.67157 1.5 1.5 1.5h3.08579l2.70711 2.7071c.286.286.7161.3716 1.0898.2168S14 18.4045 14 18V6.00003c0-.40446-.2436-.7691-.6173-.92388s-.8038-.06923-1.0898.21677M19 12.0001c0 2.2388-1.4714 4.134-3.5 4.7711v-1.0618c1.4659-.5934 2.5-2.0306 2.5-3.7093s-1.0341-3.11583-2.5-3.70922V7.22902c2.0286.63713 3.5 2.53228 3.5 4.77108m-2 0c0 1.1104-.6033 2.08-1.5 2.5987V13.323c.3112-.3525.5-.8157.5-1.3229s-.1888-.9703-.5-1.3229V9.40146c.8967.51872 1.5 1.48824 1.5 2.59864"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
