// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconVectorBend24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M17.5 8c.8284 0 1.5-.67157 1.5-1.5S18.3284 5 17.5 5 16 5.67157 16 6.5 16.6716 8 17.5 8m0 1C18.8807 9 20 7.88071 20 6.5S18.8807 4 17.5 4c-1.2095 0-2.2184.85888-2.45 2H14c-4.41828 0-8 3.58172-8 8v1.05c-1.14112.2316-2 1.2405-2 2.45C4 18.8807 5.11929 20 6.5 20S9 18.8807 9 17.5c0-1.2095-.85888-2.2184-2-2.45V14c0-3.866 3.134-7 7-7h1.05c.2316 1.14112 1.2405 2 2.45 2m-11 10c.82843 0 1.5-.6716 1.5-1.5S7.32843 16 6.5 16 5 16.6716 5 17.5 5.67157 19 6.5 19"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
