// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconInspectSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7 8c0-.55229.44771-1 1-1h7c.5523 0 1 .44771 1 1v3c0 .2761.2239.5.5.5s.5-.2239.5-.5V8c0-1.10457-.8954-2-2-2H8c-1.10457 0-2 .89543-2 2v7c0 1.1046.89543 2 2 2h3c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5H8c-.55229 0-1-.4477-1-1zm11.2941 7.3129c.4062-.125.6891-.4931.7052-.9178.0161-.4248-.238-.8133-.6337-.9687l-6-2.3572c-.3702-.1454-.7914-.0576-1.0727.2237s-.3691.7025-.2237 1.0727l2.3572 6c.1554.3957.5439.6498.9687.6337.4247-.0161.7928-.299.9178-.7052l.7015-2.2797zm-1.8278-.4839-1.252.3853-.3853 1.252L14.3571 18l-.5867-1.4935-1.2713-3.236L12 12l1.2705.4991 3.236 1.2713L18 14.3571z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
