// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconPersonSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M15.0001 9c0 1.6569-1.3432 3-3 3-1.6569 0-3.00001-1.3431-3.00001-3 0-1.65685 1.34311-3 3.00001-3 1.6568 0 3 1.34315 3 3m1 0c0 2.2091-1.7909 4-4 4-2.20914 0-4.00001-1.7909-4.00001-4 0-2.20914 1.79087-4 4.00001-4 2.2091 0 4 1.79086 4 4m-9.74913 8.0057c-.13251.1904-.10951.4469.05338.612.23242.2356.61849.167.81092-.1023C8.20345 15.9926 9.98594 15 12.0003 15c2.0142 0 3.7966.9925 4.8848 2.5152.1925.2693.5786.3379.811.1023.1628-.1652.1858-.4217.0533-.612C16.4849 15.1889 14.3814 14 12.0003 14c-2.38127 0-4.48482 1.189-5.74933 3.0057"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
