// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconBooleanIntersectSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M14 10v4h-4v-4z"
      fill="currentColor"
      fill-rule="evenodd"
      fillOpacity="0.3"
    />
    <path
      clip-rule="evenodd"
      d="M10.5 15H10v2h7v-7h-2v4c0 .5523-.4477 1-1 1zm0-1H10v-4h4v4zM9 14H7V7h7v2h-4c-.55229 0-1 .44771-1 1v4m-1 1H7c-.55229 0-1-.4477-1-1V7c0-.55229.44771-1 1-1h7c.5523 0 1 .44771 1 1v2h2c.5523 0 1 .44771 1 1v7c0 .5523-.4477 1-1 1h-7c-.55229 0-1-.4477-1-1v-2z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
