// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconDuplicateSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7.5 7h6c.2761 0 .5.22386.5.5V9h-3.5C9.67157 9 9 9.67157 9 10.5V14H7.5c-.27614 0-.5-.2239-.5-.5v-6c0-.27614.22386-.5.5-.5m9 2H15V7.5c0-.82843-.6716-1.5-1.5-1.5h-6C6.67157 6 6 6.67157 6 7.5v6c0 .8284.67157 1.5 1.5 1.5H9v1.5c0 .8284.67157 1.5 1.5 1.5h6c.8284 0 1.5-.6716 1.5-1.5v-6c0-.82843-.6716-1.5-1.5-1.5m-6 1c-.2761 0-.5.2239-.5.5v6c0 .2761.2239.5.5.5h6c.2761 0 .5-.2239.5-.5v-6c0-.2761-.2239-.5-.5-.5zm3.5 2c0-.2761-.2239-.5-.5-.5s-.5.2239-.5.5v1h-1c-.2761 0-.5.2239-.5.5s.2239.5.5.5h1v1c0 .2761.2239.5.5.5s.5-.2239.5-.5v-1h1c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5h-1z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
