// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconSectionSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M13 7h3c.5523 0 1 .44771 1 1v8c0 .5523-.4477 1-1 1H8c-.55229 0-1-.4477-1-1v-6h5.25c.4142 0 .75-.33578.75-.75zm-1 0H8c-.55229 0-1 .44771-1 1v1h5zm.25-1H16c1.1046 0 2 .89543 2 2v8c0 1.1046-.8954 2-2 2H8c-1.10457 0-2-.8954-2-2V8c0-1.10457.89543-2 2-2z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
