// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconVariableSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="m12.5039 6.45165 4 2.33333A1 1 0 0 1 17 9.64876v4.70254c0 .3556-.1889.6846-.4961.8638l-4 2.3333a1.0002 1.0002 0 0 1-1.0078 0l-3.99997-2.3333C7.18891 15.0358 7 14.7069 7 14.3513V9.64876a1 1 0 0 1 .49613-.86378l3.99997-2.33333a1.0001 1.0001 0 0 1 1.0078 0m-1.5116-.86378c.6227-.36325 1.3927-.36325 2.0155 0l3.9999 2.33333c.6145.35843.9923 1.01623.9923 1.72756v4.70254c0 .7113-.3778 1.3691-.9923 1.7275l-3.9999 2.3334c-.6228.3632-1.3928.3632-2.0155 0l-4.00004-2.3334C6.37782 15.7204 6 15.0626 6 14.3513V9.64876c0-.71133.37782-1.36913.99226-1.72755zM12 11c-.5523 0-1 .4477-1 1s.4477 1 1 1 1-.4477 1-1-.4477-1-1-1"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
