// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconFigjamPages24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M18 18c1.1046 0 2-.8954 2-2V6c0-1.10457-.8954-2-2-2H8.00001c-1.10457 0-2 .89543-2 2h1c0-.55228.44771-1 1-1H18c.5523 0 1 .44772 1 1v10c0 .5523-.4477 1-1 1V8.00012c0-1.10457-.8954-2-2-2H6c-1.10457 0-2 .89543-2 2v9.99998c0 1.1046.89543 2 2 2h10c1.1046 0 2-.8954 2-2zm-2 1.0001H6c-.55228 0-1-.4477-1-1V8.00012c0-.55228.44772-1 1-1h10c.5523 0 1 .44772 1 1v9.99998c0 .5523-.4477 1-1 1"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
