// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconFigjamPagesMore24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M20 16c0 1.1046-.8954 2-2 2v.0001c0 1.1046-.8954 2-2 2H6c-1.10457 0-2-.8954-2-2V8.00012c0-1.10457.89543-2 2-2h10c1.1046 0 2 .89543 2 2V17c.5523 0 1-.4477 1-1V6c0-.55228-.4477-1-1-1H8.00001c-.55229 0-1 .44772-1 1h-1c0-1.10457.89543-2 2-2H18c1.1046 0 2 .89543 2 2v10M5 18.0001c0 .5523.44772 1 1 1h10c.5523 0 1-.4477 1-1V8.00012c0-.55228-.4477-1-1-1H6c-.55228 0-1 .44772-1 1zm3-4.0002c.55228 0 1-.4477 1-1 0-.5522-.44772-1-1-1s-1 .4478-1 1c0 .5523.44772 1 1 1m3 0c.5523 0 1-.4477 1-1 0-.5522-.4477-1-1-1s-1 .4478-1 1c0 .5523.4477 1 1 1m4-1c0 .5523-.4477 1-1 1s-1-.4477-1-1c0-.5522.4477-1 1-1s1 .4478 1 1"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
