// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconGoToMainComponentSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M13.4999 6c-.2761 0-.5.22386-.5.5s.2239.5.5.5h2.7929l-4.6464 4.6464c-.1953.1953-.1953.5119 0 .7072.1952.1952.5118.1952.7071 0l4.6464-4.64649V10.5c0 .2761.2239.5.5.5.2762 0 .5-.2239.5-.5V7c0-.55228-.4477-1-1-1zm-2.6464 1.14645c.1952.19526.1952.51184 0 .7071L6.70703 12l5.29287 5.2929 4.1465-4.1465c.1952-.1952.5118-.1952.7071 0 .1952.1953.1952.5119 0 .7072L12.707 18c-.3905.3905-1.0237.3905-1.4142 0l-5.29288-5.2929c-.39052-.3905-.39052-1.0237 0-1.4142l4.14648-4.14645c.1952-.19527.5118-.19527.7071 0"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
