// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconGradientLinearSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M8 7h3.5v10H8c-.55228 0-1-.4477-1-1V8c0-.55228.44772-1 1-1"
      fill="currentColor"
      fill-rule="evenodd"
      fillOpacity="0.3"
    />
    <path
      clip-rule="evenodd"
      d="M12.5 7H16c.5523 0 1 .44772 1 1v8c0 .5523-.4477 1-1 1h-3.5zm-1 0H8c-.55228 0-1 .44772-1 1v8c0 .5523.44772 1 1 1h3.5zM6 8c0-1.10457.89543-2 2-2h8c1.1046 0 2 .89543 2 2v8c0 1.1046-.8954 2-2 2H8c-1.10457 0-2-.8954-2-2z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
