// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutAbsolutePosition24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M6 7c0-.55229.44771-1 1-1h2.5c.27614 0 .5.22386.5.5s-.22386.5-.5.5H7v2.5c0 .27614-.22386.5-.5.5S6 9.77614 6 9.5zm12 0c0-.55229-.4477-1-1-1h-2.5c-.2761 0-.5.22386-.5.5s.2239.5.5.5H17v2.5c0 .27614.2239.5.5.5s.5-.22386.5-.5zM7 18c-.55229 0-1-.4477-1-1v-2.5c0-.2761.22386-.5.5-.5s.5.2239.5.5V17h2.5c.27614 0 .5.2239.5.5s-.22386.5-.5.5zm11-1c0 .5523-.4477 1-1 1h-2.5c-.2761 0-.5-.2239-.5-.5s.2239-.5.5-.5H17v-2.5c0-.2761.2239-.5.5-.5s.5.2239.5.5zm-8.00006-7h3.99996v4H9.99994zm-1 0c0-.55228.44771-1 1-1h3.99996c.5523 0 1 .44772 1 1v4c0 .5523-.4477 1-1 1H9.99994c-.55229 0-1-.4477-1-1z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
