// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconFlipVertical24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M17.5 12.5c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5h-11c-.27614 0-.5.2239-.5.5s.22386.5.5.5zM14.8964 18c.6682 0 1.0028-.8079.5304-1.2803L12.7071 14c-.3905-.3905-1.0237-.3905-1.4142 0l-2.71968 2.7197C8.10075 17.1921 8.43538 18 9.10355 18zm-.6035-1H9.70711L12 14.7071zm.6035-11c.6682 0 1.0028.80786.5304 1.28033L12.7071 10c-.3905.3905-1.0237.3905-1.4142 0L8.57322 7.28033C8.10075 6.80785 8.43538 6 9.10355 6zm-.6035 1H9.70711L12 9.29289z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
