// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconLayoutAlignVerticalCenterGroup24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M18 11.5c0-.2761-.2239-.5-.5-.5H15V9.75c0-.41421-.3358-.75-.75-.75h-.5c-.4142 0-.75.33579-.75.75V11h-3V7.75c0-.41421-.33579-.75-.75-.75h-.5c-.41421 0-.75.33579-.75.75V11H5.5c-.27614 0-.5.2239-.5.5s.22386.5.5.5H8v3.25c0 .4142.33579.75.75.75h.5c.41421 0 .75-.3358.75-.75V12h3v1.25c0 .4142.3358.75.75.75h.5c.4142 0 .75-.3358.75-.75V12h2.5c.2761 0 .5-.2239.5-.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
    <path
      clip-rule="evenodd"
      d="M6.25 5C5.55964 5 5 5.55964 5 6.25V8.5c0 .27614.22386.5.5.5s.5-.22386.5-.5V6.25c0-.13807.11193-.25.25-.25h10.5c.1381 0 .25.11193.25.25V8.5c0 .27614.2239.5.5.5s.5-.22386.5-.5V6.25C18 5.55964 17.4404 5 16.75 5zm10.5 13c.6904 0 1.25-.5596 1.25-1.25V14.5c0-.2761-.2239-.5-.5-.5s-.5.2239-.5.5v2.25c0 .1381-.1119.25-.25.25H6.25c-.13807 0-.25-.1119-.25-.25V14.5c0-.2761-.22386-.5-.5-.5s-.5.2239-.5.5v2.25c0 .6904.55964 1.25 1.25 1.25z"
      fill="currentColor"
      fill-rule="evenodd"
      fillOpacity="0.3"
    />
  </svg>
)
