// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconSlides24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5 6h14c.5523 0 1 .44772 1 1v8c0 .5523-.4477 1-1 1H5c-.55228 0-1-.4477-1-1V7c0-.55228.44772-1 1-1M3 7c0-1.10457.89543-2 2-2h14c1.1046 0 2 .89543 2 2v8c0 1.1046-.8954 2-2 2h-1.9823l.9451 2.3107c.1045.2556-.0179.5475-.2735.6521-.2556.1045-.5475-.0179-.6521-.2735L15.9373 17H8.06281L6.9628 19.6895c-.10454.2556-.39648.3781-.65207.2735-.25559-.1045-.37805-.3964-.27351-.652L6.9824 17H5c-1.10457 0-2-.8954-2-2zm3 2c0-.55228.44772-1 1-1s1 .44772 1 1-.44772 1-1 1-1-.44772-1-1m1 3c-.55228 0-1 .4477-1 1s.44772 1 1 1 1-.4477 1-1-.44772-1-1-1"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
