// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconText24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M4 4.5c0-.27614.22386-.5.5-.5h15c.2761 0 .5.22386.5.5v3c0 .27614-.2239.5-.5.5s-.5-.22386-.5-.5V5h-6.5v14H15c.2761 0 .5.2239.5.5s-.2239.5-.5.5H9c-.27614 0-.5-.2239-.5-.5s.22386-.5.5-.5h2.5V5H5v2.5c0 .27614-.22386.5-.5.5S4 7.77614 4 7.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
