// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconFirstDraftSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M16.5 6c.8284 0 1.5.67157 1.5 1.5v6c0 .2761-.2239.5-.5.5s-.5-.2239-.5-.5V10h-6v7h2.5c.2761 0 .5.2239.5.5s-.2239.5-.5.5h-6c-.82843 0-1.5-.6716-1.5-1.5v-9C6 6.67157 6.67157 6 7.5 6zM10 17v-7H7v6.5c0 .2761.22386.5.5.5zM7 9h10V7.5c0-.27614-.2239-.5-.5-.5h-9c-.27614 0-.5.22386-.5.5zm9.7 7.7.3149-1.2597c.1263-.505.8439-.505.9702 0L18.3 16.7l1.2597.3149c.505.1263.505.8439 0 .9702L18.3 18.3l-.3149 1.2597c-.1263.505-.8439.505-.9702 0L16.7 18.3l-1.2597-.3149c-.505-.1263-.505-.8439 0-.9702z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
