// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconPencil24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M3.00773 4.12392a.99998.99998 0 0 1 1.11631-1.11631l4 .5a1 1 0 0 1 .58307.28517L20.5 15.5857c.7811.781.7811 2.0473 0 2.8284l-2.0858 2.0858c-.781.781-2.0474.781-2.8284 0L3.7929 8.70699a1 1 0 0 1-.28517-.58307zm.99228-.12403.12797 1.02377.37203 2.97623 9.14649 9.14641 3.5-3.5-9.14649-9.14641-2.97622-.37203zM17.8536 14.3534l-3.5 3.5 1.9393 1.9394c.3905.3905 1.0237.3905 1.4142 0l2.0858-2.0858c.3905-.3905.3905-1.0237 0-1.4142z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
