// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconProportionalUppercaseNumber24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="M9.13986 8.21826c.4439 0 .80375.35985.80375.80375V15.47c0 .2928-.23732.5301-.53006.5301-.29275 0-.53006-.2373-.53006-.5301V9.33626a.03509.03509 0 0 0-.05438-.0293l-1.1981.78904c-.28911.1904-.67398-.0169-.67398-.36313a.4348.4348 0 0 1 .19543-.36299l1.5449-1.01884a.8037.8037 0 0 1 .4425-.13278"
      fill="currentColor"
    />
    <path
      d="M13.3125 16.0001c-.3674 0-.6057-.3875-.4399-.7155l3.0717-6.07557a.049.049 0 0 0 .0053-.02215.0491.0491 0 0 0-.0491-.04909h-3.4619c-.2539 0-.4597-.20584-.4597-.45976s.2058-.45977.4597-.45977h3.8282c.4292 0 .7771.34791.7771.77707a.777.777 0 0 1-.0827.3489L13.753 15.7284c-.0836.1666-.2541.2717-.4405.2717"
      fill="currentColor"
    />
  </svg>
)
