// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconPage24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M17 18c0 .5523-.4477 1-1 1H8c-.55229 0-1-.4477-1-1V6c0-.55229.44771-1 1-1h4v3.5c0 .82843.6716 1.5 1.5 1.5H17zm-.4142-9L13 5.41422V8.5c0 .27614.2239.5.5.5zM8 20h8c1.1046 0 2-.8954 2-2V9.41422c0-.26522-.1054-.51958-.2929-.70711l-4.4142-4.41422A1 1 0 0 0 12.5858 4H8c-1.10457 0-2 .89543-2 2v12c0 1.1046.89543 2 2 2"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
