// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconListView24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M6 7c0-.55228.44772-1 1-1s1 .44772 1 1-.44772 1-1 1-1-.44772-1-1m4.5-.5c-.2761 0-.5.22386-.5.5s.2239.5.5.5h7c.2761 0 .5-.22386.5-.5s-.2239-.5-.5-.5zm0 10c-.2761 0-.5.2239-.5.5s.2239.5.5.5h7c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5zm0-5c-.2761 0-.5.2239-.5.5s.2239.5.5.5h7c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5zM6 12c0-.5523.44772-1 1-1s1 .4477 1 1-.44772 1-1 1-1-.4477-1-1m1 4c-.55228 0-1 .4477-1 1s.44772 1 1 1 1-.4477 1-1-.44772-1-1-1"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
