// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconSendForwardSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7.5 7c-.27614 0-.5.22386-.5.5s.22386.5.5.5h8c.2761 0 .5-.22386.5-.5s-.2239-.5-.5-.5zM6 7.5C6 6.67157 6.67157 6 7.5 6h8c.8284 0 1.5.67157 1.5 1.5S16.3284 9 15.5 9h-8C6.67157 9 6 8.32843 6 7.5m5.1465 2.6465c.1952-.19531.5118-.19531.707 0l2 2c.1953.1952.1953.5118 0 .707-.1952.1953-.5118.1953-.707 0L12 11.7071V15h3.5c.8284 0 1.5.6716 1.5 1.5s-.6716 1.5-1.5 1.5h-8c-.82843 0-1.5-.6716-1.5-1.5S6.67157 15 7.5 15H11v-3.2929l-1.14645 1.1464c-.19526.1953-.51184.1953-.7071 0-.19526-.1952-.19526-.5118 0-.707zM7 16.5c0-.2761.22386-.5.5-.5h8c.2761 0 .5.2239.5.5s-.2239.5-.5.5h-8c-.27614 0-.5-.2239-.5-.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
