// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconSlice24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M19.4046 5.86162c-.4996-.49958-1.3096-.49958-1.8091 0L12 11.4571v3.8132l7.4163-7.61137c.4885-.50139.4833-1.30231-.0117-1.79731M11.9938 16.7096l8.1387-8.35281c.8704-.89332.8611-2.32034-.0208-3.20228-.8901-.8901-2.3333-.8901-3.2234 0l-5.7392 5.73929-8.49732 8.2474c-.14609.1418-.19162.358-.11512.5466.07651.1887.25977.3122.46336.3122h5.5c1.86258 0 3.38538-1.455 3.49378-3.2904M11 12.432 4.23307 19h4.26695C9.88073 19 11 17.8807 11 16.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
