// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconDropShadowSpreadSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M17 6H7c-.55228 0-1 .44772-1 1v10c0 .5523.44772 1 1 1h10c.5523 0 1-.4477 1-1V7c0-.55228-.4477-1-1-1M7 5c-1.10457 0-2 .89543-2 2v10c0 1.1046.89543 2 2 2h10c1.1046 0 2-.8954 2-2V7c0-1.10457-.8954-2-2-2z"
      fill="currentColor"
      fill-rule="evenodd"
    />
    <path
      clip-rule="evenodd"
      d="M7 3C4.79086 3 3 4.79086 3 7v10c0 2.2091 1.79086 4 4 4h10c2.2091 0 4-1.7909 4-4V7c0-2.20914-1.7909-4-4-4zm0 2c-1.10457 0-2 .89543-2 2v10c0 1.1046.89543 2 2 2h10c1.1046 0 2-.8954 2-2V7c0-1.10457-.8954-2-2-2z"
      fill="currentColor"
      fill-rule="evenodd"
      fillOpacity="0.3"
    />
  </svg>
)
