// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAngle24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M9.59615 16.5966c-.19526.1953-.19526.5119 0 .7071.19527.1953.51185.1953.70715 0l4.9497-4.9497c.1953-.1953.1953-.5119 0-.7071l-4.9497-4.94976c-.1953-.19527-.51188-.19527-.70715 0-.19526.19526-.19526.51184 0 .7071l2.17455 2.1746c-1.0752 1.43036-1.0751 3.41256.0004 4.84286zm2.89165-2.8916 1.7045-1.7046-1.7049-1.7049c-.6975 1.0257-.6973 2.3839.0004 3.4095"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
