// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconProportionalLowercaseNumber24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="M12.698 17.1289c-.1658.3279.0725.7154.44.7154a.493.493 0 0 0 .4405-.2716l3.2081-6.3842a.777.777 0 0 0 .0827-.3489c0-.4292-.3479-.7771-.777-.7771h-3.8282c-.2539 0-.4598.2058-.4598.4598 0 .2539.2059.4597.4598.4597h3.4618c.0272 0 .0491.022.0491.0491 0 .0077-.0018.0153-.0052.0222z"
      fill="currentColor"
    />
    <path
      d="M9.31417 10.0625c.4439 0 .80373.3599.80373.8038v4.4479c0 .2928-.23729.5301-.53004.5301s-.53006-.2373-.53006-.5301v-4.1337a.03508.03508 0 0 0-.05437-.0293l-1.1981.7891c-.28912.1904-.67398-.017-.67398-.3632 0-.1461.07342-.2825.19543-.363l1.54489-1.0188a.804.804 0 0 1 .4425-.1328"
      fill="currentColor"
    />
  </svg>
)
