// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconBorderSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M6 7c0-.55228.44772-1 1-1h10c.5523 0 1 .44772 1 1v10c0 .5523-.4477 1-1 1H7c-.55228 0-1-.4477-1-1V7m3 2v6h6V9zM7.5 7H7v10h10V7H7.5M8 9V8h8v8H8V9"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
