// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconPolygon24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M12.0001 4.5 4.20586 18H19.7943zm.6495-.875c-.2887-.5-1.0104-.5-1.299 0l-8.22727 14.25c-.28868.5.07217 1.125.64952 1.125H20.2273c.5774 0 .9382-.625.6496-1.125z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
