// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconRadiusBottomRight24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M11.5219 16H8.5c-.27614 0-.5-.2239-.5-.5s.22386-.5.5-.5h3c.7083 0 1.2095-.0004 1.6013-.0324.3859-.0315.6215-.0912.8067-.1856.3763-.1917.6823-.4977.874-.874.0944-.1852.1541-.4208.1856-.8067.032-.3918.0324-.893.0324-1.6013v-3c0-.27614.2239-.5.5-.5s.5.22386.5.5v3.0219c0 .6815 0 1.2235-.0357 1.6608-.0366.4478-.1131.8296-.2913 1.1793a2.9994 2.9994 0 0 1-1.311 1.311c-.3497.1782-.7315.2547-1.1793.2913C12.7454 16 12.2034 16 11.5219 16"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
