// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconLockSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M8.5 12c-.27614 0-.5.2239-.5.5v4c0 .2761.22386.5.5.5h7c.2761 0 .5-.2239.5-.5v-4c0-.2761-.2239-.5-.5-.5zm1.5-1V9c0-1.10457.8954-2 2-2s2 .89543 2 2v2zm2-5c1.6569 0 3 1.34315 3 3v2h.5c.8284 0 1.5.6716 1.5 1.5v4c0 .8284-.6716 1.5-1.5 1.5h-7c-.82843 0-1.5-.6716-1.5-1.5v-4c0-.8284.67157-1.5 1.5-1.5H9V9c0-1.65685 1.3431-3 3-3"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
