// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconClipboardSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M10 6h4v1h-4zM9 6c0-.55228.44772-1 1-1h4c.5523 0 1 .44772 1 1 1.1046 0 2 .89543 2 2v8c0 1.1046-.8954 2-2 2H9c-1.10457 0-2-.8954-2-2V8c0-1.10457.89543-2 2-2m0 1c-.55228 0-1 .44772-1 1v8c0 .5523.44772 1 1 1h6c.5523 0 1-.4477 1-1V8c0-.55228-.4477-1-1-1 0 .55228-.4477 1-1 1h-4c-.55228 0-1-.44772-1-1m1 3.5c0-.2761.2239-.5.5-.5h3c.2761 0 .5.2239.5.5s-.2239.5-.5.5h-3c-.2761 0-.5-.2239-.5-.5m.5 2.5c-.2761 0-.5.2239-.5.5s.2239.5.5.5h3c.2761 0 .5-.2239.5-.5s-.2239-.5-.5-.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
