// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconCreateVariantSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="m5.88394 11.1159 5.23226-5.2322c.4881-.48816 1.2796-.48816 1.7677-.00001l5.2323 5.23221c.4881.4882.4881 1.2796 0 1.7678l-5.2323 5.2322c-.4881.4882-1.2796.4882-1.7677 0l-5.23226-5.2322c-.48816-.4882-.48816-1.2796 0-1.7678"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
