// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconDropShadowMinSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M14.5 8h-6c-.27614 0-.5.22386-.5.5v6c0 .2761.22386.5.5.5h6c.2761 0 .5-.2239.5-.5v-6c0-.27614-.2239-.5-.5-.5m-6-1C7.67157 7 7 7.67157 7 8.5v6c0 .8284.67157 1.5 1.5 1.5h6c.8284 0 1.5-.6716 1.5-1.5v-6c0-.82843-.6716-1.5-1.5-1.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
    <path
      clip-rule="evenodd"
      d="M8.06445 15.9357c.18668.6159.75885 1.0642 1.43574 1.0642h6.00001c.8284 0 1.5-.6715 1.5-1.5V9.49994c0-.67688-.4484-1.24905-1.0643-1.43573.0418.13789.0643.28419.0643.43573v5.99996c0 .8285-.6716 1.5-1.5 1.5H8.50019c-.15155 0-.29784-.0224-.43574-.0642"
      fill="currentColor"
      fill-rule="evenodd"
      fillOpacity="0.3"
    />
  </svg>
)
