// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconStrokeReversedTriangle24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M6.53 8.15249c-.30827-.19267-.69681-.20287-1.01477-.02664C5.19728 8.30207 5 8.63696 5 9.00049v5.00001c0 .3635.19728.6984.51523.8746A.9998.9998 0 0 0 6.53 14.8485l4-2.5.5568-.348H18.5c.2761 0 .5-.2239.5-.5 0-.2762-.2239-.5-.5-.5h-7.4132l-.5568-.348zM6 10.1797V9.00049l1 .625 2.0566 1.28541.9434.5896-.9434.5896L7 13.3755l-1 .625v-3.8208"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
