// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconStrokeCapRound24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5 7.5c0-.27614.22386-.5.5-.5H14c2.7614 0 5 2.23858 5 5 0 2.7614-2.2386 5-5 5H5.5c-.27614 0-.5-.2239-.5-.5s.22386-.5.5-.5H14c2.2091 0 4-1.7909 4-4 0-2.20914-1.7909-4-4-4H5.5c-.27614 0-.5-.22386-.5-.5M15 12c0 .8284-.6716 1.5-1.5 1.5-.6531 0-1.2087-.4174-1.4146-1H5.5c-.27614 0-.5-.2239-.5-.5s.22386-.5.5-.5h6.5854c.2059-.5826.7615-1 1.4146-1 .8284 0 1.5.6716 1.5 1.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
