// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconTimeSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M18 12c0 3.3137-2.6863 6-6 6-3.31371 0-6-2.6863-6-6 0-3.31371 2.68629-6 6-6 3.3137 0 6 2.68629 6 6m1 0c0 3.866-3.134 7-7 7s-7-3.134-7-7 3.134-7 7-7 7 3.134 7 7m-6.5-3.5c0-.27614-.2239-.5-.5-.5s-.5.22386-.5.5V12c0 .1326.0527.2598.1465.3535l2 2c.1952.1953.5118.1953.707 0 .1953-.1952.1953-.5118 0-.707L12.5 11.7929z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
