// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconInteractionDefaultSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M18 12c0 3.3137-2.6863 6-6 6-1.4769 0-2.82907-.5336-3.87442-1.4185l8.45592-8.45592C17.4664 9.17093 18 10.5231 18 12M7.41849 15.8744l8.45591-8.45591C14.8291 6.53358 13.4769 6 12 6c-3.31371 0-6 2.68629-6 6 0 1.4769.53358 2.8291 1.41849 3.8744M19 12c0 3.866-3.134 7-7 7s-7-3.134-7-7 3.134-7 7-7 7 3.134 7 7"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
