// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconLineSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M17.9786 6.02145c.1952.19526.1952.51184 0 .7071L6.72855 17.9786c-.19526.1952-.51184.1952-.7071 0-.19527-.1953-.19527-.5119 0-.7072L17.2714 6.02145c.1953-.19527.5119-.19527.7072 0"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
