// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconStrokeJoinBevel24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M6 6.5c0-.27614.22386-.5.5-.5h6c.1326 0 .2598.05268.3536.14645l5 4.99995c.0937.0938.1464.221.1464.3536v6c0 .2761-.2239.5-.5.5h-5c-.2761 0-.5-.2239-.5-.5V12H6.5c-.27614 0-.5-.2239-.5-.5zM7 7v4h5.5c.2761 0 .5.2239.5.5V17h4v-5.2929L12.2929 7z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
