// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAdjustSmall24 = createIcon(
  <svg
    fill="none"
    height="24"
    viewBox="0 0 24 24"
    width="24"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M8 5.5c0-.27614.22386-.5.5-.5s.5.22386.5.5v6.55c1.1411.2316 2 1.2405 2 2.45s-.8589 2.2184-2 2.45v1.55c0 .2761-.22386.5-.5.5s-.5-.2239-.5-.5v-1.55c-1.14112-.2316-2-1.2405-2-2.45s.85888-2.2184 2-2.45zm-1 9c0-.8284.67157-1.5 1.5-1.5s1.5.6716 1.5 1.5S9.32843 16 8.5 16 7 15.3284 7 14.5m8 4c0 .2761.2239.5.5.5s.5-.2239.5-.5v-6.55c1.1411-.2316 2-1.2405 2-2.45 0-1.20948-.8589-2.21836-2-2.44999V5.5c0-.27614-.2239-.5-.5-.5s-.5.22386-.5.5v1.55001c-1.1411.23163-2 1.24051-2 2.44999 0 1.2095.8589 2.2184 2 2.45zm-1-9c0 .8284.6716 1.5 1.5 1.5s1.5-.6716 1.5-1.5c0-.82843-.6716-1.5-1.5-1.5S14 8.67157 14 9.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
