// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconDevEdited16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7.08411 4.34674c.34952-.79891 1.48279-.79891 1.83232 0l2.73547 6.25256c.2891.6607-.195 1.4008-.9161 1.4008H5.26478c-.72116 0-1.20521-.7401-.91616-1.4008zm.91616.40082L5.26478 11.0001h5.47102z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
