// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconCircleInfo16 = createIcon(
  'M8 14c3.314 0 6-2.686 6-6s-2.686-6-6-6-6 2.686-6 6 2.686 6 6 6m0-1c-2.946 0-5-2.054-5-5s2.054-5 5-5 5 2.054 5 5-2.054 5-5 5m-.5-5.667h1v4h-1V9.5zm-.166-2c0-.368.298-.666.667-.666.368 0 .666.298.666.666 0 .369-.298.667-.666.667-.369 0-.667-.298-.667-.667',
  { height: 16, width: 16 }
)
