// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconBranch16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M3 4.5c0-.27614.22386-.5.5-.5h1C5.88071 4 7 5.11929 7 6.5v2c0 .82843.67157 1.5 1.5 1.5h2.7929l-1.1465-1.14645c-.19522-.19526-.19522-.51184 0-.7071.1953-.19527.5119-.19527.7072 0l2 1.99995c.1952.1953.1952.5119 0 .7072l-2 2c-.1953.1952-.5119.1952-.7072 0-.19522-.1953-.19522-.5119 0-.7072L11.2929 11H8.5C7.11929 11 6 9.88071 6 8.5v-2C6 5.67157 5.32843 5 4.5 5h-1c-.27614 0-.5-.22386-.5-.5m5.5 0c0-.27614.22386-.5.5-.5h3.5c.2761 0 .5.22386.5.5s-.2239.5-.5.5H9c-.27614 0-.5-.22386-.5-.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
