// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon.js'

export const IconCheck16 = createIcon(
  'M11.777 4.084a.5.5 0 0 1 .139.693l-4 6a.5.5 0 0 1-.77.077l-3-3a.5.5 0 1 1 .708-.708l2.568 2.57 3.662-5.493a.5.5 0 0 1 .693-.139',
  { height: 16, width: 16 }
)
