// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconTemperature16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M8 2.5c-.55229 0-1 .44771-1 1V6h2V3.5c0-.55229-.44771-1-1-1M7 9.49982V7h2v2.74959l.19971.15001C9.68661 10.2653 10 10.846 10 11.5c0 1.1046-.89543 2-2 2s-2-.8954-2-2c0-.654.31339-1.2347.80029-1.6004L7 9.74959zM6 3.5c0-1.10457.89543-2 2-2s2 .89543 2 2v5.76392c.6131.54873 1 1.34728 1 2.23608 0 1.6569-1.34314 3-3 3s-3-1.3431-3-3c0-.8888.38695-1.68735 1-2.23608zm5.5.5c-.2761 0-.5.22386-.5.5s.2239.5.5.5h1c.2761 0 .5-.22386.5-.5s-.2239-.5-.5-.5zM11 6.5c0-.27614.2239-.5.5-.5h1c.2761 0 .5.22386.5.5s-.2239.5-.5.5h-1c-.2761 0-.5-.22386-.5-.5m.5 1.5c-.2761 0-.5.22386-.5.5s.2239.5.5.5h1c.2761 0 .5-.22386.5-.5s-.2239-.5-.5-.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
