// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutAbsolutePosition16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M1 0C.44772 0 0 .44772 0 1v2.5c0 .27614.22386.5.5.5s.5-.22386.5-.5V1h2.5c.27614 0 .5-.22386.5-.5S3.77614 0 3.5 0zm14 0c.5523 0 1 .44772 1 1v2.5c0 .27614-.2239.5-.5.5s-.5-.22386-.5-.5V1h-2.5c-.2761 0-.5-.22386-.5-.5s.2239-.5.5-.5zM0 15c0 .5523.44772 1 1 1h2.5c.27614 0 .5-.2239.5-.5s-.22386-.5-.5-.5H1v-2.5c0-.2761-.22386-.5-.5-.5s-.5.2239-.5.5zm15 1c.5523 0 1-.4477 1-1v-2.5c0-.2761-.2239-.5-.5-.5s-.5.2239-.5.5V15h-2.5c-.2761 0-.5.2239-.5.5s.2239.5.5.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
