// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconLockLocked16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect
      fill="currentColor"
      fillOpacity="0.3"
      height="4"
      rx="0.25"
      width="6"
      x="5"
      y="8"
    />
    <path
      clip-rule="evenodd"
      d="M10.7763 8H5.22365l-.02472.00502C5.08524 8.0281 5 8.13021 5 8.25v3.5c0 .1381.11193.25.25.25h5.5c.1381 0 .25-.1119.25-.25v-3.5c0-.11978-.0852-.2219-.1989-.24498zM7 7H6V6c0-1.10457.89543-2 2-2s2 .89543 2 2v1H7M5 6c0-1.65685 1.34315-3 3-3s3 1.34315 3 3v1.025c.5706.11582 1 .62026 1 1.225v3.5c0 .6904-.5596 1.25-1.25 1.25h-5.5C4.55964 13 4 12.4404 4 11.75v-3.5c0-.60474.42944-1.10918 1-1.225V6"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
