// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconVariant16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7.29289 2.29289c.39053-.39052 1.02369-.39052 1.41422 0l4.99999 5c.3905.39053.3905 1.02369 0 1.41422L8.70711 13.7071c-.39053.3905-1.02369.3905-1.41422 0l-5-4.99999c-.39052-.39053-.39052-1.02369 0-1.41422zM3.70711 8.70711 3 8l.70711-.70711 3.58578-3.58578L8 3l.70711.70711 3.58579 3.58578L13 8l-.7071.70711-3.58579 3.58579L8 13l-.70711-.7071z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
