// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconArrowLeft16 = createIcon(
  'm2.29291 8.00001.35355-.35356 3-3 .70711.70711-2.14645 2.14645H12.5v1H4.20712l2.14645 2.14649-.70711.7071-3-3.00004-.35355-.35355Z',
  { height: 16, width: 16 }
)
