// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconBooleanUnion16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5 5h9v4h-4c-.55229 0-1 .44771-1 1v4H5zm4 10H5c-.55229 0-1-.4477-1-1V5c0-.55229.44771-1 1-1h9c.5523 0 1 .44771 1 1v4h4c.5523 0 1 .44771 1 1v9c0 .5523-.4477 1-1 1h-9c-.55229 0-1-.4477-1-1zm6-5h4v9h-9v-4h4c.5523 0 1-.4477 1-1zm-1 0v4h-4v-4z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
