// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutVerticalRight16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M4 4v2h8V4zm0-1c-.55228 0-1 .44772-1 1v2c0 .55228.44772 1 1 1h8c.5523 0 1-.44771 1-1V4c0-.55228-.4477-1-1-1zm4 7v2h4v-2zm0-1c-.55228 0-1 .44772-1 1v2c0 .5523.44771 1 1 1h4c.5523 0 1-.4477 1-1v-2c0-.55228-.4477-1-1-1z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
