// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconPrototype16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M12.257 9.31185 6.49892 12.7667C5.39915 13.4266 4 12.6344 4 11.3519V4.64791c0-1.28254 1.39915-2.07472 2.49892-1.41486L12.257 6.68792c.9905.59426.9905 2.02967 0 2.62393m-.5145-.85749c.3431-.20586.3431-.70309 0-.90895L5.98442 4.09054C5.55118 3.83059 5 4.14267 5 4.64791v6.70399c0 .5052.55118.8173.98442.5573z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
