// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconLockUnlocked16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5 5c0-1.65685 1.34315-3 3-3s3 1.34315 3 3v2.025c.5706.11582 1 .62026 1 1.225v3.5c0 .6904-.5596 1.25-1.25 1.25h-5.5C4.55964 13 4 12.4404 4 11.75v-3.5C4 7.55964 4.55964 7 5.25 7H10V5c0-1.10457-.89543-2-2-2s-2 .89543-2 2c0 .27614-.22386.5-.5.5S5 5.27614 5 5m.25 3c-.13807 0-.25.11193-.25.25v3.5c0 .1381.11193.25.25.25h5.5c.1381 0 .25-.1119.25-.25v-3.5c0-.13807-.1119-.25-.25-.25z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
