// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconMobile16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M10 3H6c-.55228 0-1 .44772-1 1v8c0 .5523.44772 1 1 1h4c.5523 0 1-.4477 1-1V4c0-.55228-.4477-1-1-1M6 2c-1.10457 0-2 .89543-2 2v8c0 1.1046.89543 2 2 2h4c1.1046 0 2-.8954 2-2V4c0-1.10457-.8954-2-2-2zm2.5 9.5c0 .2761-.22386.5-.5.5s-.5-.2239-.5-.5.22386-.5.5-.5.5.2239.5.5M7.5 4c-.27614 0-.5.22386-.5.5s.22386.5.5.5h1c.27614 0 .5-.22386.5-.5S8.77614 4 8.5 4z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
