// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconLine16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M12.8536 3.14645c.1952.19526.1952.51184 0 .7071L3.85355 12.8536c-.19526.1952-.51184.1952-.7071 0-.19527-.1953-.19527-.5119 0-.7072l8.99995-8.99995c.1953-.19527.5119-.19527.7072 0"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
