// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconHome16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="m7.66782 2.79524-.33218-.3737zm.66436 0 .33218-.3737zM3.66782 6.3508 4 6.7245zm8.66438 0 .3322-.37371zM8 3.16895l.66436-.74741c-.37888-.33679-.94984-.33679-1.32872 0zM4 6.7245l4-3.55555-.66436-.74741-4 3.55555zm0 0-.66436-.74741A1 1 0 0 0 3 6.7245zM4 12V6.7245H3V12zm0 0H3c0 .5523.44772 1 1 1zm2 0H4v1h2zm1 0V8.99997H6V12zm0-3.00003v-1c-.55228 0-1 .44772-1 1zm0 0h2v-1H7zm2 0h1c0-.55228-.44772-1-1-1zm0 0V12h1V8.99997zM12 12h-2v1h2zm0 0v1c.5523 0 1-.4477 1-1zm0-5.2755V12h1V6.7245zm0 0h1a1 1 0 0 0-.3356-.74741zM8 3.16895l4 3.55555.6644-.74741-4.00004-3.55555zM9 12c0 .5523.44771 1 1 1v-1zm-3 1c.55228 0 1-.4477 1-1H6z"
      fill="currentColor"
    />
  </svg>
)
