// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon.js'

export const IconCircleInfo16 = createIcon(
  'M13 8A5 5 0 1 1 3 8a5 5 0 0 1 10 0m1 0A6 6 0 1 1 2 8a6 6 0 0 1 12 0m-6.517 2.536a.514.514 0 1 0 1.028 0V7.2a.514.514 0 1 0-1.028 0zm.097-4.631a.6.6 0 0 0 .42.162.6.6 0 0 0 .42-.162.52.52 0 0 0 .177-.395.52.52 0 0 0-.177-.395A.6.6 0 0 0 8 4.95a.6.6 0 0 0-.42.165.52.52 0 0 0-.177.395q0 .23.177.395',
  { height: 16, width: 16 }
)
