// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconVariable16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M12.5 4.2534 9 2.23267c-.6188-.35726-1.3812-.35726-2 0L3.5 4.2534c-.6188.35726-1 1.01752-1 1.73205v4.04145c0 .7145.3812 1.3748 1 1.732L7 13.7797c.6188.3572 1.3812.3572 2 0l3.5-2.0208c.6188-.3572 1-1.0175 1-1.732V5.98545c0-.71453-.3812-1.37479-1-1.73205m-5-1.1547a1 1 0 0 1 1 0L12 5.11942a1 1 0 0 1 .5.86603v4.04145c0 .3573-.1906.6874-.5.866l-3.5 2.0207a.9997.9997 0 0 1-1 0L4 10.8929a.9999.9999 0 0 1-.5-.866V5.98545a1 1 0 0 1 .5-.86603zM9 7.00002H7v2h2z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
