// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconShadows16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M8.5 2c.27614 0 .5.22386.5.5v.60002C11.2822 3.56329 13 5.58104 13 8c0 2.419-1.7178 4.4367-4 4.9v.6c0 .2761-.22386.5-.5.5H8c-3.31371 0-6-2.6863-6-6 0-3.31371 2.68629-6 6-6zM8 12v1c-2.76143 0-5-2.2386-5-5 0-2.76143 2.23857-5 5-5v9m1-7.87398V11.874c1.7252-.4441 3-2.01017 3-3.874s-1.2748-3.42993-3-3.87398"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
