// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutAlignmentBaseline16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="m6.96122 9.93442-.64483 1.81648c-.09558.2693-.35032.4491-.63602.4491-.46925 0-.79528-.467-.63354-.9075l2.53068-6.89203c.13244-.36068.47586-.60042.86009-.60042s.72765.23974.86008.60042l2.53072 6.89203c.1617.4405-.1643.9075-.6336.9075-.2857 0-.5404-.1798-.636-.4491l-.64483-1.81648zM8.4376 5.77549 7.40829 8.67505h2.05862z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
