// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconConnector16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M10.6464 2.64645c.1953-.19527.5119-.19527.7072 0l1.5 1.5c.1952.19526.1952.51184 0 .7071l-1.5 1.5c-.1953.19527-.5119.19527-.7072 0-.1952-.19526-.1952-.51184 0-.7071L11.2929 5H10.5C9.67157 5 9 5.67157 9 6.5v3C9 10.8807 7.88071 12 6.5 12H6a.504.504 0 0 1-.08295-.0068C5.71308 12.5793 5.15567 13 4.5 13c-.82843 0-1.5-.6716-1.5-1.5S3.67157 10 4.5 10c.65567 0 1.21308.4207 1.41705 1.0068A.504.504 0 0 1 6 11h.5c.82843 0 1.5-.6716 1.5-1.5v-3C8 5.11929 9.11929 4 10.5 4h.7929l-.6465-.64645c-.1952-.19526-.1952-.51184 0-.7071M4.5 12c.27614 0 .5-.2239.5-.5s-.22386-.5-.5-.5-.5.2239-.5.5.22386.5.5.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
