// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconSlidesSmall16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5.5 5h5c.2761 0 .5.22386.5.5v4c0 .27614-.2239.5-.5.5h-5c-.27614 0-.5-.22386-.5-.5v-4c0-.27614.22386-.5.5-.5m-.38341 5.9506C4.4739 10.7811 4 10.1959 4 9.5v-4C4 4.67157 4.67157 4 5.5 4h5c.8284 0 1.5.67157 1.5 1.5v4c0 .6961-.4741 1.2814-1.1171 1.4507l.1033.4335c.0639.2686-.102.5382-.3706.6022-.2687.064-.5383-.102-.6023-.3706L9.86672 11H6.13277l-.14662.6158c-.06396.2686-.33358.4346-.60221.3706s-.43456-.3336-.3706-.6022zM6.5 6c-.27614 0-.5.22386-.5.5s.22386.5.5.5.5-.22386.5-.5-.22386-.5-.5-.5m0 2c-.27614 0-.5.22386-.5.5s.22386.5.5.5.5-.22386.5-.5-.22386-.5-.5-.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
