// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutGridVerticalRight16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M4 7c-.55228 0-1 .44772-1 1s.44772 1 1 1h8c.5523 0 1-.44771 1-1s-.4477-1-1-1zm3-4c-.55228 0-1 .44772-1 1s.44772 1 1 1h5c.5523 0 1-.44771 1-1s-.4477-1-1-1zm1 9c0-.5523.44771-1 1-1h3c.5523 0 1 .4477 1 1s-.4477 1-1 1H9c-.55229 0-1-.4477-1-1"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
