// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconMultiEdit16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M10.5 3.5c0-.27614.2239-.5.5-.5h1.5c.2761.00002.5.22386.5.5V5c0 .27615-.2239.5-.5.5S12 5.27615 12 5V4h-1c-.2761 0-.5-.22386-.5-.5M3 3.5c0-.27614.22386-.5.5-.5H5c.27614 0 .5.22386.5.5 0 .27615-.22386.5-.5.5H4v1c0 .27615-.22386.5-.5.5S3 5.27615 3 5zm.5 7c.27614 0 .5.2239.5.5v1h1c.27614 0 .5.2239.5.5 0 .2762-.22386.5-.5.5H3.5c-.27614 0-.5-.2238-.5-.5V11c0-.2761.22386-.5.5-.5m9 0c.2761 0 .5.2239.5.5v1.5a.50001.50001 0 0 1-.5.5H11c-.2761 0-.5-.2239-.5-.5s.2239-.5.5-.5h1v-1c0-.2761.2239-.5.5-.5M6.5 6h-1v4h1zm-1-1c-.55229 0-1 .44771-1 1v4c0 .5523.44771 1 1 1h1c.55229 0 1-.4477 1-1V6c0-.55229-.44771-1-1-1zm4 1h1v4h-1zm-1 0c0-.55229.44771-1 1-1h1c.5523 0 1 .44771 1 1v4c0 .5523-.4477 1-1 1h-1c-.55229 0-1-.4477-1-1z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
