// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconLayerRectangle16 = createIcon(
  'M12 4H4v8h8zM4 3H3v10h10V3h-1z',
  { height: 16, width: 16 }
)
