// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconCaretLeft16 = createIcon('m4 8 4 3V5L4 8Z', {
  height: 16,
  width: 16
})
