// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconDesktop16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M3 10V4h10v6zM2 3.5c0-.27614.22386-.5.5-.5h11c.2761 0 .5.22386.5.5v7c0 .2761-.2239.5-.5.5H10v1h.5c.2761 0 .5.2239.5.5s-.2239.5-.5.5h-5c-.27614 0-.5-.2239-.5-.5s.22386-.5.5-.5H6v-1H2.5c-.27614 0-.5-.2239-.5-.5zM7 11v1h2v-1z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
