// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconNavigateForward16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5.64645 12.3536c-.19527-.1953-.19527-.5119 0-.7072L8.79289 8.5 5.64645 5.35355c-.19527-.19526-.19526-.51184 0-.7071.19526-.19527.51184-.19527.7071 0l3.5 3.5c.19525.19526.19525.51184 0 .7071l-3.5 3.50005c-.19526.1952-.51184.1952-.7071 0"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
