// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconFlatten16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M8.5 2.5c0-.27614-.22386-.5-.5-.5s-.5.22386-.5.5v2.79289L6.35355 4.14645c-.19526-.19527-.51184-.19527-.7071 0-.19527.19526-.19527.51184 0 .7071l2 2c.19526.19527.51184.19527.7071 0l2.00005-2c.1952-.19526.1952-.51184 0-.7071-.1953-.19527-.51189-.19527-.70715 0L8.5 5.29289zM2 9.5c0-.27614.22386-.5.5-.5h11c.2761 0 .5.22386.5.5s-.2239.5-.5.5h-11c-.27614 0-.5-.22386-.5-.5m1 3c0-.2761.22386-.5.5-.5h9c.2761 0 .5.2239.5.5s-.2239.5-.5.5h-9c-.27614 0-.5-.2239-.5-.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
