// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon.js'

export const IconTextAlignJustified16 = createIcon(
  'M1 3h14v1H1zm0 4h14v1H1zm14 4H1v1h14z',
  { height: 16, width: 16 }
)
