// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconLayerRectangle16 = createIcon(
  'M12 4H4v8h8V4ZM4 3H3v10h10V3H4Z',
  { height: 16, width: 16 }
)
