// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconFolder16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M4 4h3v1H4zM3 5V4c0-.55229.44771-1 1-1h3c.55229 0 1 .44771 1 1v1h4c.5523 0 1 .44771 1 1v5c0 .5523-.4477 1-1 1H4c-.55229 0-1-.4477-1-1V5m5 1H4v5h8V6z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
