// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconOrientationLandscape16 = createIcon(
  'M2 5v6h12V5zm-1 6v1h14V4H1v1z',
  { height: 16, width: 16 }
)
