// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconChevronRight16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M6.76754 5.52511c.19526-.19526.51184-.19526.70711 0l2.12131 2.12132.35356.35356-.35356.35355-2.12131 2.12136c-.19527.1952-.51185.1952-.70711 0-.19526-.1953-.19526-.51188 0-.70715l1.76777-1.76776-1.76777-1.76777c-.19526-.19527-.19526-.51185 0-.70711"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
