// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconCaretUp16 = createIcon('m8 6 3 4H5l3-4Z', {
  height: 16,
  width: 16
})
