// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconBooleanExclude16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M9 4H4v5h2V7c0-.55228.44772-1 1-1h2zm1 3v2c0 .55228-.44772 1-1 1H7v2h5V7z"
      fill="currentColor"
      fill-rule="evenodd"
      fillOpacity="0.3"
    />
    <path
      clip-rule="evenodd"
      d="M7 12h5V7h-2v2c0 .55229-.44771 1-1 1H7zm.5-3H7V7h2v2zM6 9H4V4h5v2H7c-.55229 0-1 .44771-1 1v2m-1 1H4c-.55229 0-1-.44771-1-1V4c0-.55229.44771-1 1-1h5c.55229 0 1 .44771 1 1v2h2c.5523 0 1 .44771 1 1v5c0 .5523-.4477 1-1 1H7c-.55229 0-1-.4477-1-1v-2z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
