// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconString16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M4.5 3C3.67157 3 3 3.67157 3 4.5v7c0 .8284.67157 1.5 1.5 1.5h7c.8284 0 1.5-.6716 1.5-1.5v-7c0-.82843-.6716-1.5-1.5-1.5zM4 4.5c0-.27615.22386-.5.5-.5h7c.2761 0 .5.22385.5.5v7c0 .2761-.2239.5-.5.5h-7c-.27614 0-.5-.2239-.5-.5zM6.5 6c-.27614 0-.5.22385-.5.5V7c0 .27615.22386.5.5.5S7 7.27615 7 7h.5v2c-.27614 0-.5.22386-.5.5s.22386.5.5.5h1c.27614 0 .5-.22386.5-.5S8.77614 9 8.5 9V7H9c0 .27615.22386.5.5.5s.5-.22385.5-.5v-.5c0-.27615-.22386-.5-.5-.5h-3"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
