// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconAnchorHorizontal16 = createIcon(
  'M3.50021 7.49987v-2h-1v5.00003h1V8.49987h8.99999v2.00003h1V5.49987h-1v2z',
  { height: 16, width: 16 }
)
