// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconHighlights16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7.5 2c-.27614 0-.5.22386-.5.5v.60002C4.71776 3.56329 3 5.58104 3 8c0 2.419 1.71776 4.4367 4 4.9v.6c0 .2761.22386.5.5.5H8c3.3137 0 6-2.6863 6-6 0-3.31371-2.6863-6-6-6zM8 12v1c2.7614 0 5-2.2386 5-5 0-2.76143-2.2386-5-5-5v9M7 4.12602V11.874C5.27478 11.4299 4 9.86383 4 8s1.27478-3.42993 3-3.87398"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
