// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconText16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M3 3.5c0-.27614.22386-.5.5-.5h9c.2761 0 .5.22386.5.5V5c0 .27614-.2239.5-.5.5S12 5.27614 12 5V4H8.5v8h1c.27614 0 .5.2239.5.5s-.22386.5-.5.5h-3c-.27614 0-.5-.2239-.5-.5s.22386-.5.5-.5h1V4H4v1c0 .27614-.22386.5-.5.5S3 5.27614 3 5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
