// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon.js'

export const IconPaddingVertical16 = createIcon(
  'M13 3H3v1h10zM3 5h10v1H3zm10 5H3v1h10zm0 2H3v1h10z',
  { height: 16, width: 16 }
)
