// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutHorizontalTop16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M4 4h2v8H4zM3 4c0-.55229.44771-1 1-1h2c.55229 0 1 .44771 1 1v8c0 .5523-.44771 1-1 1H4c-.55229 0-1-.4477-1-1zm7 0h2v4h-2zM9 4c0-.55229.44771-1 1-1h2c.5523 0 1 .44771 1 1v4c0 .55229-.4477 1-1 1h-2c-.55229 0-1-.44771-1-1z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
