// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconShapeText16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M4.5 4h7c.2761 0 .5.22386.5.5v7c0 .2761-.2239.5-.5.5h-7c-.27614 0-.5-.2239-.5-.5v-7c0-.27614.22386-.5.5-.5M3 4.5C3 3.67157 3.67157 3 4.5 3h7c.8284 0 1.5.67157 1.5 1.5v7c0 .8284-.6716 1.5-1.5 1.5h-7c-.82843 0-1.5-.6716-1.5-1.5zm3 1c-.27614 0-.5.22386-.5.5v.5c0 .27614.22386.5.5.5s.5-.22386.5-.5h1v3c-.27614 0-.5.22386-.5.5 0 .2761.22386.5.5.5h1c.27614 0 .5-.2239.5-.5 0-.27614-.22386-.5-.5-.5v-3h1c0 .27614.22386.5.5.5.2761 0 .5-.22386.5-.5V6c0-.27614-.2239-.5-.5-.5H6"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
