// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutGridHorizontalTop16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M3 4c0-.55228.44772-1 1-1s1 .44772 1 1v5c0 .55228-.44772 1-1 1s-1-.44772-1-1zm4 0c0-.55228.44772-1 1-1s1 .44772 1 1v8c0 .5523-.44772 1-1 1s-1-.4477-1-1zm5-1c-.5523 0-1 .44772-1 1v3c0 .55228.4477 1 1 1s1-.44772 1-1V4c0-.55228-.4477-1-1-1"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
