// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconBoolean16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M10 5H6C4.34315 5 3 6.34315 3 8s1.34315 3 3 3h4c1.6569 0 3-1.34315 3-3 0-1.65686-1.3431-3-3-3m0 7c2.2091 0 4-1.7909 4-4 0-2.20914-1.7909-4-4-4H6C3.79086 4 2 5.79086 2 8c0 2.2091 1.79086 4 4 4zm1-4c0 .55228-.4477 1-1 1-.55228 0-1-.44772-1-1s.44772-1 1-1c.5523 0 1 .44771 1 1m1 0c0 1.10457-.8954 2-2 2-1.10457 0-2-.89543-2-2s.89543-2 2-2c1.1046 0 2 .89543 2 2"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
