// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutGridVerticalAutoLargeBottom16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      d="M12 11c.5523 0 1 .4477 1 1s-.4477 1-1 1H4c-.55228 0-1-.4477-1-1s.44771-1 1-1z"
      fill="currentColor"
    />
  </svg>
)
