// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAutoLayoutWrapCenter16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M6 4H4v2h2zM4 3c-.55229 0-1 .44771-1 1v2c0 .55229.44771 1 1 1h2c.55229 0 1-.44771 1-1V4c0-.55229-.44771-1-1-1zm8 1h-2v2h2zm-2-1c-.55229 0-1 .44771-1 1v2c0 .55229.44771 1 1 1h2c.5523 0 1-.44771 1-1V4c0-.55229-.4477-1-1-1zm-3 7h2v2H7zm-1 0c0-.55229.44771-1 1-1h2c.55229 0 1 .44771 1 1v2c0 .5523-.44771 1-1 1H7c-.55229 0-1-.4477-1-1z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
