// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAnimated16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M4.5 4h7c.2761 0 .5.22386.5.5v7c0 .2761-.2239.5-.5.5h-7c-.27614 0-.5-.2239-.5-.5v-7c0-.27614.22386-.5.5-.5M3 4.5C3 3.67157 3.67157 3 4.5 3h7c.8284 0 1.5.67157 1.5 1.5v7c0 .8284-.6716 1.5-1.5 1.5h-7c-.82843 0-1.5-.6716-1.5-1.5zm7.0145 4.35749a1 1 0 0 0 0-1.71498l-2.5-1.5A1 1 0 0 0 6 6.5v3a1 1 0 0 0 .5073.8702c.31351.1775.69826.1727 1.0072-.0127zM9.5 8l-.97183.58309L8 8.9l-1 .6v-3l1 .6.52817.3169z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
