// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconWarning16 = createIcon(
  'm8 0 8 14.5H0L8 0Zm0 4.38174c.49706 0 .9.40294.9.9v3.0878c0 .49706-.40294.9-.9.9s-.9-.40294-.9-.9v-3.0878c0-.49706.40294-.9.9-.9Zm1.10007 7.37506c0-.6075-.49248-1.1-1.1-1.1-.60751 0-1.1.4925-1.1 1.1v.0686c0 .6075.49249 1.1 1.1 1.1.60752 0 1.1-.4925 1.1-1.1v-.0686Z',
  { height: 16, width: 16 }
)
