// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconAutoLayoutVerticalCenter16 = createIcon(
  'M4 3v2h8V3H4ZM3 7v2h10V7H3Zm2 6v-2h6v2H5Z',
  { height: 16, width: 16 }
)
