// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconRectangle16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M11.5 4h-7c-.27614 0-.5.22386-.5.5v7c0 .2761.22386.5.5.5h7c.2761 0 .5-.2239.5-.5v-7c0-.27614-.2239-.5-.5-.5m-7-1C3.67157 3 3 3.67157 3 4.5v7c0 .8284.67157 1.5 1.5 1.5h7c.8284 0 1.5-.6716 1.5-1.5v-7c0-.82843-.6716-1.5-1.5-1.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
