// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconSlides16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M4 4h8c.5523 0 1 .44772 1 1v5c0 .5523-.4477 1-1 1H4c-.55228 0-1-.4477-1-1V5c0-.55228.44772-1 1-1m.43389 8H4c-1.10457 0-2-.8954-2-2V5c0-1.10457.89543-2 2-2h8c1.1046 0 2 .89543 2 2v5c0 1.1046-.8954 2-2 2h-.4339l.4122 1.3544c.0804.2642-.0685.5435-.3327.6239s-.5435-.0685-.6239-.3327L10.5208 12H5.47918l-.50083 1.6456c-.0804.2642-.35974.4131-.62392.3327s-.41316-.3597-.33276-.6239zM5 5c-.55228 0-1 .44772-1 1s.44772 1 1 1 1-.44772 1-1-.44772-1-1-1m0 3c-.55228 0-1 .44772-1 1s.44772 1 1 1 1-.44772 1-1-.44772-1-1-1"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
