// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconCoverArt16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M4.5 4h7c.2761 0 .5.22386.5.5V9H4V4.5c0-.27614.22386-.5.5-.5M4 10v1.5c0 .2761.22386.5.5.5h7c.2761 0 .5-.2239.5-.5V10zM3 4.5C3 3.67157 3.67157 3 4.5 3h7c.8284 0 1.5.67157 1.5 1.5v7c0 .8284-.6716 1.5-1.5 1.5h-7c-.82843 0-1.5-.6716-1.5-1.5z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
