// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconMenuCheckmarkMixed16 = createIcon('M12 9H4.00003V7H12v2Z', {
  height: 16,
  width: 16
})
