// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconAutoLayoutHorizontalTop16 = createIcon(
  'M3 11h2V3H3v8Zm4 2h2V3H7v10Zm6-4h-2V3h2v6Z',
  { height: 16, width: 16 }
)
