// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconAiSort16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M4 4h2v2H4zM3 4c0-.55228.44772-1 1-1h2c.55228 0 1 .44772 1 1v2c0 .55228-.44772 1-1 1H4c-.55228 0-1-.44772-1-1zm7.5149 4.94029L10.2 10.2l-1.25971.3149c-.50498.1263-.50498.8439 0 .9702L10.2 11.8l.3149 1.2597c.1263.505.8439.505.9702 0L11.8 11.8l1.2597-.3149c.505-.1263.505-.8439 0-.9702L11.8 10.2l-.3149-1.25971c-.1263-.50498-.8439-.50498-.9702 0M6 10H4v2h2zM4 9c-.55228 0-1 .44772-1 1v2c0 .5523.44772 1 1 1h2c.55228 0 1-.4477 1-1v-2c0-.55228-.44772-1-1-1zm6-5h2v2h-2zM9 4c0-.55228.44772-1 1-1h2c.5523 0 1 .44772 1 1v2c0 .55228-.4477 1-1 1h-2c-.55228 0-1-.44772-1-1z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
