// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconPolygon16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M7.99995 3a1 1 0 0 1 .87158.50974l4.50007 7.99996c.1741.3097.171.6885-.0084.9951-.1793.3067-.5079.4952-.8632.4952h-9a1 1 0 0 1-.86321-.4952c-.17935-.3066-.18254-.6854-.00837-.9951l4.49996-7.99996A1 1 0 0 1 7.99995 3m.00001 1-.57367 1.01987L4.06249 11 3.5 12h9l-.5625-1-3.36387-5.98014z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
