// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconImage16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M11.5 4h-7c-.27614 0-.5.22386-.5.5v5.29289l2.14645-2.14644c.19526-.19527.51184-.19527.7071 0L11.2071 12H11.5c.2761 0 .5-.2239.5-.5v-7c0-.27614-.2239-.5-.5-.5M3 10.9999V11.5c0 .8284.67157 1.5 1.5 1.5h7c.8284 0 1.5-.6716 1.5-1.5v-7c0-.82843-.6716-1.5-1.5-1.5h-7C3.67157 3 3 3.67157 3 4.5zM4.5 12h5.29289L6.5 8.70711 4 11.2071V11.5c0 .2761.22386.5.5.5m5-4.5c.5523 0 1-.44772 1-1s-.4477-1-1-1c-.55228 0-1 .44772-1 1s.44772 1 1 1"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
