// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconAlignTop16 = createIcon(
  'M15 1H1v1h14V1ZM8.35355 3.64645 8 3.29289l-.35355.35356-3 3 .7071.7071L7.5 5.20711V13h1V5.20711l2.1464 2.14644.7072-.7071-3.00005-3Z',
  { height: 16, width: 16 }
)
