// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconStamp16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="m9 6.78909.33308-.29812C9.74385 6.12332 10 5.59224 10 5c0-1.10457-.89543-2-2-2s-2 .89543-2 2c0 .59224.25615 1.12332.66692 1.49097L7 6.78909V8.5h2V6.78909m1 1.78736V7.2361c.6138-.54932 1-1.3476 1-2.2361 0-1.65686-1.34314-3-3-3S5 3.34314 5 5c0 .8885.38625 1.68678 1 2.2361v1.34035l-2.5822.43036C3.17671 9.04698 3 9.25558 3 9.5v2c0 .2761.22386.5.5.5h9c.2761 0 .5-.2239.5-.5v-2c0-.24442-.1767-.45302-.4178-.49319zM9.45862 9.5H6.54138L4 9.92357V11h8V9.92357zM5 13.5c0-.2761.22386-.5.5-.5h5c.2761 0 .5.2239.5.5s-.2239.5-.5.5h-5c-.27614 0-.5-.2239-.5-.5"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
