// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconLayerAnimated16 = createIcon(
  'M3 3h10v10H3V3ZM2 3c0-.55228.44772-1 1-1h10c.5523 0 1 .44772 1 1v10c0 .5523-.4477 1-1 1H3c-.55228 0-1-.4477-1-1V3Zm8.5 5L6.00003 5.5v5L10.5 8Z',
  { height: 16, width: 16 }
)
