// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconLayerLine16 = createIcon('M3.5 7.5h9v1h-9v-1Z', {
  height: 16,
  width: 16
})
