// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconRatingFilled16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M8.70223 2.44865c-.24334-.64886-1.16116-.64886-1.40449.00001L6.15345 5.50003H2.76023c-.72382 0-1.02768.92398-.44516 1.3536l2.82162 2.081-.93373 3.08627c-.20591.6807.56258 1.239 1.14626.8328l2.65076-1.8445 2.65082 1.8445c.5836.4062 1.3521-.1521 1.1462-.8328l-.9337-3.08626 2.8217-2.081c.5826-.42962.2787-1.35361-.4451-1.35361H9.84656z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
