// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconHeart16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M3.73223 8.26783c-.97631-.97631-.97631-2.55923 0-3.53554s2.55923-.97631 3.53554 0L8 5.46453l.73223-.73224c.97631-.97631 2.55927-.97631 3.53557 0s.9763 2.55923 0 3.53554L8 12.5356zM8 4.05031l.02513-.02512c1.36683-1.36684 3.58287-1.36684 4.94977 0 1.3668 1.36683 1.3668 3.58291 0 4.94974L8.70711 13.2427c-.39053.3905-1.02369.3905-1.41422 0L3.02513 8.97493c-1.36684-1.36683-1.36684-3.58291 0-4.94974 1.36683-1.36684 3.58291-1.36684 4.94974 0z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
