// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { createIcon } from '../create-icon.js'

export const IconFrame16 = createIcon(
  <svg
    fill="none"
    height="16"
    viewBox="0 0 16 16"
    width="16"
    xmlns="http://www.w3.org/2000/svg"
  >
    <path
      clip-rule="evenodd"
      d="M5.5 3c.27614 0 .5.22386.5.5V5h4V3.5c0-.27614.2239-.5.5-.5s.5.22386.5.5V5h1.5c.2761 0 .5.22386.5.5s-.2239.5-.5.5H11v4h1.5c.2761 0 .5.2239.5.5s-.2239.5-.5.5H11v1.5c0 .2761-.2239.5-.5.5s-.5-.2239-.5-.5V11H6v1.5c0 .2761-.22386.5-.5.5s-.5-.2239-.5-.5V11H3.5c-.27614 0-.5-.2239-.5-.5s.22386-.5.5-.5H5V6H3.5c-.27614 0-.5-.22386-.5-.5s.22386-.5.5-.5H5V3.5c0-.27614.22386-.5.5-.5m4.5 7V6H6v4z"
      fill="currentColor"
      fill-rule="evenodd"
    />
  </svg>
)
