// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconAutoLayoutVerticalLeft16 = createIcon(
  'M3 3v2h8V3H3zm0 4v2h10V7H3zm0 6v-2h6v2H3z',
  { height: 16, width: 16 }
)
