// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconAutoLayoutHorizontalBottom16 = createIcon(
  'M7 13h2V3H7v10Zm-4 0h2V5H3v8Zm10 0h-2V7h2v6Z',
  { height: 16, width: 16 }
)
