// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconLockUnlocked16 = createIcon(
  'M10 6v1h.5c.2761 0 .5.22386.5.5v5c0 .2761-.2239.5-.5.5h-6c-.27614 0-.5-.2239-.5-.5v-5c0-.27614.22386-.5.5-.5H9V4.5C9 3.11929 10.1193 2 11.5 2S14 3.11929 14 4.5V6h-1V4.5c0-.82843-.6716-1.5-1.5-1.5S10 3.67157 10 4.5V6Z',
  { height: 16, width: 16 }
)
