// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconSpaceVertical16 = createIcon(
  'M2 2v3h12V2h-1v2H3V2H2zm9 7H5V8h6v1zm-9 3h12v3h-1v-2H3v2H2v-3z',
  { height: 16, width: 16 }
)
