// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconOrientationPortrait16 = createIcon(
  'M11 2H5v12h6V2zM5 1H4v14h8V1H5z',
  { height: 16, width: 16 }
)
