// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconLayerFrameCoverArt16 = createIcon(
  'M5 4h6c.5523 0 1 .44772 1 1v4H4V5c0-.55228.44772-1 1-1Zm-1 6v1c0 .5523.44772 1 1 1h6c.5523 0 1-.4477 1-1v-1H4ZM3 5c0-1.10457.89543-2 2-2h6c1.1046 0 2 .89543 2 2v6c0 1.1046-.8954 2-2 2H5c-1.10457 0-2-.8954-2-2V5Z',
  { height: 16, width: 16 }
)
