// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconCaretRight16 = createIcon('M12 8 8 5v6l4-3Z', {
  height: 16,
  width: 16
})
