// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconTextAlignLeft16 = createIcon(
  'M1 3h14v1H1V3zm0 4h8v1H1V7zm10 4H1v1h10v-1z',
  { height: 16, width: 16 }
)
