// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconOptionDisabled16 = createIcon('M10 9H6V8h4v1z', {
  height: 16,
  width: 16
})
