// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconStarFilled16 = createIcon(
  'M7.99999.5 10 5.5h5L11 9l1.5 5L8 11l-4.5 3.0676L5 8.88525 1 5.5h5l1.99999-5Z',
  { height: 16, width: 16 }
)
