// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/** @jsx h */
import { h } from 'preact'

import { IconAlignBottom16 } from './icon-align-bottom-16'
import { IconAlignMiddle16 } from './icon-align-middle-16'
import { IconAlignTop16 } from './icon-align-top-16'
import { IconAnchorHorizontal16 } from './icon-anchor-horizontal-16'
import { IconAnchorVertical16 } from './icon-anchor-vertical-16'
import { IconArrowDown16 } from './icon-arrow-down-16'
import { IconArrowLeft16 } from './icon-arrow-left-16'
import { IconArrowLeftRight16 } from './icon-arrow-left-right-16'
import { IconArrowRight16 } from './icon-arrow-right-16'
import { IconArrowUp16 } from './icon-arrow-up-16'
import { IconArrowUpDown16 } from './icon-arrow-up-down-16'
import { IconAutoLayoutHorizontalBottom16 } from './icon-auto-layout-horizontal-bottom-16'
import { IconAutoLayoutHorizontalCenter16 } from './icon-auto-layout-horizontal-center-16'
import { IconAutoLayoutHorizontalTop16 } from './icon-auto-layout-horizontal-top-16'
import { IconAutoLayoutVerticalCenter16 } from './icon-auto-layout-vertical-center-16'
import { IconAutoLayoutVerticalLeft16 } from './icon-auto-layout-vertical-left-16'
import { IconAutoLayoutVerticalRight16 } from './icon-auto-layout-vertical-right-16'
import { IconCaretDown16 } from './icon-caret-down-16'
import { IconCaretLeft16 } from './icon-caret-left-16'
import { IconCaretRight16 } from './icon-caret-right-16'
import { IconCaretUp16 } from './icon-caret-up-16'
import { IconChevronDown16 } from './icon-chevron-down-16'
import { IconChevronUp16 } from './icon-chevron-up-16'
import { IconCircleHelp16 } from './icon-circle-help-16'
import { IconCircleInfo16 } from './icon-circle-info-16'
import { IconCode16 } from './icon-code-16'
import { IconConnector16 } from './icon-connector-16'
import { IconHyperlink16 } from './icon-hyperlink-16'
import { IconLayerAnimated16 } from './icon-layer-animated-16'
import { IconLayerComponent16 } from './icon-layer-component-16'
import { IconLayerEllipse16 } from './icon-layer-ellipse-16'
import { IconLayerFrame16 } from './icon-layer-frame-16'
import { IconLayerFrameCoverArt16 } from './icon-layer-frame-cover-art-16'
import { IconLayerFrameScrolling16 } from './icon-layer-frame-scrolling-16'
import { IconLayerFrameScrollingHorizontal16 } from './icon-layer-frame-scrolling-horizontal-16'
import { IconLayerFrameScrollingVertical16 } from './icon-layer-frame-scrolling-vertical-16'
import { IconLayerGroup16 } from './icon-layer-group-16'
import { IconLayerImage16 } from './icon-layer-image-16'
import { IconLayerInstance16 } from './icon-layer-instance-16'
import { IconLayerLine16 } from './icon-layer-line-16'
import { IconLayerMask16 } from './icon-layer-mask-16'
import { IconLayerRectangle16 } from './icon-layer-rectangle-16'
import { IconLayerSlice16 } from './icon-layer-slice-16'
import { IconLayerText16 } from './icon-layer-text-16'
import { IconLayerVector16 } from './icon-layer-vector-16'
import { IconLockLocked16 } from './icon-lock-locked-16'
import { IconLockUnlocked16 } from './icon-lock-unlocked-16'
import { IconMenuCheckmarkBreadcrumb16 } from './icon-menu-checkmark-breadcrumb-16'
import { IconMenuCheckmarkChecked16 } from './icon-menu-checkmark-checked-16'
import { IconMenuCheckmarkMixed16 } from './icon-menu-checkmark-mixed-16'
import { IconMoveDown16 } from './icon-move-down-16'
import { IconMoveRight16 } from './icon-move-right-16'
import { IconOptionCheck16 } from './icon-option-check-16'
import { IconOptionDisabled16 } from './icon-option-disabled-16'
import { IconOrientationLandscape16 } from './icon-orientation-landscape-16'
import { IconOrientationPortrait16 } from './icon-orientation-portrait-16'
import { IconPaddingHorizontal16 } from './icon-padding-horizontal-16'
import { IconPaddingVertical16 } from './icon-padding-vertical-16'
import { IconSpaceHorizontal16 } from './icon-space-horizontal-16'
import { IconSpaceVertical16 } from './icon-space-vertical-16'
import { IconStar16 } from './icon-star-16'
import { IconStarFilled16 } from './icon-star-filled-16'
import { IconSwap16 } from './icon-swap-16'
import { IconTarget16 } from './icon-target-16'
import { IconTextAlignCenter16 } from './icon-text-align-center-16'
import { IconTextAlignJustified16 } from './icon-text-align-justified-16'
import { IconTextAlignLeft16 } from './icon-text-align-left-16'
import { IconTextAlignRight16 } from './icon-text-align-right-16'
import { IconTextDecorationStrikethrough16 } from './icon-text-decoration-strikethrough-16'
import { IconTextDecorationUnderline16 } from './icon-text-decoration-underline-16'
import { IconUpload16 } from './icon-upload-16'
import { IconVisibilityHidden16 } from './icon-visibility-hidden-16'
import { IconVisibilityVisible16 } from './icon-visibility-visible-16'
import { IconWarning16 } from './icon-warning-16'
import { IconWorld16 } from './icon-world-16'

export default { title: 'Components/Icon/Size 16' }

export const AlignBottom = function () {
  return <IconAlignBottom16 />
}

export const AlignMiddle = function () {
  return <IconAlignMiddle16 />
}

export const AlignTop = function () {
  return <IconAlignTop16 />
}

export const AnchorHorizontal = function () {
  return <IconAnchorHorizontal16 />
}

export const AnchorVertical = function () {
  return <IconAnchorVertical16 />
}

export const ArrowDown = function () {
  return <IconArrowDown16 />
}

export const ArrowLeftRight = function () {
  return <IconArrowLeftRight16 />
}

export const ArrowLeft = function () {
  return <IconArrowLeft16 />
}

export const ArrowRight = function () {
  return <IconArrowRight16 />
}

export const ArrowUpDown = function () {
  return <IconArrowUpDown16 />
}

export const ArrowUp = function () {
  return <IconArrowUp16 />
}

export const AutoLayoutHorizontalBottom = function () {
  return <IconAutoLayoutHorizontalBottom16 />
}

export const AutoLayoutHorizontalCenter = function () {
  return <IconAutoLayoutHorizontalCenter16 />
}

export const AutoLayoutHorizontalTop = function () {
  return <IconAutoLayoutHorizontalTop16 />
}

export const AutoLayoutVerticalCenter = function () {
  return <IconAutoLayoutVerticalCenter16 />
}

export const AutoLayoutVerticalLeft = function () {
  return <IconAutoLayoutVerticalLeft16 />
}

export const AutoLayoutVerticalRight = function () {
  return <IconAutoLayoutVerticalRight16 />
}

export const CaretDown = function () {
  return <IconCaretDown16 />
}

export const CaretLeft = function () {
  return <IconCaretLeft16 />
}

export const CaretRight = function () {
  return <IconCaretRight16 />
}

export const CaretUp = function () {
  return <IconCaretUp16 />
}

export const ChevronDown = function () {
  return <IconChevronDown16 />
}

export const ChevronUp = function () {
  return <IconChevronUp16 />
}

export const CircleHelp = function () {
  return <IconCircleHelp16 />
}

export const CircleInfo = function () {
  return <IconCircleInfo16 />
}

export const Code = function () {
  return <IconCode16 />
}

export const Connector = function () {
  return <IconConnector16 />
}

export const Hyperlink = function () {
  return <IconHyperlink16 />
}

export const LayerAnimated = function () {
  return <IconLayerAnimated16 />
}

export const LayerComponent = function () {
  return <IconLayerComponent16 />
}

export const LayerEllipse = function () {
  return <IconLayerEllipse16 />
}

export const LayerFrameCoverArt = function () {
  return <IconLayerFrameCoverArt16 />
}

export const LayerFrameScrollingHorizontal = function () {
  return <IconLayerFrameScrollingHorizontal16 />
}

export const LayerFrameScrollingVertical = function () {
  return <IconLayerFrameScrollingVertical16 />
}

export const LayerFrameScrolling = function () {
  return <IconLayerFrameScrolling16 />
}

export const LayerFrame = function () {
  return <IconLayerFrame16 />
}

export const LayerGroup = function () {
  return <IconLayerGroup16 />
}

export const LayerImage = function () {
  return <IconLayerImage16 />
}

export const LayerInstance = function () {
  return <IconLayerInstance16 />
}

export const LayerLine = function () {
  return <IconLayerLine16 />
}

export const LayerMask = function () {
  return <IconLayerMask16 />
}

export const LayerRectangle = function () {
  return <IconLayerRectangle16 />
}

export const LayerSlice = function () {
  return <IconLayerSlice16 />
}

export const LayerText = function () {
  return <IconLayerText16 />
}

export const LayerVector = function () {
  return <IconLayerVector16 />
}

export const LockLocked = function () {
  return <IconLockLocked16 />
}

export const LockUnlocked = function () {
  return <IconLockUnlocked16 />
}

export const MenuCheckmarkBreadcrumb = function () {
  return <IconMenuCheckmarkBreadcrumb16 />
}

export const MenuCheckmarkChecked = function () {
  return <IconMenuCheckmarkChecked16 />
}

export const MenuCheckmarkMixed = function () {
  return <IconMenuCheckmarkMixed16 />
}

export const MoveDown = function () {
  return <IconMoveDown16 />
}

export const MoveRight = function () {
  return <IconMoveRight16 />
}

export const OptionCheck = function () {
  return <IconOptionCheck16 />
}

export const OptionDisabled = function () {
  return <IconOptionDisabled16 />
}

export const OrientationLandscape = function () {
  return <IconOrientationLandscape16 />
}

export const OrientationPortrait = function () {
  return <IconOrientationPortrait16 />
}

export const PaddingHorizontal = function () {
  return <IconPaddingHorizontal16 />
}

export const PaddingVertical = function () {
  return <IconPaddingVertical16 />
}

export const SpaceHorizontal = function () {
  return <IconSpaceHorizontal16 />
}

export const SpaceVertical = function () {
  return <IconSpaceVertical16 />
}

export const StarFilled = function () {
  return <IconStarFilled16 />
}

export const Star = function () {
  return <IconStar16 />
}

export const Swap = function () {
  return <IconSwap16 />
}

export const Target = function () {
  return <IconTarget16 />
}

export const TextAlignCenter = function () {
  return <IconTextAlignCenter16 />
}

export const TextAlignJustified = function () {
  return <IconTextAlignJustified16 />
}

export const TextAlignLeft = function () {
  return <IconTextAlignLeft16 />
}

export const TextAlignRight = function () {
  return <IconTextAlignRight16 />
}

export const TextDecorationStrikethrough = function () {
  return <IconTextDecorationStrikethrough16 />
}

export const TextDecorationUnderline = function () {
  return <IconTextDecorationUnderline16 />
}

export const Upload = function () {
  return <IconUpload16 />
}

export const VisibilityHidden = function () {
  return <IconVisibilityHidden16 />
}

export const VisibilityVisible = function () {
  return <IconVisibilityVisible16 />
}

export const Warning = function () {
  return <IconWarning16 />
}

export const World = function () {
  return <IconWorld16 />
}
