// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconArrowDown16 = createIcon(
  'm7.99998 12.7071-.35356-.3535-3-3.00005.70711-.7071 2.14645 2.14645V2.5h1v8.2929l2.14642-2.14645.7071.7071-2.99997 3.00005-.35355.3535Z',
  { height: 16, width: 16 }
)
