// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconAnchorVertical16 = createIcon(
  'M5.50006 2.50018h5.00004v1H8.50006v9.00002h2.00004v1H5.50006v-1h2V3.50018h-2v-1Z',
  { height: 16, width: 16 }
)
