// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconArrowUp16 = createIcon(
  'm7.99998 2.29289-.35356.35356-3 3 .70711.7071 2.14645-2.14644V12.5h1V4.20711l2.14642 2.14644.7071-.7071-2.99997-3-.35355-.35356Z',
  { height: 16, width: 16 }
)
