// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconLockLocked16 = createIcon(
  'M9.5 5.5V7h-3V5.5C6.5 4.67157 7.17157 4 8 4s1.5.67157 1.5 1.5ZM5.5 7V5.5C5.5 4.11929 6.61929 3 8 3s2.5 1.11929 2.5 2.5V7h.5c.2761 0 .5.22386.5.5v5c0 .2761-.2239.5-.5.5H5c-.27614 0-.5-.2239-.5-.5v-5c0-.27614.22386-.5.5-.5h.5Z',
  { height: 16, width: 16 }
)
