// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconAlignBottom16 = createIcon(
  'M8.35355 12.3536 8 12.7071l-.35355-.3535-3-3.00005.7071-.7071L7.5 10.7929V3h1v7.7929l2.1464-2.14645.7072.7071-3.00005 3.00005ZM15 14v1H1v-1h14Z',
  { height: 16, width: 16 }
)
