// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconTextDecorationUnderline16 = createIcon(
  'M5.5 8.5V3h-1v5.5C4.5 10.433 6.067 12 8 12s3.5-1.567 3.5-3.5V3h-1v5.5C10.5 9.88071 9.38071 11 8 11S5.5 9.88071 5.5 8.5ZM2 14v1h12v-1H2Z',
  { height: 16, width: 16 }
)
