// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconTextAlignJustified16 = createIcon(
  'M1 3h14v1H1V3zm0 4h14v1H1V7zm14 4H1v1h14v-1z',
  { height: 16, width: 16 }
)
