// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconPaddingHorizontal16 = createIcon(
  'M3 3v10h1V3H3zm2 10V3h1v10H5zm5-10v10h1V3h-1zm2 0v10h1V3h-1z',
  { height: 16, width: 16 }
)
