// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconMoveRight16 = createIcon(
  'M4.5 4h-1v8h1V8.50004h7.2929L9.64645 10.6465l.70715.7071 3-3.00001.3535-.35355-.3535-.35356-3-3-.70715.70711 2.14645 2.14645H4.5V4Z',
  { height: 16, width: 16 }
)
