// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconAutoLayoutHorizontalCenter16 = createIcon(
  'M7 13h2V3H7v10zm-4-1h2V4H3v8zm10-1h-2V5h2v6z',
  { height: 16, width: 16 }
)
