/* eslint-disable no-console */
import fs from 'fs-extra'
import globby from 'globby'
import ts from 'typescript'

async function main(): Promise<void> {
  const args = process.argv.slice(2) // Glob patterns are passed in as CLI arguments
  const filePaths = await globby([
    ...args,
    '!src/index.ts',
    '!**/*.d.ts',
    '!**/*.stories.tsx'
  ])
  const result: Array<string> = [] // Array of export declaration strings
  const usedExportNames: Record<string, true> = {} // Track the names of exports that were already used
  const program = ts.createProgram(filePaths, { allowJs: true })
  for (const filePath of filePaths) {
    const sourceFile = program.getSourceFile(filePath)
    if (typeof sourceFile === 'undefined') {
      console.error(`\`sourceFile\` is \`undefined\`: ${filePath}`)
      process.exit(1)
    }
    const exportNames: Array<string> = []
    function addExport(exportName: string) {
      if (usedExportNames[exportName] === true) {
        console.error(`Export name clash \`${exportName}\`: ${filePath}`)
        process.exit(1)
      }
      usedExportNames[exportName] = true
      exportNames.push(exportName)
    }
    ts.forEachChild(sourceFile, function (node: ts.Node): void {
      if (
        ts.isTypeAliasDeclaration(node) ||
        ts.isInterfaceDeclaration(node) ||
        ts.isFunctionDeclaration(node)
      ) {
        if (
          typeof node.modifiers !== 'undefined' &&
          node.modifiers[0].kind === ts.SyntaxKind.ExportKeyword &&
          typeof node.name !== 'undefined'
        ) {
          if (
            node.modifiers.length > 1 &&
            node.modifiers[1].kind === ts.SyntaxKind.DefaultKeyword
          ) {
            console.error(`Use of \`default\` export detected: ${filePath}`)
            process.exit(1)
          }
          addExport(node.name.text)
        }
      }
      if (ts.isVariableStatement(node)) {
        if (
          typeof node.modifiers !== 'undefined' &&
          node.modifiers[0].kind === ts.SyntaxKind.ExportKeyword
        ) {
          const identifier = node.declarationList.declarations[0].name
          if (ts.isIdentifier(identifier)) {
            addExport(identifier.text)
          }
        }
      }
    })
    console.log(filePath)
    const normalizedFilePath = filePath
      .replace(/^(?:\.\/)?src\//, './') // Relace `./src/` with `./`
      .replace(/\.tsx?/, '.js')
    const exportDeclaration = `export { ${exportNames
      .sort()
      .join(', ')} } from '${normalizedFilePath}'`
    result.push(exportDeclaration)
  }
  await fs.outputFile(
    'src/index.ts',
    `// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n${result.join(
      '\n'
    )}`
  )
}
main()
