// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { IconClose24 } from '../icon-close-24.js'
import { IconEllipsis24 } from '../icon-ellipsis-24.js'
import { IconMinus24 } from '../icon-minus-24.js'
import { IconPlus24 } from '../icon-plus-24.js'
import { IconSearch24 } from '../icon-search-24.js'
import { IconTextAlignCenter24 } from '../icon-text-align-center-24.js'
import { IconTextAlignLeft24 } from '../icon-text-align-left-24.js'
import { IconTextAlignRight24 } from '../icon-text-align-right-24.js'

export default {
  parameters: {
    fixedWidth: false
  },
  title: 'Icons/Size 24'
}

export const Close = function () {
  return <IconClose24 />
}

export const Ellipsis = function () {
  return <IconEllipsis24 />
}

export const Minus = function () {
  return <IconMinus24 />
}

export const Plus = function () {
  return <IconPlus24 />
}

export const Search = function () {
  return <IconSearch24 />
}

export const TextAlignCenter = function () {
  return <IconTextAlignCenter24 />
}

export const TextAlignLeft = function () {
  return <IconTextAlignLeft24 />
}

export const TextAlignRight = function () {
  return <IconTextAlignRight24 />
}
