// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { h } from 'preact'

import { IconActionBackSmall24 } from '../icon-action-back-small-24.js'
import { IconActionChangeSmall24 } from '../icon-action-change-small-24.js'
import { IconActionConditionalSmall24 } from '../icon-action-conditional-small-24.js'
import { IconActionGoSmall24 } from '../icon-action-go-small-24.js'
import { IconActionNextSmall24 } from '../icon-action-next-small-24.js'
import { IconActionOverlayCloseSmall24 } from '../icon-action-overlay-close-small-24.js'
import { IconActionOverlayOpenSmall24 } from '../icon-action-overlay-open-small-24.js'
import { IconActionOverlaySwapSmall24 } from '../icon-action-overlay-swap-small-24.js'
import { IconActionScrollSmall24 } from '../icon-action-scroll-small-24.js'
import { IconActionTimeJumpSmall24 } from '../icon-action-time-jump-small-24.js'
import { IconActionTimeSetSmall24 } from '../icon-action-time-set-small-24.js'
import { IconActionVideoEndsSmall24 } from '../icon-action-video-ends-small-24.js'
import { IconActionVideoHitsSmall24 } from '../icon-action-video-hits-small-24.js'
import { IconActions24 } from '../icon-actions-24.js'
import { IconActionsSmall24 } from '../icon-actions-small-24.js'
import { IconActualSizeSmall24 } from '../icon-actual-size-small-24.js'
import { IconAdjust24 } from '../icon-adjust-24.js'
import { IconAdjustSmall24 } from '../icon-adjust-small-24.js'
import { IconAi24 } from '../icon-ai-24.js'
import { IconAiOutline24 } from '../icon-ai-outline-24.js'
import { IconAiOutlineSmall24 } from '../icon-ai-outline-small-24.js'
import { IconAiSearch24 } from '../icon-ai-search-24.js'
import { IconAiSearchSmall24 } from '../icon-ai-search-small-24.js'
import { IconAiSmall24 } from '../icon-ai-small-24.js'
import { IconAiSort24 } from '../icon-ai-sort-24.js'
import { IconAiSortSmall24 } from '../icon-ai-sort-small-24.js'
import { IconAiSummarize24 } from '../icon-ai-summarize-24.js'
import { IconAiSummarizeSmall24 } from '../icon-ai-summarize-small-24.js'
import { IconAllSmall24 } from '../icon-all-small-24.js'
import { IconAngle24 } from '../icon-angle-24.js'
import { IconAnimate24 } from '../icon-animate-24.js'
import { IconAnimateSmall24 } from '../icon-animate-small-24.js'
import { IconAnnotate24 } from '../icon-annotate-24.js'
import { IconAnnotateSmall24 } from '../icon-annotate-small-24.js'
import { IconApprovedCheckmark24 } from '../icon-approved-checkmark-24.js'
import { IconArc24 } from '../icon-arc-24.js'
import { IconArrow24 } from '../icon-arrow-24.js'
import { IconArrowSmall24 } from '../icon-arrow-small-24.js'
import { IconAttentionSmall24 } from '../icon-attention-small-24.js'
import { IconAudio24 } from '../icon-audio-24.js'
import { IconAudioSmall24 } from '../icon-audio-small-24.js'
import { IconAuthorSmall24 } from '../icon-author-small-24.js'
import { IconAutoLayoutAbsolutePosition24 } from '../icon-auto-layout-absolute-position-24.js'
import { IconAutoLayoutAddHorizontal24 } from '../icon-auto-layout-add-horizontal-24.js'
import { IconAutoLayoutAddVertical24 } from '../icon-auto-layout-add-vertical-24.js'
import { IconAutoLayoutAddWrap24 } from '../icon-auto-layout-add-wrap-24.js'
import { IconAutoLayoutConstrainHoriz24 } from '../icon-auto-layout-constrain-horiz-24.js'
import { IconAutoLayoutConstrainVert24 } from '../icon-auto-layout-constrain-vert-24.js'
import { IconAutoLayoutHeightFill24 } from '../icon-auto-layout-height-fill-24.js'
import { IconAutoLayoutHeightHug24 } from '../icon-auto-layout-height-hug-24.js'
import { IconAutoLayoutHeightMax24 } from '../icon-auto-layout-height-max-24.js'
import { IconAutoLayoutHeightMin24 } from '../icon-auto-layout-height-min-24.js'
import { IconAutoLayoutHeightMinmax24 } from '../icon-auto-layout-height-minmax-24.js'
import { IconAutoLayoutHorizontal24 } from '../icon-auto-layout-horizontal-24.js'
import { IconAutoLayoutLayoutHorizontal24 } from '../icon-auto-layout-layout-horizontal-24.js'
import { IconAutoLayoutLayoutVertical24 } from '../icon-auto-layout-layout-vertical-24.js'
import { IconAutoLayoutLayoutVerticalUp24 } from '../icon-auto-layout-layout-vertical-up-24.js'
import { IconAutoLayoutLayoutWrap24 } from '../icon-auto-layout-layout-wrap-24.js'
import { IconAutoLayoutPaddingAll24 } from '../icon-auto-layout-padding-all-24.js'
import { IconAutoLayoutPaddingBottom24 } from '../icon-auto-layout-padding-bottom-24.js'
import { IconAutoLayoutPaddingHorizontal24 } from '../icon-auto-layout-padding-horizontal-24.js'
import { IconAutoLayoutPaddingLeft24 } from '../icon-auto-layout-padding-left-24.js'
import { IconAutoLayoutPaddingRight24 } from '../icon-auto-layout-padding-right-24.js'
import { IconAutoLayoutPaddingSides24 } from '../icon-auto-layout-padding-sides-24.js'
import { IconAutoLayoutPaddingTop24 } from '../icon-auto-layout-padding-top-24.js'
import { IconAutoLayoutPaddingVertical24 } from '../icon-auto-layout-padding-vertical-24.js'
import { IconAutoLayoutSpacingHorizontal24 } from '../icon-auto-layout-spacing-horizontal-24.js'
import { IconAutoLayoutSpacingVertical24 } from '../icon-auto-layout-spacing-vertical-24.js'
import { IconAutoLayoutVertical24 } from '../icon-auto-layout-vertical-24.js'
import { IconAutoLayoutWidthFill24 } from '../icon-auto-layout-width-fill-24.js'
import { IconAutoLayoutWidthHug24 } from '../icon-auto-layout-width-hug-24.js'
import { IconAutoLayoutWidthMax24 } from '../icon-auto-layout-width-max-24.js'
import { IconAutoLayoutWidthMin24 } from '../icon-auto-layout-width-min-24.js'
import { IconAutoLayoutWidthMinmax24 } from '../icon-auto-layout-width-minmax-24.js'
import { IconAutoLayoutWrap24 } from '../icon-auto-layout-wrap-24.js'
import { IconAutoRenameSmall24 } from '../icon-auto-rename-small-24.js'
import { IconBackgroundBlurSmall24 } from '../icon-background-blur-small-24.js'
import { IconBackwardSmall24 } from '../icon-backward-small-24.js'
import { IconBlendModeActiveSmall24 } from '../icon-blend-mode-active-small-24.js'
import { IconBlendModeSmall24 } from '../icon-blend-mode-small-24.js'
import { IconBold24 } from '../icon-bold-24.js'
import { IconBoolean24 } from '../icon-boolean-24.js'
import { IconBooleanExclude24 } from '../icon-boolean-exclude-24.js'
import { IconBooleanExcludeSmall24 } from '../icon-boolean-exclude-small-24.js'
import { IconBooleanIntersect24 } from '../icon-boolean-intersect-24.js'
import { IconBooleanIntersectSmall24 } from '../icon-boolean-intersect-small-24.js'
import { IconBooleanSmall24 } from '../icon-boolean-small-24.js'
import { IconBooleanSubtract24 } from '../icon-boolean-subtract-24.js'
import { IconBooleanSubtractSmall24 } from '../icon-boolean-subtract-small-24.js'
import { IconBooleanUnion24 } from '../icon-boolean-union-24.js'
import { IconBooleanUnionSmall24 } from '../icon-boolean-union-small-24.js'
import { IconBorderBottomLeftRightSmall24 } from '../icon-border-bottom-left-right-small-24.js'
import { IconBorderBottomLeftSmall24 } from '../icon-border-bottom-left-small-24.js'
import { IconBorderBottomRightSmall24 } from '../icon-border-bottom-right-small-24.js'
import { IconBorderBottomSmall24 } from '../icon-border-bottom-small-24.js'
import { IconBorderExtraLargeSmall24 } from '../icon-border-extra-large-small-24.js'
import { IconBorderLargeSmall24 } from '../icon-border-large-small-24.js'
import { IconBorderLeftRightSmall24 } from '../icon-border-left-right-small-24.js'
import { IconBorderLeftSmall24 } from '../icon-border-left-small-24.js'
import { IconBorderMediumSmall24 } from '../icon-border-medium-small-24.js'
import { IconBorderNoneSmall24 } from '../icon-border-none-small-24.js'
import { IconBorderRightSmall24 } from '../icon-border-right-small-24.js'
import { IconBorderSmall24 } from '../icon-border-small-24.js'
import { IconBorderSmallSmall24 } from '../icon-border-small-small-24.js'
import { IconBorderTopBottomSmall24 } from '../icon-border-top-bottom-small-24.js'
import { IconBorderTopLeftBottomSmall24 } from '../icon-border-top-left-bottom-small-24.js'
import { IconBorderTopLeftRightSmall24 } from '../icon-border-top-left-right-small-24.js'
import { IconBorderTopLeftSmall24 } from '../icon-border-top-left-small-24.js'
import { IconBorderTopRightBottomSmall24 } from '../icon-border-top-right-bottom-small-24.js'
import { IconBorderTopRightSmall24 } from '../icon-border-top-right-small-24.js'
import { IconBorderTopSmall24 } from '../icon-border-top-small-24.js'
import { IconBranchSmall24 } from '../icon-branch-small-24.js'
import { IconBulbOff24 } from '../icon-bulb-off-24.js'
import { IconBulbOn24 } from '../icon-bulb-on-24.js'
import { IconCameraOffSmall24 } from '../icon-camera-off-small-24.js'
import { IconCameraSmall24 } from '../icon-camera-small-24.js'
import { IconCheck24 } from '../icon-check-24.js'
import { IconCheckLarge24 } from '../icon-check-large-24.js'
import { IconChevronDown24 } from '../icon-chevron-down-24.js'
import { IconChevronDownLarge24 } from '../icon-chevron-down-large-24.js'
import { IconChevronRight24 } from '../icon-chevron-right-24.js'
import { IconChevronRightLarge24 } from '../icon-chevron-right-large-24.js'
import { IconChevronUp24 } from '../icon-chevron-up-24.js'
import { IconChild24 } from '../icon-child-24.js'
import { IconClipboardSmall24 } from '../icon-clipboard-small-24.js'
import { IconClose24 } from '../icon-close-24.js'
import { IconCloseFilled24 } from '../icon-close-filled-24.js'
import { IconCloseSmall24 } from '../icon-close-small-24.js'
import { IconClosedCaptioningSmall24 } from '../icon-closed-captioning-small-24.js'
import { IconCloudOffline24 } from '../icon-cloud-offline-24.js'
import { IconCloudOfflineSmall24 } from '../icon-cloud-offline-small-24.js'
import { IconCodeBlock24 } from '../icon-code-block-24.js'
import { IconCodeBlockSmall24 } from '../icon-code-block-small-24.js'
import { IconCodeSnippet24 } from '../icon-code-snippet-24.js'
import { IconCollapse24 } from '../icon-collapse-24.js'
import { IconCollapseLayersSmall24 } from '../icon-collapse-layers-small-24.js'
import { IconCommand24 } from '../icon-command-24.js'
import { IconComment24 } from '../icon-comment-24.js'
import { IconCommentNew24 } from '../icon-comment-new-24.js'
import { IconCommentNewSmall24 } from '../icon-comment-new-small-24.js'
import { IconCommentSmall24 } from '../icon-comment-small-24.js'
import { IconCommunity24 } from '../icon-community-24.js'
import { IconCompanySmall24 } from '../icon-company-small-24.js'
import { IconComponent24 } from '../icon-component-24.js'
import { IconComponentSet24 } from '../icon-component-set-24.js'
import { IconComponentSetSmall24 } from '../icon-component-set-small-24.js'
import { IconComponentSmall24 } from '../icon-component-small-24.js'
import { IconConstraintsSmallCenterBottom24 } from '../icon-constraints-small-center-bottom-24.js'
import { IconConstraintsSmallCenterCenter24 } from '../icon-constraints-small-center-center-24.js'
import { IconConstraintsSmallCenterScale24 } from '../icon-constraints-small-center-scale-24.js'
import { IconConstraintsSmallCenterTop24 } from '../icon-constraints-small-center-top-24.js'
import { IconConstraintsSmallCenterTopBottom24 } from '../icon-constraints-small-center-top-bottom-24.js'
import { IconConstraintsSmallLeftBottom24 } from '../icon-constraints-small-left-bottom-24.js'
import { IconConstraintsSmallLeftCenter24 } from '../icon-constraints-small-left-center-24.js'
import { IconConstraintsSmallLeftRightBottom24 } from '../icon-constraints-small-left-right-bottom-24.js'
import { IconConstraintsSmallLeftRightCenter24 } from '../icon-constraints-small-left-right-center-24.js'
import { IconConstraintsSmallLeftRightScale24 } from '../icon-constraints-small-left-right-scale-24.js'
import { IconConstraintsSmallLeftRightTop24 } from '../icon-constraints-small-left-right-top-24.js'
import { IconConstraintsSmallLeftRightTopBottom24 } from '../icon-constraints-small-left-right-top-bottom-24.js'
import { IconConstraintsSmallLeftScale24 } from '../icon-constraints-small-left-scale-24.js'
import { IconConstraintsSmallLeftTop24 } from '../icon-constraints-small-left-top-24.js'
import { IconConstraintsSmallLeftTopBottom24 } from '../icon-constraints-small-left-top-bottom-24.js'
import { IconConstraintsSmallMixedMixed24 } from '../icon-constraints-small-mixed-mixed-24.js'
import { IconConstraintsSmallRightBottom24 } from '../icon-constraints-small-right-bottom-24.js'
import { IconConstraintsSmallRightCenter24 } from '../icon-constraints-small-right-center-24.js'
import { IconConstraintsSmallRightScale24 } from '../icon-constraints-small-right-scale-24.js'
import { IconConstraintsSmallRightTop24 } from '../icon-constraints-small-right-top-24.js'
import { IconConstraintsSmallRightTopBottom24 } from '../icon-constraints-small-right-top-bottom-24.js'
import { IconConstraintsSmallScaleBottom24 } from '../icon-constraints-small-scale-bottom-24.js'
import { IconConstraintsSmallScaleCenter24 } from '../icon-constraints-small-scale-center-24.js'
import { IconConstraintsSmallScaleScale24 } from '../icon-constraints-small-scale-scale-24.js'
import { IconConstraintsSmallScaleTop24 } from '../icon-constraints-small-scale-top-24.js'
import { IconConstraintsSmallScaleTopBottom24 } from '../icon-constraints-small-scale-top-bottom-24.js'
import { IconContrastSmall24 } from '../icon-contrast-small-24.js'
import { IconConvertToRasterSmall24 } from '../icon-convert-to-raster-small-24.js'
import { IconCopySmall24 } from '../icon-copy-small-24.js'
import { IconCorners24 } from '../icon-corners-24.js'
import { IconCountPolygon24 } from '../icon-count-polygon-24.js'
import { IconCountStar24 } from '../icon-count-star-24.js'
import { IconCreateVariant24 } from '../icon-create-variant-24.js'
import { IconCreateVariantSmall24 } from '../icon-create-variant-small-24.js'
import { IconCrop24 } from '../icon-crop-24.js'
import { IconCropSmall24 } from '../icon-crop-small-24.js'
import { IconCutSmall24 } from '../icon-cut-small-24.js'
import { IconDescriptionSmall24 } from '../icon-description-small-24.js'
import { IconDesign24 } from '../icon-design-24.js'
import { IconDesignSmall24 } from '../icon-design-small-24.js'
import { IconDesktopSmall24 } from '../icon-desktop-small-24.js'
import { IconDetachSmall24 } from '../icon-detach-small-24.js'
import { IconDev24 } from '../icon-dev-24.js'
import { IconDevBrackets24 } from '../icon-dev-brackets-24.js'
import { IconDevSmall24 } from '../icon-dev-small-24.js'
import { IconDocPlus24 } from '../icon-doc-plus-24.js'
import { IconDockToSide24 } from '../icon-dock-to-side-24.js'
import { IconDropShadowBottomLeftSmall24 } from '../icon-drop-shadow-bottom-left-small-24.js'
import { IconDropShadowBottomRightSmall24 } from '../icon-drop-shadow-bottom-right-small-24.js'
import { IconDropShadowBottomSmall24 } from '../icon-drop-shadow-bottom-small-24.js'
import { IconDropShadowLeftSmall24 } from '../icon-drop-shadow-left-small-24.js'
import { IconDropShadowMaxSmall24 } from '../icon-drop-shadow-max-small-24.js'
import { IconDropShadowMidSmall24 } from '../icon-drop-shadow-mid-small-24.js'
import { IconDropShadowMinSmall24 } from '../icon-drop-shadow-min-small-24.js'
import { IconDropShadowRightSmall24 } from '../icon-drop-shadow-right-small-24.js'
import { IconDropShadowSpreadSmall24 } from '../icon-drop-shadow-spread-small-24.js'
import { IconDropShadowTopLeftSmall24 } from '../icon-drop-shadow-top-left-small-24.js'
import { IconDropShadowTopRightSmall24 } from '../icon-drop-shadow-top-right-small-24.js'
import { IconDropShadowTopSmall24 } from '../icon-drop-shadow-top-small-24.js'
import { IconDuplicateSmall24 } from '../icon-duplicate-small-24.js'
import { IconEditMode24 } from '../icon-edit-mode-24.js'
import { IconEditModeSmall24 } from '../icon-edit-mode-small-24.js'
import { IconEditObject24 } from '../icon-edit-object-24.js'
import { IconEditObjectSmall24 } from '../icon-edit-object-small-24.js'
import { IconEditTextSmall24 } from '../icon-edit-text-small-24.js'
import { IconEffectsSmall24 } from '../icon-effects-small-24.js'
import { IconEllipse24 } from '../icon-ellipse-24.js'
import { IconEllipseSmall24 } from '../icon-ellipse-small-24.js'
import { IconEmbedCodeSmall24 } from '../icon-embed-code-small-24.js'
import { IconEmoji24 } from '../icon-emoji-24.js'
import { IconEnhanceSmall24 } from '../icon-enhance-small-24.js'
import { IconExpand24 } from '../icon-expand-24.js'
import { IconExportSmall24 } from '../icon-export-small-24.js'
import { IconExposureSmall24 } from '../icon-exposure-small-24.js'
import { IconExtendImageSmall24 } from '../icon-extend-image-small-24.js'
import { IconEyeSmall24 } from '../icon-eye-small-24.js'
import { IconEyedropper24 } from '../icon-eyedropper-24.js'
import { IconEyedropperSmall24 } from '../icon-eyedropper-small-24.js'
import { IconFigjam24 } from '../icon-figjam-24.js'
import { IconFigjamPages24 } from '../icon-figjam-pages-24.js'
import { IconFigjamPagesMore24 } from '../icon-figjam-pages-more-24.js'
import { IconFigjamPagesNew24 } from '../icon-figjam-pages-new-24.js'
import { IconFigjamSmall24 } from '../icon-figjam-small-24.js'
import { IconFigma24 } from '../icon-figma-24.js'
import { IconFigmaSmall24 } from '../icon-figma-small-24.js'
import { IconFillGradientLinearSmall24 } from '../icon-fill-gradient-linear-small-24.js'
import { IconFillImageSmall24 } from '../icon-fill-image-small-24.js'
import { IconFillMixedSmall24 } from '../icon-fill-mixed-small-24.js'
import { IconFillScreenSmall24 } from '../icon-fill-screen-small-24.js'
import { IconFillSmall24 } from '../icon-fill-small-24.js'
import { IconFillSolidSmall24 } from '../icon-fill-solid-small-24.js'
import { IconFilter24 } from '../icon-filter-24.js'
import { IconFilterFilled24 } from '../icon-filter-filled-24.js'
import { IconFirstDraft24 } from '../icon-first-draft-24.js'
import { IconFirstDraftSmall24 } from '../icon-first-draft-small-24.js'
import { IconFitToHeightSmall24 } from '../icon-fit-to-height-small-24.js'
import { IconFitToScreenSmall24 } from '../icon-fit-to-screen-small-24.js'
import { IconFitToWidthSmall24 } from '../icon-fit-to-width-small-24.js'
import { IconFlatten24 } from '../icon-flatten-24.js'
import { IconFlattenSmall24 } from '../icon-flatten-small-24.js'
import { IconFlipHorizontalSmall24 } from '../icon-flip-horizontal-small-24.js'
import { IconFlipVertical24 } from '../icon-flip-vertical-24.js'
import { IconFolder24 } from '../icon-folder-24.js'
import { IconForwardSmall24 } from '../icon-forward-small-24.js'
import { IconFrame24 } from '../icon-frame-24.js'
import { IconFrameSmall24 } from '../icon-frame-small-24.js'
import { IconGenerateImageSmall24 } from '../icon-generate-image-small-24.js'
import { IconGoToMainComponentSmall24 } from '../icon-go-to-main-component-small-24.js'
import { IconGoToParent24 } from '../icon-go-to-parent-24.js'
import { IconGradientAngularSmall24 } from '../icon-gradient-angular-small-24.js'
import { IconGradientDiamondSmall24 } from '../icon-gradient-diamond-small-24.js'
import { IconGradientLinearSmall24 } from '../icon-gradient-linear-small-24.js'
import { IconGradientRadialSmall24 } from '../icon-gradient-radial-small-24.js'
import { IconGrid24 } from '../icon-grid-24.js'
import { IconGridColumn24 } from '../icon-grid-column-24.js'
import { IconGridRow24 } from '../icon-grid-row-24.js'
import { IconGridView24 } from '../icon-grid-view-24.js'
import { IconGroupSmall24 } from '../icon-group-small-24.js'
import { IconH124 } from '../icon-h1-24.js'
import { IconH224 } from '../icon-h2-24.js'
import { IconHand24 } from '../icon-hand-24.js'
import { IconHandSmall24 } from '../icon-hand-small-24.js'
import { IconHelp24 } from '../icon-help-24.js'
import { IconHelpSmall24 } from '../icon-help-small-24.js'
import { IconHiddenSmall24 } from '../icon-hidden-small-24.js'
import { IconHighlightsSmall24 } from '../icon-highlights-small-24.js'
import { IconHome24 } from '../icon-home-24.js'
import { IconHomeSmall24 } from '../icon-home-small-24.js'
import { IconImage24 } from '../icon-image-24.js'
import { IconImageSmall24 } from '../icon-image-small-24.js'
import { IconImagesSmall24 } from '../icon-images-small-24.js'
import { IconImport24 } from '../icon-import-24.js'
import { IconInDevelopment24 } from '../icon-in-development-24.js'
import { IconInDevelopmentSmall24 } from '../icon-in-development-small-24.js'
import { IconInfoSmall24 } from '../icon-info-small-24.js'
import { IconInnerShadowBottomLeftSmall24 } from '../icon-inner-shadow-bottom-left-small-24.js'
import { IconInnerShadowBottomRightSmall24 } from '../icon-inner-shadow-bottom-right-small-24.js'
import { IconInnerShadowBottomSmall24 } from '../icon-inner-shadow-bottom-small-24.js'
import { IconInnerShadowLeftSmall24 } from '../icon-inner-shadow-left-small-24.js'
import { IconInnerShadowRightSmall24 } from '../icon-inner-shadow-right-small-24.js'
import { IconInnerShadowSpreadSmall24 } from '../icon-inner-shadow-spread-small-24.js'
import { IconInnerShadowTopLeftSmall24 } from '../icon-inner-shadow-top-left-small-24.js'
import { IconInnerShadowTopRightSmall24 } from '../icon-inner-shadow-top-right-small-24.js'
import { IconInnerShadowTopSmall24 } from '../icon-inner-shadow-top-small-24.js'
import { IconInsert24 } from '../icon-insert-24.js'
import { IconInsertSmall24 } from '../icon-insert-small-24.js'
import { IconInspect24 } from '../icon-inspect-24.js'
import { IconInspectSmall24 } from '../icon-inspect-small-24.js'
import { IconInstanceSmall24 } from '../icon-instance-small-24.js'
import { IconInstanceSwapSmall24 } from '../icon-instance-swap-small-24.js'
import { IconInteractionClickSmall24 } from '../icon-interaction-click-small-24.js'
import { IconInteractionDefaultSmall24 } from '../icon-interaction-default-small-24.js'
import { IconInteractionDelay24 } from '../icon-interaction-delay-24.js'
import { IconInteractionDelaySmall24 } from '../icon-interaction-delay-small-24.js'
import { IconInteractionDragSmall24 } from '../icon-interaction-drag-small-24.js'
import { IconInteractionEnterSmall24 } from '../icon-interaction-enter-small-24.js'
import { IconInteractionHoverSmall24 } from '../icon-interaction-hover-small-24.js'
import { IconInteractionKeySmall24 } from '../icon-interaction-key-small-24.js'
import { IconInteractionLeaveSmall24 } from '../icon-interaction-leave-small-24.js'
import { IconInteractionMouseDownSmall24 } from '../icon-interaction-mouse-down-small-24.js'
import { IconInteractionMouseUpSmall24 } from '../icon-interaction-mouse-up-small-24.js'
import { IconInteractionPressSmall24 } from '../icon-interaction-press-small-24.js'
import { IconInteractive24 } from '../icon-interactive-24.js'
import { IconInteractiveSmall24 } from '../icon-interactive-small-24.js'
import { IconItalic24 } from '../icon-italic-24.js'
import { IconKeySmall24 } from '../icon-key-small-24.js'
import { IconKeyboardShortcutsSmall24 } from '../icon-keyboard-shortcuts-small-24.js'
import { IconLandscape24 } from '../icon-landscape-24.js'
import { IconLanguageSmall24 } from '../icon-language-small-24.js'
import { IconLayerBlurMediumSmall24 } from '../icon-layer-blur-medium-small-24.js'
import { IconLayerBlurSmall24 } from '../icon-layer-blur-small-24.js'
import { IconLayerBlurSmallSmall24 } from '../icon-layer-blur-small-small-24.js'
import { IconLayoutAlignBottom24 } from '../icon-layout-align-bottom-24.js'
import { IconLayoutAlignBottomGroup24 } from '../icon-layout-align-bottom-group-24.js'
import { IconLayoutAlignHorizontalCenter24 } from '../icon-layout-align-horizontal-center-24.js'
import { IconLayoutAlignHorizontalCenterGroup24 } from '../icon-layout-align-horizontal-center-group-24.js'
import { IconLayoutAlignLeft24 } from '../icon-layout-align-left-24.js'
import { IconLayoutAlignLeftGroup24 } from '../icon-layout-align-left-group-24.js'
import { IconLayoutAlignRight24 } from '../icon-layout-align-right-24.js'
import { IconLayoutAlignRightGroup24 } from '../icon-layout-align-right-group-24.js'
import { IconLayoutAlignTop24 } from '../icon-layout-align-top-24.js'
import { IconLayoutAlignTopGroup24 } from '../icon-layout-align-top-group-24.js'
import { IconLayoutAlignVerticalCenter24 } from '../icon-layout-align-vertical-center-24.js'
import { IconLayoutAlignVerticalCenterGroup24 } from '../icon-layout-align-vertical-center-group-24.js'
import { IconLayoutDistributeHorizontalSpacing24 } from '../icon-layout-distribute-horizontal-spacing-24.js'
import { IconLayoutDistributeVerticalSpacing24 } from '../icon-layout-distribute-vertical-spacing-24.js'
import { IconLayoutGridColumns24 } from '../icon-layout-grid-columns-24.js'
import { IconLayoutGridRows24 } from '../icon-layout-grid-rows-24.js'
import { IconLayoutGridUniform24 } from '../icon-layout-grid-uniform-24.js'
import { IconLayoutOverlayBottom24 } from '../icon-layout-overlay-bottom-24.js'
import { IconLayoutOverlayCenter24 } from '../icon-layout-overlay-center-24.js'
import { IconLayoutOverlayLeft24 } from '../icon-layout-overlay-left-24.js'
import { IconLayoutTidyUpGrid24 } from '../icon-layout-tidy-up-grid-24.js'
import { IconLayoutTidyUpListHorizontal24 } from '../icon-layout-tidy-up-list-horizontal-24.js'
import { IconLayoutTidyUpListVertical24 } from '../icon-layout-tidy-up-list-vertical-24.js'
import { IconLeadingTrim24 } from '../icon-leading-trim-24.js'
import { IconLibrary24 } from '../icon-library-24.js'
import { IconLine24 } from '../icon-line-24.js'
import { IconLineSmall24 } from '../icon-line-small-24.js'
import { IconLink24 } from '../icon-link-24.js'
import { IconLinkBroken24 } from '../icon-link-broken-24.js'
import { IconLinkConnected24 } from '../icon-link-connected-24.js'
import { IconLinkSmall24 } from '../icon-link-small-24.js'
import { IconLinkedobjectSmall24 } from '../icon-linkedobject-small-24.js'
import { IconListView24 } from '../icon-list-view-24.js'
import { IconLoadingSmall24 } from '../icon-loading-small-24.js'
import { IconLockLocked24 } from '../icon-lock-locked-24.js'
import { IconLockOpen24 } from '../icon-lock-open-24.js'
import { IconLockOpenSmall24 } from '../icon-lock-open-small-24.js'
import { IconLockSmall24 } from '../icon-lock-small-24.js'
import { IconLoopOffSmall24 } from '../icon-loop-off-small-24.js'
import { IconLoopSmall24 } from '../icon-loop-small-24.js'
import { IconLowercase24 } from '../icon-lowercase-24.js'
import { IconMagicNoodle24 } from '../icon-magic-noodle-24.js'
import { IconMagicNoodleSmall24 } from '../icon-magic-noodle-small-24.js'
import { IconMail24 } from '../icon-mail-24.js'
import { IconMask24 } from '../icon-mask-24.js'
import { IconMaskSmall24 } from '../icon-mask-small-24.js'
import { IconMeasure24 } from '../icon-measure-24.js'
import { IconMeasureSmall24 } from '../icon-measure-small-24.js'
import { IconMention24 } from '../icon-mention-24.js'
import { IconMicMute24 } from '../icon-mic-mute-24.js'
import { IconMicMuteSmall24 } from '../icon-mic-mute-small-24.js'
import { IconMicrophone24 } from '../icon-microphone-24.js'
import { IconMicrophoneSmall24 } from '../icon-microphone-small-24.js'
import { IconMinus24 } from '../icon-minus-24.js'
import { IconMinusSmall24 } from '../icon-minus-small-24.js'
import { IconMissingFont24 } from '../icon-missing-font-24.js'
import { IconMissingFontSmall24 } from '../icon-missing-font-small-24.js'
import { IconMobileSmall24 } from '../icon-mobile-small-24.js'
import { IconMonospaceLowercaseNumber24 } from '../icon-monospace-lowercase-number-24.js'
import { IconMonospaceUppercaseNumber24 } from '../icon-monospace-uppercase-number-24.js'
import { IconMoonSmall24 } from '../icon-moon-small-24.js'
import { IconMore24 } from '../icon-more-24.js'
import { IconMove24 } from '../icon-move-24.js'
import { IconMoveSmall24 } from '../icon-move-small-24.js'
import { IconMultiEdit24 } from '../icon-multi-edit-24.js'
import { IconMultiEditSmall24 } from '../icon-multi-edit-small-24.js'
import { IconMultiEditTextSmall24 } from '../icon-multi-edit-text-small-24.js'
import { IconMultipleComponentsSmall24 } from '../icon-multiple-components-small-24.js'
import { IconNavigateBack24 } from '../icon-navigate-back-24.js'
import { IconNavigateForward24 } from '../icon-navigate-forward-24.js'
import { IconNewTab24 } from '../icon-new-tab-24.js'
import { IconNoTrim24 } from '../icon-no-trim-24.js'
import { IconNoodle24 } from '../icon-noodle-24.js'
import { IconNormalNumber24 } from '../icon-normal-number-24.js'
import { IconNotesOnRectangle24 } from '../icon-notes-on-rectangle-24.js'
import { IconNotesOnRectangleSmall24 } from '../icon-notes-on-rectangle-small-24.js'
import { IconNotificationBellBadgedSmall24 } from '../icon-notification-bell-badged-small-24.js'
import { IconNotificationBellFilledBadgedSmall24 } from '../icon-notification-bell-filled-badged-small-24.js'
import { IconNotificationBellFilledSmall24 } from '../icon-notification-bell-filled-small-24.js'
import { IconNotificationBellSmall24 } from '../icon-notification-bell-small-24.js'
import { IconNumberList24 } from '../icon-number-list-24.js'
import { IconNumberSmall24 } from '../icon-number-small-24.js'
import { IconOpacity24 } from '../icon-opacity-24.js'
import { IconOpenSession24 } from '../icon-open-session-24.js'
import { IconOpenSessionSmall24 } from '../icon-open-session-small-24.js'
import { IconOutlineStrokeSmall24 } from '../icon-outline-stroke-small-24.js'
import { IconOverflowClipSmall24 } from '../icon-overflow-clip-small-24.js'
import { IconOverflowDisplaySmall24 } from '../icon-overflow-display-small-24.js'
import { IconPage24 } from '../icon-page-24.js'
import { IconPasswordSmall24 } from '../icon-password-small-24.js'
import { IconPause24 } from '../icon-pause-24.js'
import { IconPauseSmall24 } from '../icon-pause-small-24.js'
import { IconPen24 } from '../icon-pen-24.js'
import { IconPenSmall24 } from '../icon-pen-small-24.js'
import { IconPencil24 } from '../icon-pencil-24.js'
import { IconPencilSmall24 } from '../icon-pencil-small-24.js'
import { IconPendingInvite24 } from '../icon-pending-invite-24.js'
import { IconPeopleSmall24 } from '../icon-people-small-24.js'
import { IconPersonSmall24 } from '../icon-person-small-24.js'
import { IconPhone24 } from '../icon-phone-24.js'
import { IconPlaceholder24 } from '../icon-placeholder-24.js'
import { IconPlaceholderSmall24 } from '../icon-placeholder-small-24.js'
import { IconPlay24 } from '../icon-play-24.js'
import { IconPlayOnRectangle24 } from '../icon-play-on-rectangle-24.js'
import { IconPlayPauseSmall24 } from '../icon-play-pause-small-24.js'
import { IconPlaySmall24 } from '../icon-play-small-24.js'
import { IconPlugin24 } from '../icon-plugin-24.js'
import { IconPluginSmall24 } from '../icon-plugin-small-24.js'
import { IconPlus24 } from '../icon-plus-24.js'
import { IconPlusSmall24 } from '../icon-plus-small-24.js'
import { IconPoll24 } from '../icon-poll-24.js'
import { IconPollSmall24 } from '../icon-poll-small-24.js'
import { IconPolygon24 } from '../icon-polygon-24.js'
import { IconPolygonSmall24 } from '../icon-polygon-small-24.js'
import { IconPortrait24 } from '../icon-portrait-24.js'
import { IconPreviewPrototype24 } from '../icon-preview-prototype-24.js'
import { IconPreviewPrototypeSmall24 } from '../icon-preview-prototype-small-24.js'
import { IconProgressSmall24 } from '../icon-progress-small-24.js'
import { IconPropHeight24 } from '../icon-prop-height-24.js'
import { IconPropText24 } from '../icon-prop-text-24.js'
import { IconPropWidth24 } from '../icon-prop-width-24.js'
import { IconProportionalLowercaseNumber24 } from '../icon-proportional-lowercase-number-24.js'
import { IconProportionalUppercaseNumber24 } from '../icon-proportional-uppercase-number-24.js'
import { IconPropsSmall24 } from '../icon-props-small-24.js'
import { IconPrototyping24 } from '../icon-prototyping-24.js'
import { IconPublicSmall24 } from '../icon-public-small-24.js'
import { IconPublishedCommunitySmall24 } from '../icon-published-community-small-24.js'
import { IconPushToMainComponentSmall24 } from '../icon-push-to-main-component-small-24.js'
import { IconQwand24 } from '../icon-qwand-24.js'
import { IconQwandSmall24 } from '../icon-qwand-small-24.js'
import { IconRadiusBottomLeft24 } from '../icon-radius-bottom-left-24.js'
import { IconRadiusBottomRight24 } from '../icon-radius-bottom-right-24.js'
import { IconRadiusTopLeft24 } from '../icon-radius-top-left-24.js'
import { IconRadiusTopRight24 } from '../icon-radius-top-right-24.js'
import { IconReadyForDev24 } from '../icon-ready-for-dev-24.js'
import { IconReadyForDevSmall24 } from '../icon-ready-for-dev-small-24.js'
import { IconRecentSmall24 } from '../icon-recent-small-24.js'
import { IconRectangle24 } from '../icon-rectangle-24.js'
import { IconRectangleSmall24 } from '../icon-rectangle-small-24.js'
import { IconReleaseNotesSmall24 } from '../icon-release-notes-small-24.js'
import { IconRemoveBackgroundSmall24 } from '../icon-remove-background-small-24.js'
import { IconRenameSmall24 } from '../icon-rename-small-24.js'
import { IconReplaceContentSmall24 } from '../icon-replace-content-small-24.js'
import { IconReplaceSmall24 } from '../icon-replace-small-24.js'
import { IconReplaceTextStyle24 } from '../icon-replace-text-style-24.js'
import { IconReplaceTextStyleSmall24 } from '../icon-replace-text-style-small-24.js'
import { IconResetInstance24 } from '../icon-reset-instance-24.js'
import { IconResetInstanceSmall24 } from '../icon-reset-instance-small-24.js'
import { IconResizeToFitSmall24 } from '../icon-resize-to-fit-small-24.js'
import { IconResolve24 } from '../icon-resolve-24.js'
import { IconResolveFilled24 } from '../icon-resolve-filled-24.js'
import { IconResponsiveSmall24 } from '../icon-responsive-small-24.js'
import { IconRestart24 } from '../icon-restart-24.js'
import { IconReturn24 } from '../icon-return-24.js'
import { IconRewriteSmall24 } from '../icon-rewrite-small-24.js'
import { IconRotate24 } from '../icon-rotate-24.js'
import { IconRotate180Small24 } from '../icon-rotate-180-small-24.js'
import { IconRotateCcwSmall24 } from '../icon-rotate-ccw-small-24.js'
import { IconRotation24 } from '../icon-rotation-24.js'
import { IconSaturationSmall24 } from '../icon-saturation-small-24.js'
import { IconSave24 } from '../icon-save-24.js'
import { IconSaveFilled24 } from '../icon-save-filled-24.js'
import { IconScale24 } from '../icon-scale-24.js'
import { IconScaleSmall24 } from '../icon-scale-small-24.js'
import { IconSearch24 } from '../icon-search-24.js'
import { IconSearchSmall24 } from '../icon-search-small-24.js'
import { IconSection24 } from '../icon-section-24.js'
import { IconSectionSmall24 } from '../icon-section-small-24.js'
import { IconSelect24 } from '../icon-select-24.js'
import { IconSelectMatchingSmall24 } from '../icon-select-matching-small-24.js'
import { IconSend24 } from '../icon-send-24.js'
import { IconSendBackwardSmall24 } from '../icon-send-backward-small-24.js'
import { IconSendForwardSmall24 } from '../icon-send-forward-small-24.js'
import { IconSendToBackSmall24 } from '../icon-send-to-back-small-24.js'
import { IconSendToFrontSmall24 } from '../icon-send-to-front-small-24.js'
import { IconSettings24 } from '../icon-settings-24.js'
import { IconSettingsSmall24 } from '../icon-settings-small-24.js'
import { IconShadowsSmall24 } from '../icon-shadows-small-24.js'
import { IconShapeTextSmall24 } from '../icon-shape-text-small-24.js'
import { IconShapes24 } from '../icon-shapes-24.js'
import { IconShapesSmall24 } from '../icon-shapes-small-24.js'
import { IconShortenSmall24 } from '../icon-shorten-small-24.js'
import { IconShuffleSmall24 } from '../icon-shuffle-small-24.js'
import { IconSidebarClosed24 } from '../icon-sidebar-closed-24.js'
import { IconSidebarClosedLarge24 } from '../icon-sidebar-closed-large-24.js'
import { IconSidebarOpen24 } from '../icon-sidebar-open-24.js'
import { IconSidebarsHideDefault24 } from '../icon-sidebars-hide-default-24.js'
import { IconSidebarsHideHover24 } from '../icon-sidebars-hide-hover-24.js'
import { IconSidebarsShowDefault24 } from '../icon-sidebars-show-default-24.js'
import { IconSidebarsShowHover24 } from '../icon-sidebars-show-hover-24.js'
import { IconSizeSmall24 } from '../icon-size-small-24.js'
import { IconSkipInkFalse24 } from '../icon-skip-ink-false-24.js'
import { IconSkipInkTrue24 } from '../icon-skip-ink-true-24.js'
import { IconSlice24 } from '../icon-slice-24.js'
import { IconSliceSmall24 } from '../icon-slice-small-24.js'
import { IconSlide24 } from '../icon-slide-24.js'
import { IconSlideGrid24 } from '../icon-slide-grid-24.js'
import { IconSlideSmall24 } from '../icon-slide-small-24.js'
import { IconSlides24 } from '../icon-slides-24.js'
import { IconSlidesSmall24 } from '../icon-slides-small-24.js'
import { IconSmallCaps24 } from '../icon-small-caps-24.js'
import { IconSoundOffSmall24 } from '../icon-sound-off-small-24.js'
import { IconSoundOffToggleSmall24 } from '../icon-sound-off-toggle-small-24.js'
import { IconSoundOnSmall24 } from '../icon-sound-on-small-24.js'
import { IconSpacingHorizontalSmall24 } from '../icon-spacing-horizontal-small-24.js'
import { IconSpacingVerticalSmall24 } from '../icon-spacing-vertical-small-24.js'
import { IconSpotlightSmall24 } from '../icon-spotlight-small-24.js'
import { IconSpreadSmall24 } from '../icon-spread-small-24.js'
import { IconStar24 } from '../icon-star-24.js'
import { IconStarSmall24 } from '../icon-star-small-24.js'
import { IconSticky24 } from '../icon-sticky-24.js'
import { IconStickySmall24 } from '../icon-sticky-small-24.js'
import { IconStop24 } from '../icon-stop-24.js'
import { IconStopSmall24 } from '../icon-stop-small-24.js'
import { IconStrikeThrough24 } from '../icon-strike-through-24.js'
import { IconStrokeCapNone24 } from '../icon-stroke-cap-none-24.js'
import { IconStrokeCapRound24 } from '../icon-stroke-cap-round-24.js'
import { IconStrokeCapSquare24 } from '../icon-stroke-cap-square-24.js'
import { IconStrokeCircleArrow24 } from '../icon-stroke-circle-arrow-24.js'
import { IconStrokeDash24 } from '../icon-stroke-dash-24.js'
import { IconStrokeDiamondArrow24 } from '../icon-stroke-diamond-arrow-24.js'
import { IconStrokeJoinBevel24 } from '../icon-stroke-join-bevel-24.js'
import { IconStrokeJoinRound24 } from '../icon-stroke-join-round-24.js'
import { IconStrokeJoinSquare24 } from '../icon-stroke-join-square-24.js'
import { IconStrokeLineArrow24 } from '../icon-stroke-line-arrow-24.js'
import { IconStrokeReversedTriangle24 } from '../icon-stroke-reversed-triangle-24.js'
import { IconStrokeRound24 } from '../icon-stroke-round-24.js'
import { IconStrokeSolid24 } from '../icon-stroke-solid-24.js'
import { IconStrokeSquare24 } from '../icon-stroke-square-24.js'
import { IconStrokeTriangleArrow24 } from '../icon-stroke-triangle-arrow-24.js'
import { IconStrokeWeight24 } from '../icon-stroke-weight-24.js'
import { IconStyles24 } from '../icon-styles-24.js'
import { IconSubscript24 } from '../icon-subscript-24.js'
import { IconSunSmall24 } from '../icon-sun-small-24.js'
import { IconSuperscript24 } from '../icon-superscript-24.js'
import { IconSwap24 } from '../icon-swap-24.js'
import { IconSwapSmall24 } from '../icon-swap-small-24.js'
import { IconSwatchSmall24 } from '../icon-swatch-small-24.js'
import { IconTable24 } from '../icon-table-24.js'
import { IconTableSmall24 } from '../icon-table-small-24.js'
import { IconTabletSmall24 } from '../icon-tablet-small-24.js'
import { IconTemperatureSmall24 } from '../icon-temperature-small-24.js'
import { IconTemplate24 } from '../icon-template-24.js'
import { IconTemplateSmall24 } from '../icon-template-small-24.js'
import { IconText24 } from '../icon-text-24.js'
import { IconTextAlignBottom24 } from '../icon-text-align-bottom-24.js'
import { IconTextAlignCenter24 } from '../icon-text-align-center-24.js'
import { IconTextAlignJustified24 } from '../icon-text-align-justified-24.js'
import { IconTextAlignLeft24 } from '../icon-text-align-left-24.js'
import { IconTextAlignMiddle24 } from '../icon-text-align-middle-24.js'
import { IconTextAlignRight24 } from '../icon-text-align-right-24.js'
import { IconTextAlignTop24 } from '../icon-text-align-top-24.js'
import { IconTextCapsSmall24 } from '../icon-text-caps-small-24.js'
import { IconTextFontSize24 } from '../icon-text-font-size-24.js'
import { IconTextLetterSpacing24 } from '../icon-text-letter-spacing-24.js'
import { IconTextLibrary24 } from '../icon-text-library-24.js'
import { IconTextLineHeight24 } from '../icon-text-line-height-24.js'
import { IconTextParagraphIndent124 } from '../icon-text-paragraph-indent-1-24.js'
import { IconTextParagraphIndent24 } from '../icon-text-paragraph-indent-24.js'
import { IconTextParagraphSpacing24 } from '../icon-text-paragraph-spacing-24.js'
import { IconTextResizeFixed24 } from '../icon-text-resize-fixed-24.js'
import { IconTextResizeHeight124 } from '../icon-text-resize-height-1-24.js'
import { IconTextResizeHeight24 } from '../icon-text-resize-height-24.js'
import { IconTextResizeWidth24 } from '../icon-text-resize-width-24.js'
import { IconTextSmall24 } from '../icon-text-small-24.js'
import { IconThumbDownSmall24 } from '../icon-thumb-down-small-24.js'
import { IconThumbUpSmall24 } from '../icon-thumb-up-small-24.js'
import { IconTimeSmall24 } from '../icon-time-small-24.js'
import { IconTintSmall24 } from '../icon-tint-small-24.js'
import { IconTitleCase24 } from '../icon-title-case-24.js'
import { IconTranslateSmall24 } from '../icon-translate-small-24.js'
import { IconTrash24 } from '../icon-trash-24.js'
import { IconTruncateText24 } from '../icon-truncate-text-24.js'
import { IconUiKit24 } from '../icon-ui-kit-24.js'
import { IconUnderline24 } from '../icon-underline-24.js'
import { IconUnderlineDashed24 } from '../icon-underline-dashed-24.js'
import { IconUnderlineDotted24 } from '../icon-underline-dotted-24.js'
import { IconUnderlineWave24 } from '../icon-underline-wave-24.js'
import { IconUngroupSmall24 } from '../icon-ungroup-small-24.js'
import { IconUnsavedChanges24 } from '../icon-unsaved-changes-24.js'
import { IconUnsavedChangesSmall24 } from '../icon-unsaved-changes-small-24.js'
import { IconUpdateTextStyle24 } from '../icon-update-text-style-24.js'
import { IconUpdateTextStyleSmall24 } from '../icon-update-text-style-small-24.js'
import { IconUpdates24 } from '../icon-updates-24.js'
import { IconUppercase24 } from '../icon-uppercase-24.js'
import { IconVariableColor24 } from '../icon-variable-color-24.js'
import { IconVariableColorSmall24 } from '../icon-variable-color-small-24.js'
import { IconVariableModeSmall24 } from '../icon-variable-mode-small-24.js'
import { IconVariableSmall24 } from '../icon-variable-small-24.js'
import { IconVariantSmall24 } from '../icon-variant-small-24.js'
import { IconVectorBend24 } from '../icon-vector-bend-24.js'
import { IconVectorBendSmall24 } from '../icon-vector-bend-small-24.js'
import { IconVectorPaint24 } from '../icon-vector-paint-24.js'
import { IconVectorPaintSmall24 } from '../icon-vector-paint-small-24.js'
import { IconVersionCurrent24 } from '../icon-version-current-24.js'
import { IconVersionHistorySmall24 } from '../icon-version-history-small-24.js'
import { IconVersionMerged24 } from '../icon-version-merged-24.js'
import { IconVersionNewBranch24 } from '../icon-version-new-branch-24.js'
import { IconVideoSmall24 } from '../icon-video-small-24.js'
import { IconVisualSearch24 } from '../icon-visual-search-24.js'
import { IconVisualSearchSmall24 } from '../icon-visual-search-small-24.js'
import { IconWand24 } from '../icon-wand-24.js'
import { IconWandSmall24 } from '../icon-wand-small-24.js'
import { IconWarningSmall24 } from '../icon-warning-small-24.js'
import { IconWidget24 } from '../icon-widget-24.js'
import { IconWidgetSmall24 } from '../icon-widget-small-24.js'
import { IconWrite24 } from '../icon-write-24.js'
import { IconZoomInSmall24 } from '../icon-zoom-in-small-24.js'
import { IconZoomNoSmall24 } from '../icon-zoom-no-small-24.js'
import { IconZoomOutSmall24 } from '../icon-zoom-out-small-24.js'

export default {
  parameters: {
    fixedWidth: false
  },
  title: 'Icons/Size 24'
}

export const ActionBackSmall = function () {
  return <IconActionBackSmall24 />
}

export const ActionChangeSmall = function () {
  return <IconActionChangeSmall24 />
}

export const ActionConditionalSmall = function () {
  return <IconActionConditionalSmall24 />
}

export const ActionGoSmall = function () {
  return <IconActionGoSmall24 />
}

export const ActionNextSmall = function () {
  return <IconActionNextSmall24 />
}

export const ActionOverlayCloseSmall = function () {
  return <IconActionOverlayCloseSmall24 />
}

export const ActionOverlayOpenSmall = function () {
  return <IconActionOverlayOpenSmall24 />
}

export const ActionOverlaySwapSmall = function () {
  return <IconActionOverlaySwapSmall24 />
}

export const ActionScrollSmall = function () {
  return <IconActionScrollSmall24 />
}

export const ActionTimeJumpSmall = function () {
  return <IconActionTimeJumpSmall24 />
}

export const ActionTimeSetSmall = function () {
  return <IconActionTimeSetSmall24 />
}

export const ActionVideoEndsSmall = function () {
  return <IconActionVideoEndsSmall24 />
}

export const ActionVideoHitsSmall = function () {
  return <IconActionVideoHitsSmall24 />
}

export const ActionsSmall = function () {
  return <IconActionsSmall24 />
}

export const Actions = function () {
  return <IconActions24 />
}

export const ActualSizeSmall = function () {
  return <IconActualSizeSmall24 />
}

export const AdjustSmall = function () {
  return <IconAdjustSmall24 />
}

export const Adjust = function () {
  return <IconAdjust24 />
}

export const AiOutlineSmall = function () {
  return <IconAiOutlineSmall24 />
}

export const AiOutline = function () {
  return <IconAiOutline24 />
}

export const AiSearchSmall = function () {
  return <IconAiSearchSmall24 />
}

export const AiSearch = function () {
  return <IconAiSearch24 />
}

export const AiSmall = function () {
  return <IconAiSmall24 />
}

export const AiSortSmall = function () {
  return <IconAiSortSmall24 />
}

export const AiSort = function () {
  return <IconAiSort24 />
}

export const AiSummarizeSmall = function () {
  return <IconAiSummarizeSmall24 />
}

export const AiSummarize = function () {
  return <IconAiSummarize24 />
}

export const Ai = function () {
  return <IconAi24 />
}

export const AllSmall = function () {
  return <IconAllSmall24 />
}

export const Angle = function () {
  return <IconAngle24 />
}

export const AnimateSmall = function () {
  return <IconAnimateSmall24 />
}

export const Animate = function () {
  return <IconAnimate24 />
}

export const AnnotateSmall = function () {
  return <IconAnnotateSmall24 />
}

export const Annotate = function () {
  return <IconAnnotate24 />
}

export const ApprovedCheckmark = function () {
  return <IconApprovedCheckmark24 />
}

export const Arc = function () {
  return <IconArc24 />
}

export const ArrowSmall = function () {
  return <IconArrowSmall24 />
}

export const Arrow = function () {
  return <IconArrow24 />
}

export const AttentionSmall = function () {
  return <IconAttentionSmall24 />
}

export const AudioSmall = function () {
  return <IconAudioSmall24 />
}

export const Audio = function () {
  return <IconAudio24 />
}

export const AuthorSmall = function () {
  return <IconAuthorSmall24 />
}

export const AutoLayoutAbsolutePosition = function () {
  return <IconAutoLayoutAbsolutePosition24 />
}

export const AutoLayoutAddHorizontal = function () {
  return <IconAutoLayoutAddHorizontal24 />
}

export const AutoLayoutAddVertical = function () {
  return <IconAutoLayoutAddVertical24 />
}

export const AutoLayoutAddWrap = function () {
  return <IconAutoLayoutAddWrap24 />
}

export const AutoLayoutConstrainHoriz = function () {
  return <IconAutoLayoutConstrainHoriz24 />
}

export const AutoLayoutConstrainVert = function () {
  return <IconAutoLayoutConstrainVert24 />
}

export const AutoLayoutHeightFill = function () {
  return <IconAutoLayoutHeightFill24 />
}

export const AutoLayoutHeightHug = function () {
  return <IconAutoLayoutHeightHug24 />
}

export const AutoLayoutHeightMax = function () {
  return <IconAutoLayoutHeightMax24 />
}

export const AutoLayoutHeightMin = function () {
  return <IconAutoLayoutHeightMin24 />
}

export const AutoLayoutHeightMinmax = function () {
  return <IconAutoLayoutHeightMinmax24 />
}

export const AutoLayoutHorizontal = function () {
  return <IconAutoLayoutHorizontal24 />
}

export const AutoLayoutLayoutHorizontal = function () {
  return <IconAutoLayoutLayoutHorizontal24 />
}

export const AutoLayoutLayoutVerticalUp = function () {
  return <IconAutoLayoutLayoutVerticalUp24 />
}

export const AutoLayoutLayoutVertical = function () {
  return <IconAutoLayoutLayoutVertical24 />
}

export const AutoLayoutLayoutWrap = function () {
  return <IconAutoLayoutLayoutWrap24 />
}

export const AutoLayoutPaddingAll = function () {
  return <IconAutoLayoutPaddingAll24 />
}

export const AutoLayoutPaddingBottom = function () {
  return <IconAutoLayoutPaddingBottom24 />
}

export const AutoLayoutPaddingHorizontal = function () {
  return <IconAutoLayoutPaddingHorizontal24 />
}

export const AutoLayoutPaddingLeft = function () {
  return <IconAutoLayoutPaddingLeft24 />
}

export const AutoLayoutPaddingRight = function () {
  return <IconAutoLayoutPaddingRight24 />
}

export const AutoLayoutPaddingSides = function () {
  return <IconAutoLayoutPaddingSides24 />
}

export const AutoLayoutPaddingTop = function () {
  return <IconAutoLayoutPaddingTop24 />
}

export const AutoLayoutPaddingVertical = function () {
  return <IconAutoLayoutPaddingVertical24 />
}

export const AutoLayoutSpacingHorizontal = function () {
  return <IconAutoLayoutSpacingHorizontal24 />
}

export const AutoLayoutSpacingVertical = function () {
  return <IconAutoLayoutSpacingVertical24 />
}

export const AutoLayoutVertical = function () {
  return <IconAutoLayoutVertical24 />
}

export const AutoLayoutWidthFill = function () {
  return <IconAutoLayoutWidthFill24 />
}

export const AutoLayoutWidthHug = function () {
  return <IconAutoLayoutWidthHug24 />
}

export const AutoLayoutWidthMax = function () {
  return <IconAutoLayoutWidthMax24 />
}

export const AutoLayoutWidthMin = function () {
  return <IconAutoLayoutWidthMin24 />
}

export const AutoLayoutWidthMinmax = function () {
  return <IconAutoLayoutWidthMinmax24 />
}

export const AutoLayoutWrap = function () {
  return <IconAutoLayoutWrap24 />
}

export const AutoRenameSmall = function () {
  return <IconAutoRenameSmall24 />
}

export const BackgroundBlurSmall = function () {
  return <IconBackgroundBlurSmall24 />
}

export const BackwardSmall = function () {
  return <IconBackwardSmall24 />
}

export const BlendModeActiveSmall = function () {
  return <IconBlendModeActiveSmall24 />
}

export const BlendModeSmall = function () {
  return <IconBlendModeSmall24 />
}

export const Bold = function () {
  return <IconBold24 />
}

export const BooleanExcludeSmall = function () {
  return <IconBooleanExcludeSmall24 />
}

export const BooleanExclude = function () {
  return <IconBooleanExclude24 />
}

export const BooleanIntersectSmall = function () {
  return <IconBooleanIntersectSmall24 />
}

export const BooleanIntersect = function () {
  return <IconBooleanIntersect24 />
}

export const BooleanSmall = function () {
  return <IconBooleanSmall24 />
}

export const BooleanSubtractSmall = function () {
  return <IconBooleanSubtractSmall24 />
}

export const BooleanSubtract = function () {
  return <IconBooleanSubtract24 />
}

export const BooleanUnionSmall = function () {
  return <IconBooleanUnionSmall24 />
}

export const BooleanUnion = function () {
  return <IconBooleanUnion24 />
}

export const Boolean = function () {
  return <IconBoolean24 />
}

export const BorderBottomLeftRightSmall = function () {
  return <IconBorderBottomLeftRightSmall24 />
}

export const BorderBottomLeftSmall = function () {
  return <IconBorderBottomLeftSmall24 />
}

export const BorderBottomRightSmall = function () {
  return <IconBorderBottomRightSmall24 />
}

export const BorderBottomSmall = function () {
  return <IconBorderBottomSmall24 />
}

export const BorderExtraLargeSmall = function () {
  return <IconBorderExtraLargeSmall24 />
}

export const BorderLargeSmall = function () {
  return <IconBorderLargeSmall24 />
}

export const BorderLeftRightSmall = function () {
  return <IconBorderLeftRightSmall24 />
}

export const BorderLeftSmall = function () {
  return <IconBorderLeftSmall24 />
}

export const BorderMediumSmall = function () {
  return <IconBorderMediumSmall24 />
}

export const BorderNoneSmall = function () {
  return <IconBorderNoneSmall24 />
}

export const BorderRightSmall = function () {
  return <IconBorderRightSmall24 />
}

export const BorderSmallSmall = function () {
  return <IconBorderSmallSmall24 />
}

export const BorderSmall = function () {
  return <IconBorderSmall24 />
}

export const BorderTopBottomSmall = function () {
  return <IconBorderTopBottomSmall24 />
}

export const BorderTopLeftBottomSmall = function () {
  return <IconBorderTopLeftBottomSmall24 />
}

export const BorderTopLeftRightSmall = function () {
  return <IconBorderTopLeftRightSmall24 />
}

export const BorderTopLeftSmall = function () {
  return <IconBorderTopLeftSmall24 />
}

export const BorderTopRightBottomSmall = function () {
  return <IconBorderTopRightBottomSmall24 />
}

export const BorderTopRightSmall = function () {
  return <IconBorderTopRightSmall24 />
}

export const BorderTopSmall = function () {
  return <IconBorderTopSmall24 />
}

export const BranchSmall = function () {
  return <IconBranchSmall24 />
}

export const BulbOff = function () {
  return <IconBulbOff24 />
}

export const BulbOn = function () {
  return <IconBulbOn24 />
}

export const CameraOffSmall = function () {
  return <IconCameraOffSmall24 />
}

export const CameraSmall = function () {
  return <IconCameraSmall24 />
}

export const CheckLarge = function () {
  return <IconCheckLarge24 />
}

export const Check = function () {
  return <IconCheck24 />
}

export const ChevronDownLarge = function () {
  return <IconChevronDownLarge24 />
}

export const ChevronDown = function () {
  return <IconChevronDown24 />
}

export const ChevronRightLarge = function () {
  return <IconChevronRightLarge24 />
}

export const ChevronRight = function () {
  return <IconChevronRight24 />
}

export const ChevronUp = function () {
  return <IconChevronUp24 />
}

export const Child = function () {
  return <IconChild24 />
}

export const ClipboardSmall = function () {
  return <IconClipboardSmall24 />
}

export const CloseFilled = function () {
  return <IconCloseFilled24 />
}

export const CloseSmall = function () {
  return <IconCloseSmall24 />
}

export const Close = function () {
  return <IconClose24 />
}

export const ClosedCaptioningSmall = function () {
  return <IconClosedCaptioningSmall24 />
}

export const CloudOfflineSmall = function () {
  return <IconCloudOfflineSmall24 />
}

export const CloudOffline = function () {
  return <IconCloudOffline24 />
}

export const CodeBlockSmall = function () {
  return <IconCodeBlockSmall24 />
}

export const CodeBlock = function () {
  return <IconCodeBlock24 />
}

export const CodeSnippet = function () {
  return <IconCodeSnippet24 />
}

export const CollapseLayersSmall = function () {
  return <IconCollapseLayersSmall24 />
}

export const Collapse = function () {
  return <IconCollapse24 />
}

export const Command = function () {
  return <IconCommand24 />
}

export const CommentNewSmall = function () {
  return <IconCommentNewSmall24 />
}

export const CommentNew = function () {
  return <IconCommentNew24 />
}

export const CommentSmall = function () {
  return <IconCommentSmall24 />
}

export const Comment = function () {
  return <IconComment24 />
}

export const Community = function () {
  return <IconCommunity24 />
}

export const CompanySmall = function () {
  return <IconCompanySmall24 />
}

export const ComponentSetSmall = function () {
  return <IconComponentSetSmall24 />
}

export const ComponentSet = function () {
  return <IconComponentSet24 />
}

export const ComponentSmall = function () {
  return <IconComponentSmall24 />
}

export const Component = function () {
  return <IconComponent24 />
}

export const ConstraintsSmallCenterBottom = function () {
  return <IconConstraintsSmallCenterBottom24 />
}

export const ConstraintsSmallCenterCenter = function () {
  return <IconConstraintsSmallCenterCenter24 />
}

export const ConstraintsSmallCenterScale = function () {
  return <IconConstraintsSmallCenterScale24 />
}

export const ConstraintsSmallCenterTopBottom = function () {
  return <IconConstraintsSmallCenterTopBottom24 />
}

export const ConstraintsSmallCenterTop = function () {
  return <IconConstraintsSmallCenterTop24 />
}

export const ConstraintsSmallLeftBottom = function () {
  return <IconConstraintsSmallLeftBottom24 />
}

export const ConstraintsSmallLeftCenter = function () {
  return <IconConstraintsSmallLeftCenter24 />
}

export const ConstraintsSmallLeftRightBottom = function () {
  return <IconConstraintsSmallLeftRightBottom24 />
}

export const ConstraintsSmallLeftRightCenter = function () {
  return <IconConstraintsSmallLeftRightCenter24 />
}

export const ConstraintsSmallLeftRightScale = function () {
  return <IconConstraintsSmallLeftRightScale24 />
}

export const ConstraintsSmallLeftRightTopBottom = function () {
  return <IconConstraintsSmallLeftRightTopBottom24 />
}

export const ConstraintsSmallLeftRightTop = function () {
  return <IconConstraintsSmallLeftRightTop24 />
}

export const ConstraintsSmallLeftScale = function () {
  return <IconConstraintsSmallLeftScale24 />
}

export const ConstraintsSmallLeftTopBottom = function () {
  return <IconConstraintsSmallLeftTopBottom24 />
}

export const ConstraintsSmallLeftTop = function () {
  return <IconConstraintsSmallLeftTop24 />
}

export const ConstraintsSmallMixedMixed = function () {
  return <IconConstraintsSmallMixedMixed24 />
}

export const ConstraintsSmallRightBottom = function () {
  return <IconConstraintsSmallRightBottom24 />
}

export const ConstraintsSmallRightCenter = function () {
  return <IconConstraintsSmallRightCenter24 />
}

export const ConstraintsSmallRightScale = function () {
  return <IconConstraintsSmallRightScale24 />
}

export const ConstraintsSmallRightTopBottom = function () {
  return <IconConstraintsSmallRightTopBottom24 />
}

export const ConstraintsSmallRightTop = function () {
  return <IconConstraintsSmallRightTop24 />
}

export const ConstraintsSmallScaleBottom = function () {
  return <IconConstraintsSmallScaleBottom24 />
}

export const ConstraintsSmallScaleCenter = function () {
  return <IconConstraintsSmallScaleCenter24 />
}

export const ConstraintsSmallScaleScale = function () {
  return <IconConstraintsSmallScaleScale24 />
}

export const ConstraintsSmallScaleTopBottom = function () {
  return <IconConstraintsSmallScaleTopBottom24 />
}

export const ConstraintsSmallScaleTop = function () {
  return <IconConstraintsSmallScaleTop24 />
}

export const ContrastSmall = function () {
  return <IconContrastSmall24 />
}

export const ConvertToRasterSmall = function () {
  return <IconConvertToRasterSmall24 />
}

export const CopySmall = function () {
  return <IconCopySmall24 />
}

export const Corners = function () {
  return <IconCorners24 />
}

export const CountPolygon = function () {
  return <IconCountPolygon24 />
}

export const CountStar = function () {
  return <IconCountStar24 />
}

export const CreateVariantSmall = function () {
  return <IconCreateVariantSmall24 />
}

export const CreateVariant = function () {
  return <IconCreateVariant24 />
}

export const CropSmall = function () {
  return <IconCropSmall24 />
}

export const Crop = function () {
  return <IconCrop24 />
}

export const CutSmall = function () {
  return <IconCutSmall24 />
}

export const DescriptionSmall = function () {
  return <IconDescriptionSmall24 />
}

export const DesignSmall = function () {
  return <IconDesignSmall24 />
}

export const Design = function () {
  return <IconDesign24 />
}

export const DesktopSmall = function () {
  return <IconDesktopSmall24 />
}

export const DetachSmall = function () {
  return <IconDetachSmall24 />
}

export const DevBrackets = function () {
  return <IconDevBrackets24 />
}

export const DevSmall = function () {
  return <IconDevSmall24 />
}

export const Dev = function () {
  return <IconDev24 />
}

export const DocPlus = function () {
  return <IconDocPlus24 />
}

export const DockToSide = function () {
  return <IconDockToSide24 />
}

export const DropShadowBottomLeftSmall = function () {
  return <IconDropShadowBottomLeftSmall24 />
}

export const DropShadowBottomRightSmall = function () {
  return <IconDropShadowBottomRightSmall24 />
}

export const DropShadowBottomSmall = function () {
  return <IconDropShadowBottomSmall24 />
}

export const DropShadowLeftSmall = function () {
  return <IconDropShadowLeftSmall24 />
}

export const DropShadowMaxSmall = function () {
  return <IconDropShadowMaxSmall24 />
}

export const DropShadowMidSmall = function () {
  return <IconDropShadowMidSmall24 />
}

export const DropShadowMinSmall = function () {
  return <IconDropShadowMinSmall24 />
}

export const DropShadowRightSmall = function () {
  return <IconDropShadowRightSmall24 />
}

export const DropShadowSpreadSmall = function () {
  return <IconDropShadowSpreadSmall24 />
}

export const DropShadowTopLeftSmall = function () {
  return <IconDropShadowTopLeftSmall24 />
}

export const DropShadowTopRightSmall = function () {
  return <IconDropShadowTopRightSmall24 />
}

export const DropShadowTopSmall = function () {
  return <IconDropShadowTopSmall24 />
}

export const DuplicateSmall = function () {
  return <IconDuplicateSmall24 />
}

export const EditModeSmall = function () {
  return <IconEditModeSmall24 />
}

export const EditMode = function () {
  return <IconEditMode24 />
}

export const EditObjectSmall = function () {
  return <IconEditObjectSmall24 />
}

export const EditObject = function () {
  return <IconEditObject24 />
}

export const EditTextSmall = function () {
  return <IconEditTextSmall24 />
}

export const EffectsSmall = function () {
  return <IconEffectsSmall24 />
}

export const EllipseSmall = function () {
  return <IconEllipseSmall24 />
}

export const Ellipse = function () {
  return <IconEllipse24 />
}

export const EmbedCodeSmall = function () {
  return <IconEmbedCodeSmall24 />
}

export const Emoji = function () {
  return <IconEmoji24 />
}

export const EnhanceSmall = function () {
  return <IconEnhanceSmall24 />
}

export const Expand = function () {
  return <IconExpand24 />
}

export const ExportSmall = function () {
  return <IconExportSmall24 />
}

export const ExposureSmall = function () {
  return <IconExposureSmall24 />
}

export const ExtendImageSmall = function () {
  return <IconExtendImageSmall24 />
}

export const EyeSmall = function () {
  return <IconEyeSmall24 />
}

export const EyedropperSmall = function () {
  return <IconEyedropperSmall24 />
}

export const Eyedropper = function () {
  return <IconEyedropper24 />
}

export const FigjamPagesMore = function () {
  return <IconFigjamPagesMore24 />
}

export const FigjamPagesNew = function () {
  return <IconFigjamPagesNew24 />
}

export const FigjamPages = function () {
  return <IconFigjamPages24 />
}

export const FigjamSmall = function () {
  return <IconFigjamSmall24 />
}

export const Figjam = function () {
  return <IconFigjam24 />
}

export const FigmaSmall = function () {
  return <IconFigmaSmall24 />
}

export const Figma = function () {
  return <IconFigma24 />
}

export const FillGradientLinearSmall = function () {
  return <IconFillGradientLinearSmall24 />
}

export const FillImageSmall = function () {
  return <IconFillImageSmall24 />
}

export const FillMixedSmall = function () {
  return <IconFillMixedSmall24 />
}

export const FillScreenSmall = function () {
  return <IconFillScreenSmall24 />
}

export const FillSmall = function () {
  return <IconFillSmall24 />
}

export const FillSolidSmall = function () {
  return <IconFillSolidSmall24 />
}

export const FilterFilled = function () {
  return <IconFilterFilled24 />
}

export const Filter = function () {
  return <IconFilter24 />
}

export const FirstDraftSmall = function () {
  return <IconFirstDraftSmall24 />
}

export const FirstDraft = function () {
  return <IconFirstDraft24 />
}

export const FitToHeightSmall = function () {
  return <IconFitToHeightSmall24 />
}

export const FitToScreenSmall = function () {
  return <IconFitToScreenSmall24 />
}

export const FitToWidthSmall = function () {
  return <IconFitToWidthSmall24 />
}

export const FlattenSmall = function () {
  return <IconFlattenSmall24 />
}

export const Flatten = function () {
  return <IconFlatten24 />
}

export const FlipHorizontalSmall = function () {
  return <IconFlipHorizontalSmall24 />
}

export const FlipVertical = function () {
  return <IconFlipVertical24 />
}

export const Folder = function () {
  return <IconFolder24 />
}

export const ForwardSmall = function () {
  return <IconForwardSmall24 />
}

export const FrameSmall = function () {
  return <IconFrameSmall24 />
}

export const Frame = function () {
  return <IconFrame24 />
}

export const GenerateImageSmall = function () {
  return <IconGenerateImageSmall24 />
}

export const GoToMainComponentSmall = function () {
  return <IconGoToMainComponentSmall24 />
}

export const GoToParent = function () {
  return <IconGoToParent24 />
}

export const GradientAngularSmall = function () {
  return <IconGradientAngularSmall24 />
}

export const GradientDiamondSmall = function () {
  return <IconGradientDiamondSmall24 />
}

export const GradientLinearSmall = function () {
  return <IconGradientLinearSmall24 />
}

export const GradientRadialSmall = function () {
  return <IconGradientRadialSmall24 />
}

export const GridColumn = function () {
  return <IconGridColumn24 />
}

export const GridRow = function () {
  return <IconGridRow24 />
}

export const GridView = function () {
  return <IconGridView24 />
}

export const Grid = function () {
  return <IconGrid24 />
}

export const GroupSmall = function () {
  return <IconGroupSmall24 />
}

export const H1 = function () {
  return <IconH124 />
}

export const H2 = function () {
  return <IconH224 />
}

export const HandSmall = function () {
  return <IconHandSmall24 />
}

export const Hand = function () {
  return <IconHand24 />
}

export const HelpSmall = function () {
  return <IconHelpSmall24 />
}

export const Help = function () {
  return <IconHelp24 />
}

export const HiddenSmall = function () {
  return <IconHiddenSmall24 />
}

export const HighlightsSmall = function () {
  return <IconHighlightsSmall24 />
}

export const HomeSmall = function () {
  return <IconHomeSmall24 />
}

export const Home = function () {
  return <IconHome24 />
}

export const ImageSmall = function () {
  return <IconImageSmall24 />
}

export const Image = function () {
  return <IconImage24 />
}

export const ImagesSmall = function () {
  return <IconImagesSmall24 />
}

export const Import = function () {
  return <IconImport24 />
}

export const InDevelopmentSmall = function () {
  return <IconInDevelopmentSmall24 />
}

export const InDevelopment = function () {
  return <IconInDevelopment24 />
}

export const InfoSmall = function () {
  return <IconInfoSmall24 />
}

export const InnerShadowBottomLeftSmall = function () {
  return <IconInnerShadowBottomLeftSmall24 />
}

export const InnerShadowBottomRightSmall = function () {
  return <IconInnerShadowBottomRightSmall24 />
}

export const InnerShadowBottomSmall = function () {
  return <IconInnerShadowBottomSmall24 />
}

export const InnerShadowLeftSmall = function () {
  return <IconInnerShadowLeftSmall24 />
}

export const InnerShadowRightSmall = function () {
  return <IconInnerShadowRightSmall24 />
}

export const InnerShadowSpreadSmall = function () {
  return <IconInnerShadowSpreadSmall24 />
}

export const InnerShadowTopLeftSmall = function () {
  return <IconInnerShadowTopLeftSmall24 />
}

export const InnerShadowTopRightSmall = function () {
  return <IconInnerShadowTopRightSmall24 />
}

export const InnerShadowTopSmall = function () {
  return <IconInnerShadowTopSmall24 />
}

export const InsertSmall = function () {
  return <IconInsertSmall24 />
}

export const Insert = function () {
  return <IconInsert24 />
}

export const InspectSmall = function () {
  return <IconInspectSmall24 />
}

export const Inspect = function () {
  return <IconInspect24 />
}

export const InstanceSmall = function () {
  return <IconInstanceSmall24 />
}

export const InstanceSwapSmall = function () {
  return <IconInstanceSwapSmall24 />
}

export const InteractionClickSmall = function () {
  return <IconInteractionClickSmall24 />
}

export const InteractionDefaultSmall = function () {
  return <IconInteractionDefaultSmall24 />
}

export const InteractionDelaySmall = function () {
  return <IconInteractionDelaySmall24 />
}

export const InteractionDelay = function () {
  return <IconInteractionDelay24 />
}

export const InteractionDragSmall = function () {
  return <IconInteractionDragSmall24 />
}

export const InteractionEnterSmall = function () {
  return <IconInteractionEnterSmall24 />
}

export const InteractionHoverSmall = function () {
  return <IconInteractionHoverSmall24 />
}

export const InteractionKeySmall = function () {
  return <IconInteractionKeySmall24 />
}

export const InteractionLeaveSmall = function () {
  return <IconInteractionLeaveSmall24 />
}

export const InteractionMouseDownSmall = function () {
  return <IconInteractionMouseDownSmall24 />
}

export const InteractionMouseUpSmall = function () {
  return <IconInteractionMouseUpSmall24 />
}

export const InteractionPressSmall = function () {
  return <IconInteractionPressSmall24 />
}

export const InteractiveSmall = function () {
  return <IconInteractiveSmall24 />
}

export const Interactive = function () {
  return <IconInteractive24 />
}

export const Italic = function () {
  return <IconItalic24 />
}

export const KeySmall = function () {
  return <IconKeySmall24 />
}

export const KeyboardShortcutsSmall = function () {
  return <IconKeyboardShortcutsSmall24 />
}

export const Landscape = function () {
  return <IconLandscape24 />
}

export const LanguageSmall = function () {
  return <IconLanguageSmall24 />
}

export const LayerBlurMediumSmall = function () {
  return <IconLayerBlurMediumSmall24 />
}

export const LayerBlurSmallSmall = function () {
  return <IconLayerBlurSmallSmall24 />
}

export const LayerBlurSmall = function () {
  return <IconLayerBlurSmall24 />
}

export const LayoutAlignBottomGroup = function () {
  return <IconLayoutAlignBottomGroup24 />
}

export const LayoutAlignBottom = function () {
  return <IconLayoutAlignBottom24 />
}

export const LayoutAlignHorizontalCenterGroup = function () {
  return <IconLayoutAlignHorizontalCenterGroup24 />
}

export const LayoutAlignHorizontalCenter = function () {
  return <IconLayoutAlignHorizontalCenter24 />
}

export const LayoutAlignLeftGroup = function () {
  return <IconLayoutAlignLeftGroup24 />
}

export const LayoutAlignLeft = function () {
  return <IconLayoutAlignLeft24 />
}

export const LayoutAlignRightGroup = function () {
  return <IconLayoutAlignRightGroup24 />
}

export const LayoutAlignRight = function () {
  return <IconLayoutAlignRight24 />
}

export const LayoutAlignTopGroup = function () {
  return <IconLayoutAlignTopGroup24 />
}

export const LayoutAlignTop = function () {
  return <IconLayoutAlignTop24 />
}

export const LayoutAlignVerticalCenterGroup = function () {
  return <IconLayoutAlignVerticalCenterGroup24 />
}

export const LayoutAlignVerticalCenter = function () {
  return <IconLayoutAlignVerticalCenter24 />
}

export const LayoutDistributeHorizontalSpacing = function () {
  return <IconLayoutDistributeHorizontalSpacing24 />
}

export const LayoutDistributeVerticalSpacing = function () {
  return <IconLayoutDistributeVerticalSpacing24 />
}

export const LayoutGridColumns = function () {
  return <IconLayoutGridColumns24 />
}

export const LayoutGridRows = function () {
  return <IconLayoutGridRows24 />
}

export const LayoutGridUniform = function () {
  return <IconLayoutGridUniform24 />
}

export const LayoutOverlayBottom = function () {
  return <IconLayoutOverlayBottom24 />
}

export const LayoutOverlayCenter = function () {
  return <IconLayoutOverlayCenter24 />
}

export const LayoutOverlayLeft = function () {
  return <IconLayoutOverlayLeft24 />
}

export const LayoutTidyUpGrid = function () {
  return <IconLayoutTidyUpGrid24 />
}

export const LayoutTidyUpListHorizontal = function () {
  return <IconLayoutTidyUpListHorizontal24 />
}

export const LayoutTidyUpListVertical = function () {
  return <IconLayoutTidyUpListVertical24 />
}

export const LeadingTrim = function () {
  return <IconLeadingTrim24 />
}

export const Library = function () {
  return <IconLibrary24 />
}

export const LineSmall = function () {
  return <IconLineSmall24 />
}

export const Line = function () {
  return <IconLine24 />
}

export const LinkBroken = function () {
  return <IconLinkBroken24 />
}

export const LinkConnected = function () {
  return <IconLinkConnected24 />
}

export const LinkSmall = function () {
  return <IconLinkSmall24 />
}

export const Link = function () {
  return <IconLink24 />
}

export const LinkedobjectSmall = function () {
  return <IconLinkedobjectSmall24 />
}

export const ListView = function () {
  return <IconListView24 />
}

export const LoadingSmall = function () {
  return <IconLoadingSmall24 />
}

export const LockLocked = function () {
  return <IconLockLocked24 />
}

export const LockOpenSmall = function () {
  return <IconLockOpenSmall24 />
}

export const LockOpen = function () {
  return <IconLockOpen24 />
}

export const LockSmall = function () {
  return <IconLockSmall24 />
}

export const LoopOffSmall = function () {
  return <IconLoopOffSmall24 />
}

export const LoopSmall = function () {
  return <IconLoopSmall24 />
}

export const Lowercase = function () {
  return <IconLowercase24 />
}

export const MagicNoodleSmall = function () {
  return <IconMagicNoodleSmall24 />
}

export const MagicNoodle = function () {
  return <IconMagicNoodle24 />
}

export const Mail = function () {
  return <IconMail24 />
}

export const MaskSmall = function () {
  return <IconMaskSmall24 />
}

export const Mask = function () {
  return <IconMask24 />
}

export const MeasureSmall = function () {
  return <IconMeasureSmall24 />
}

export const Measure = function () {
  return <IconMeasure24 />
}

export const Mention = function () {
  return <IconMention24 />
}

export const MicMuteSmall = function () {
  return <IconMicMuteSmall24 />
}

export const MicMute = function () {
  return <IconMicMute24 />
}

export const MicrophoneSmall = function () {
  return <IconMicrophoneSmall24 />
}

export const Microphone = function () {
  return <IconMicrophone24 />
}

export const MinusSmall = function () {
  return <IconMinusSmall24 />
}

export const Minus = function () {
  return <IconMinus24 />
}

export const MissingFontSmall = function () {
  return <IconMissingFontSmall24 />
}

export const MissingFont = function () {
  return <IconMissingFont24 />
}

export const MobileSmall = function () {
  return <IconMobileSmall24 />
}

export const MonospaceLowercaseNumber = function () {
  return <IconMonospaceLowercaseNumber24 />
}

export const MonospaceUppercaseNumber = function () {
  return <IconMonospaceUppercaseNumber24 />
}

export const MoonSmall = function () {
  return <IconMoonSmall24 />
}

export const More = function () {
  return <IconMore24 />
}

export const MoveSmall = function () {
  return <IconMoveSmall24 />
}

export const Move = function () {
  return <IconMove24 />
}

export const MultiEditSmall = function () {
  return <IconMultiEditSmall24 />
}

export const MultiEditTextSmall = function () {
  return <IconMultiEditTextSmall24 />
}

export const MultiEdit = function () {
  return <IconMultiEdit24 />
}

export const MultipleComponentsSmall = function () {
  return <IconMultipleComponentsSmall24 />
}

export const NavigateBack = function () {
  return <IconNavigateBack24 />
}

export const NavigateForward = function () {
  return <IconNavigateForward24 />
}

export const NewTab = function () {
  return <IconNewTab24 />
}

export const NoTrim = function () {
  return <IconNoTrim24 />
}

export const Noodle = function () {
  return <IconNoodle24 />
}

export const NormalNumber = function () {
  return <IconNormalNumber24 />
}

export const NotesOnRectangleSmall = function () {
  return <IconNotesOnRectangleSmall24 />
}

export const NotesOnRectangle = function () {
  return <IconNotesOnRectangle24 />
}

export const NotificationBellBadgedSmall = function () {
  return <IconNotificationBellBadgedSmall24 />
}

export const NotificationBellFilledBadgedSmall = function () {
  return <IconNotificationBellFilledBadgedSmall24 />
}

export const NotificationBellFilledSmall = function () {
  return <IconNotificationBellFilledSmall24 />
}

export const NotificationBellSmall = function () {
  return <IconNotificationBellSmall24 />
}

export const NumberList = function () {
  return <IconNumberList24 />
}

export const NumberSmall = function () {
  return <IconNumberSmall24 />
}

export const Opacity = function () {
  return <IconOpacity24 />
}

export const OpenSessionSmall = function () {
  return <IconOpenSessionSmall24 />
}

export const OpenSession = function () {
  return <IconOpenSession24 />
}

export const OutlineStrokeSmall = function () {
  return <IconOutlineStrokeSmall24 />
}

export const OverflowClipSmall = function () {
  return <IconOverflowClipSmall24 />
}

export const OverflowDisplaySmall = function () {
  return <IconOverflowDisplaySmall24 />
}

export const Page = function () {
  return <IconPage24 />
}

export const PasswordSmall = function () {
  return <IconPasswordSmall24 />
}

export const PauseSmall = function () {
  return <IconPauseSmall24 />
}

export const Pause = function () {
  return <IconPause24 />
}

export const PenSmall = function () {
  return <IconPenSmall24 />
}

export const Pen = function () {
  return <IconPen24 />
}

export const PencilSmall = function () {
  return <IconPencilSmall24 />
}

export const Pencil = function () {
  return <IconPencil24 />
}

export const PendingInvite = function () {
  return <IconPendingInvite24 />
}

export const PeopleSmall = function () {
  return <IconPeopleSmall24 />
}

export const PersonSmall = function () {
  return <IconPersonSmall24 />
}

export const Phone = function () {
  return <IconPhone24 />
}

export const PlaceholderSmall = function () {
  return <IconPlaceholderSmall24 />
}

export const Placeholder = function () {
  return <IconPlaceholder24 />
}

export const PlayOnRectangle = function () {
  return <IconPlayOnRectangle24 />
}

export const PlayPauseSmall = function () {
  return <IconPlayPauseSmall24 />
}

export const PlaySmall = function () {
  return <IconPlaySmall24 />
}

export const Play = function () {
  return <IconPlay24 />
}

export const PluginSmall = function () {
  return <IconPluginSmall24 />
}

export const Plugin = function () {
  return <IconPlugin24 />
}

export const PlusSmall = function () {
  return <IconPlusSmall24 />
}

export const Plus = function () {
  return <IconPlus24 />
}

export const PollSmall = function () {
  return <IconPollSmall24 />
}

export const Poll = function () {
  return <IconPoll24 />
}

export const PolygonSmall = function () {
  return <IconPolygonSmall24 />
}

export const Polygon = function () {
  return <IconPolygon24 />
}

export const Portrait = function () {
  return <IconPortrait24 />
}

export const PreviewPrototypeSmall = function () {
  return <IconPreviewPrototypeSmall24 />
}

export const PreviewPrototype = function () {
  return <IconPreviewPrototype24 />
}

export const ProgressSmall = function () {
  return <IconProgressSmall24 />
}

export const PropHeight = function () {
  return <IconPropHeight24 />
}

export const PropText = function () {
  return <IconPropText24 />
}

export const PropWidth = function () {
  return <IconPropWidth24 />
}

export const ProportionalLowercaseNumber = function () {
  return <IconProportionalLowercaseNumber24 />
}

export const ProportionalUppercaseNumber = function () {
  return <IconProportionalUppercaseNumber24 />
}

export const PropsSmall = function () {
  return <IconPropsSmall24 />
}

export const Prototyping = function () {
  return <IconPrototyping24 />
}

export const PublicSmall = function () {
  return <IconPublicSmall24 />
}

export const PublishedCommunitySmall = function () {
  return <IconPublishedCommunitySmall24 />
}

export const PushToMainComponentSmall = function () {
  return <IconPushToMainComponentSmall24 />
}

export const QwandSmall = function () {
  return <IconQwandSmall24 />
}

export const Qwand = function () {
  return <IconQwand24 />
}

export const RadiusBottomLeft = function () {
  return <IconRadiusBottomLeft24 />
}

export const RadiusBottomRight = function () {
  return <IconRadiusBottomRight24 />
}

export const RadiusTopLeft = function () {
  return <IconRadiusTopLeft24 />
}

export const RadiusTopRight = function () {
  return <IconRadiusTopRight24 />
}

export const ReadyForDevSmall = function () {
  return <IconReadyForDevSmall24 />
}

export const ReadyForDev = function () {
  return <IconReadyForDev24 />
}

export const RecentSmall = function () {
  return <IconRecentSmall24 />
}

export const RectangleSmall = function () {
  return <IconRectangleSmall24 />
}

export const Rectangle = function () {
  return <IconRectangle24 />
}

export const ReleaseNotesSmall = function () {
  return <IconReleaseNotesSmall24 />
}

export const RemoveBackgroundSmall = function () {
  return <IconRemoveBackgroundSmall24 />
}

export const RenameSmall = function () {
  return <IconRenameSmall24 />
}

export const ReplaceContentSmall = function () {
  return <IconReplaceContentSmall24 />
}

export const ReplaceSmall = function () {
  return <IconReplaceSmall24 />
}

export const ReplaceTextStyleSmall = function () {
  return <IconReplaceTextStyleSmall24 />
}

export const ReplaceTextStyle = function () {
  return <IconReplaceTextStyle24 />
}

export const ResetInstanceSmall = function () {
  return <IconResetInstanceSmall24 />
}

export const ResetInstance = function () {
  return <IconResetInstance24 />
}

export const ResizeToFitSmall = function () {
  return <IconResizeToFitSmall24 />
}

export const ResolveFilled = function () {
  return <IconResolveFilled24 />
}

export const Resolve = function () {
  return <IconResolve24 />
}

export const ResponsiveSmall = function () {
  return <IconResponsiveSmall24 />
}

export const Restart = function () {
  return <IconRestart24 />
}

export const Return = function () {
  return <IconReturn24 />
}

export const RewriteSmall = function () {
  return <IconRewriteSmall24 />
}

export const Rotate180Small = function () {
  return <IconRotate180Small24 />
}

export const RotateCcwSmall = function () {
  return <IconRotateCcwSmall24 />
}

export const Rotate = function () {
  return <IconRotate24 />
}

export const Rotation = function () {
  return <IconRotation24 />
}

export const SaturationSmall = function () {
  return <IconSaturationSmall24 />
}

export const SaveFilled = function () {
  return <IconSaveFilled24 />
}

export const Save = function () {
  return <IconSave24 />
}

export const ScaleSmall = function () {
  return <IconScaleSmall24 />
}

export const Scale = function () {
  return <IconScale24 />
}

export const SearchSmall = function () {
  return <IconSearchSmall24 />
}

export const Search = function () {
  return <IconSearch24 />
}

export const SectionSmall = function () {
  return <IconSectionSmall24 />
}

export const Section = function () {
  return <IconSection24 />
}

export const SelectMatchingSmall = function () {
  return <IconSelectMatchingSmall24 />
}

export const Select = function () {
  return <IconSelect24 />
}

export const SendBackwardSmall = function () {
  return <IconSendBackwardSmall24 />
}

export const SendForwardSmall = function () {
  return <IconSendForwardSmall24 />
}

export const SendToBackSmall = function () {
  return <IconSendToBackSmall24 />
}

export const SendToFrontSmall = function () {
  return <IconSendToFrontSmall24 />
}

export const Send = function () {
  return <IconSend24 />
}

export const SettingsSmall = function () {
  return <IconSettingsSmall24 />
}

export const Settings = function () {
  return <IconSettings24 />
}

export const ShadowsSmall = function () {
  return <IconShadowsSmall24 />
}

export const ShapeTextSmall = function () {
  return <IconShapeTextSmall24 />
}

export const ShapesSmall = function () {
  return <IconShapesSmall24 />
}

export const Shapes = function () {
  return <IconShapes24 />
}

export const ShortenSmall = function () {
  return <IconShortenSmall24 />
}

export const ShuffleSmall = function () {
  return <IconShuffleSmall24 />
}

export const SidebarClosedLarge = function () {
  return <IconSidebarClosedLarge24 />
}

export const SidebarClosed = function () {
  return <IconSidebarClosed24 />
}

export const SidebarOpen = function () {
  return <IconSidebarOpen24 />
}

export const SidebarsHideDefault = function () {
  return <IconSidebarsHideDefault24 />
}

export const SidebarsHideHover = function () {
  return <IconSidebarsHideHover24 />
}

export const SidebarsShowDefault = function () {
  return <IconSidebarsShowDefault24 />
}

export const SidebarsShowHover = function () {
  return <IconSidebarsShowHover24 />
}

export const SizeSmall = function () {
  return <IconSizeSmall24 />
}

export const SkipInkFalse = function () {
  return <IconSkipInkFalse24 />
}

export const SkipInkTrue = function () {
  return <IconSkipInkTrue24 />
}

export const SliceSmall = function () {
  return <IconSliceSmall24 />
}

export const Slice = function () {
  return <IconSlice24 />
}

export const SlideGrid = function () {
  return <IconSlideGrid24 />
}

export const SlideSmall = function () {
  return <IconSlideSmall24 />
}

export const Slide = function () {
  return <IconSlide24 />
}

export const SlidesSmall = function () {
  return <IconSlidesSmall24 />
}

export const Slides = function () {
  return <IconSlides24 />
}

export const SmallCaps = function () {
  return <IconSmallCaps24 />
}

export const SoundOffSmall = function () {
  return <IconSoundOffSmall24 />
}

export const SoundOffToggleSmall = function () {
  return <IconSoundOffToggleSmall24 />
}

export const SoundOnSmall = function () {
  return <IconSoundOnSmall24 />
}

export const SpacingHorizontalSmall = function () {
  return <IconSpacingHorizontalSmall24 />
}

export const SpacingVerticalSmall = function () {
  return <IconSpacingVerticalSmall24 />
}

export const SpotlightSmall = function () {
  return <IconSpotlightSmall24 />
}

export const SpreadSmall = function () {
  return <IconSpreadSmall24 />
}

export const StarSmall = function () {
  return <IconStarSmall24 />
}

export const Star = function () {
  return <IconStar24 />
}

export const StickySmall = function () {
  return <IconStickySmall24 />
}

export const Sticky = function () {
  return <IconSticky24 />
}

export const StopSmall = function () {
  return <IconStopSmall24 />
}

export const Stop = function () {
  return <IconStop24 />
}

export const StrikeThrough = function () {
  return <IconStrikeThrough24 />
}

export const StrokeCapNone = function () {
  return <IconStrokeCapNone24 />
}

export const StrokeCapRound = function () {
  return <IconStrokeCapRound24 />
}

export const StrokeCapSquare = function () {
  return <IconStrokeCapSquare24 />
}

export const StrokeCircleArrow = function () {
  return <IconStrokeCircleArrow24 />
}

export const StrokeDash = function () {
  return <IconStrokeDash24 />
}

export const StrokeDiamondArrow = function () {
  return <IconStrokeDiamondArrow24 />
}

export const StrokeJoinBevel = function () {
  return <IconStrokeJoinBevel24 />
}

export const StrokeJoinRound = function () {
  return <IconStrokeJoinRound24 />
}

export const StrokeJoinSquare = function () {
  return <IconStrokeJoinSquare24 />
}

export const StrokeLineArrow = function () {
  return <IconStrokeLineArrow24 />
}

export const StrokeReversedTriangle = function () {
  return <IconStrokeReversedTriangle24 />
}

export const StrokeRound = function () {
  return <IconStrokeRound24 />
}

export const StrokeSolid = function () {
  return <IconStrokeSolid24 />
}

export const StrokeSquare = function () {
  return <IconStrokeSquare24 />
}

export const StrokeTriangleArrow = function () {
  return <IconStrokeTriangleArrow24 />
}

export const StrokeWeight = function () {
  return <IconStrokeWeight24 />
}

export const Styles = function () {
  return <IconStyles24 />
}

export const Subscript = function () {
  return <IconSubscript24 />
}

export const SunSmall = function () {
  return <IconSunSmall24 />
}

export const Superscript = function () {
  return <IconSuperscript24 />
}

export const SwapSmall = function () {
  return <IconSwapSmall24 />
}

export const Swap = function () {
  return <IconSwap24 />
}

export const SwatchSmall = function () {
  return <IconSwatchSmall24 />
}

export const TableSmall = function () {
  return <IconTableSmall24 />
}

export const Table = function () {
  return <IconTable24 />
}

export const TabletSmall = function () {
  return <IconTabletSmall24 />
}

export const TemperatureSmall = function () {
  return <IconTemperatureSmall24 />
}

export const TemplateSmall = function () {
  return <IconTemplateSmall24 />
}

export const Template = function () {
  return <IconTemplate24 />
}

export const TextAlignBottom = function () {
  return <IconTextAlignBottom24 />
}

export const TextAlignCenter = function () {
  return <IconTextAlignCenter24 />
}

export const TextAlignJustified = function () {
  return <IconTextAlignJustified24 />
}

export const TextAlignLeft = function () {
  return <IconTextAlignLeft24 />
}

export const TextAlignMiddle = function () {
  return <IconTextAlignMiddle24 />
}

export const TextAlignRight = function () {
  return <IconTextAlignRight24 />
}

export const TextAlignTop = function () {
  return <IconTextAlignTop24 />
}

export const TextCapsSmall = function () {
  return <IconTextCapsSmall24 />
}

export const TextFontSize = function () {
  return <IconTextFontSize24 />
}

export const TextLetterSpacing = function () {
  return <IconTextLetterSpacing24 />
}

export const TextLibrary = function () {
  return <IconTextLibrary24 />
}

export const TextLineHeight = function () {
  return <IconTextLineHeight24 />
}

export const TextParagraphIndent1 = function () {
  return <IconTextParagraphIndent124 />
}

export const TextParagraphIndent = function () {
  return <IconTextParagraphIndent24 />
}

export const TextParagraphSpacing = function () {
  return <IconTextParagraphSpacing24 />
}

export const TextResizeFixed = function () {
  return <IconTextResizeFixed24 />
}

export const TextResizeHeight1 = function () {
  return <IconTextResizeHeight124 />
}

export const TextResizeHeight = function () {
  return <IconTextResizeHeight24 />
}

export const TextResizeWidth = function () {
  return <IconTextResizeWidth24 />
}

export const TextSmall = function () {
  return <IconTextSmall24 />
}

export const Text = function () {
  return <IconText24 />
}

export const ThumbDownSmall = function () {
  return <IconThumbDownSmall24 />
}

export const ThumbUpSmall = function () {
  return <IconThumbUpSmall24 />
}

export const TimeSmall = function () {
  return <IconTimeSmall24 />
}

export const TintSmall = function () {
  return <IconTintSmall24 />
}

export const TitleCase = function () {
  return <IconTitleCase24 />
}

export const TranslateSmall = function () {
  return <IconTranslateSmall24 />
}

export const Trash = function () {
  return <IconTrash24 />
}

export const TruncateText = function () {
  return <IconTruncateText24 />
}

export const UiKit = function () {
  return <IconUiKit24 />
}

export const UnderlineDashed = function () {
  return <IconUnderlineDashed24 />
}

export const UnderlineDotted = function () {
  return <IconUnderlineDotted24 />
}

export const UnderlineWave = function () {
  return <IconUnderlineWave24 />
}

export const Underline = function () {
  return <IconUnderline24 />
}

export const UngroupSmall = function () {
  return <IconUngroupSmall24 />
}

export const UnsavedChangesSmall = function () {
  return <IconUnsavedChangesSmall24 />
}

export const UnsavedChanges = function () {
  return <IconUnsavedChanges24 />
}

export const UpdateTextStyleSmall = function () {
  return <IconUpdateTextStyleSmall24 />
}

export const UpdateTextStyle = function () {
  return <IconUpdateTextStyle24 />
}

export const Updates = function () {
  return <IconUpdates24 />
}

export const Uppercase = function () {
  return <IconUppercase24 />
}

export const VariableColorSmall = function () {
  return <IconVariableColorSmall24 />
}

export const VariableColor = function () {
  return <IconVariableColor24 />
}

export const VariableModeSmall = function () {
  return <IconVariableModeSmall24 />
}

export const VariableSmall = function () {
  return <IconVariableSmall24 />
}

export const VariantSmall = function () {
  return <IconVariantSmall24 />
}

export const VectorBendSmall = function () {
  return <IconVectorBendSmall24 />
}

export const VectorBend = function () {
  return <IconVectorBend24 />
}

export const VectorPaintSmall = function () {
  return <IconVectorPaintSmall24 />
}

export const VectorPaint = function () {
  return <IconVectorPaint24 />
}

export const VersionCurrent = function () {
  return <IconVersionCurrent24 />
}

export const VersionHistorySmall = function () {
  return <IconVersionHistorySmall24 />
}

export const VersionMerged = function () {
  return <IconVersionMerged24 />
}

export const VersionNewBranch = function () {
  return <IconVersionNewBranch24 />
}

export const VideoSmall = function () {
  return <IconVideoSmall24 />
}

export const VisualSearchSmall = function () {
  return <IconVisualSearchSmall24 />
}

export const VisualSearch = function () {
  return <IconVisualSearch24 />
}

export const WandSmall = function () {
  return <IconWandSmall24 />
}

export const Wand = function () {
  return <IconWand24 />
}

export const WarningSmall = function () {
  return <IconWarningSmall24 />
}

export const WidgetSmall = function () {
  return <IconWidgetSmall24 />
}

export const Widget = function () {
  return <IconWidget24 />
}

export const Write = function () {
  return <IconWrite24 />
}

export const ZoomInSmall = function () {
  return <IconZoomInSmall24 />
}

export const ZoomNoSmall = function () {
  return <IconZoomNoSmall24 />
}

export const ZoomOutSmall = function () {
  return <IconZoomOutSmall24 />
}
