// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconNavigateBack32 = createIcon(
  'M14.7574 11.2574 10.5 15.5m0 0 4.2574 4.2426M10.5 15.5H23',
  { height: 32, width: 32 }
)
