// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconLayoutHorizontal32 = createIcon(
  'M11 11h3v10h-3V11zm-1-1h5v12h-5V10zm8 1h3v10h-3V11zm-1-1h5v12h-5V10z',
  { height: 32, width: 32 }
)
