// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconRotate32 = createIcon(
  'M16 8c3.866 0 7 3.134 7 7v2.7929l-2.1464-2.1465-.7072.7072 3 3 .3536.3535.3536-.3535 3-3-.7072-.7072L24 17.7929V15c0-4.4183-3.5817-8-8-8v1Zm0 7H8v8h8v-8Zm-8-1H7v10h10V14H8Z',
  { height: 32, width: 32 }
)
