// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconMinus32 = createIcon('M21.5 16.5h-11v-1h11v1Z', {
  height: 32,
  width: 32
})
