// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconNavigateTo32 = createIcon(
  'M17.2426 11.2574 21.5 15.5m0 0-4.2574 4.2426M21.5 15.5H9',
  { height: 32, width: 32 }
)
