// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconReturn32 = createIcon(
  'm11.7071 14 2.6465 2.6464-.7071.7071-3.5-3.5-.35359-.3535.35359-.3536 3.5-3.49998.7071.70708L11.7071 13H15.5c3.5762 0 6.5 2.9238 6.5 6.5V21h-1v-1.5c0-3.0239-2.4761-5.5-5.5-5.5h-3.7929Z',
  { height: 32, width: 32 }
)
