// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconPaddingVertical32 = createIcon(
  'M23 10H9V9h14v1zm-4 3h-6v6h6v-6zm-6-1h-1v8h8v-8h-7zM9 23h14v-1H9v1z',
  { height: 32, width: 32 }
)
