// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconLayoutAlignTop32 = createIcon(
  'M14.5 22V12h-2v10h2zm8-12V9h-13v1h13zm-3 2v6h-2v-6h2z',
  { height: 32, width: 32 }
)
