// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconLayoutGridRows32 = createIcon('undefined', {
  height: 32,
  width: 32
})
