// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconLayoutGridUniform32 = createIcon(
  'M9 9h3v3H9V9zm11 0h3v3h-3V9zm-2.5 0h-3v3h3V9zM9 14.5h3v3H9v-3zm14 0h-3v3h3v-3zm-8.5 0h3v3h-3v-3zM12 20H9v3h3v-3zm8 0h3v3h-3v-3zm-2.5 0h-3v3h3v-3z',
  { height: 32, width: 32 }
)
