// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconLayoutVertical32 = createIcon(
  'M11 11h10v3H11v-3Zm-1-1h12v5H10v-5Zm1 8h10v3H11v-3Zm-1-1h12v5H10v-5Z',
  { height: 32, width: 32 }
)
