// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconLayoutAlignRight32 = createIcon(
  'M22 22.5h1v-13h-1v13zm-12-8h10v-2H10v2zm10 5h-6v-2h6v2z',
  { height: 32, width: 32 }
)
