// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconNavigateTo32 = createIcon(
  'M9 15h11.2899l-3.4002-3.3885.7059-.7083L22.2083 15.5l-4.6127 4.5968-.7059-.7083L20.2899 16H9v-1Z',
  { height: 32, width: 32 }
)
