// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconPaddingHorizontal32 = createIcon(
  'M9 23V9h1v14H9zm13 0V9h1v14h-1zm-9-10h6v6h-6v-6zm-1-1h8v8h-8v-8z',
  { height: 32, width: 32 }
)
