// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconLayoutAlignBottom32 = createIcon(
  'M14.5 10v10h-2V10h2zm8 12v1h-13v-1h13zm-3-2v-6h-2v6h2z',
  { height: 32, width: 32 }
)
