// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconArrowDownCircle32 = createIcon(
  'M9 16c0-3.866 3.134-7 7-7s7 3.134 7 7-3.134 7-7 7-7-3.134-7-7Zm-1 0c0-4.4183 3.5817-8 8-8s8 3.5817 8 8-3.5817 8-8 8-8-3.5817-8-8Zm8.3535 3.7464-.3536.3536-.3535-.3536-3-3 .7071-.7071 2.1464 2.1465v-6.2929h1v6.2929l2.1465-2.1465.7071.7071-3 3Z',
  { height: 32, width: 32 }
)
