// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconEyedropper32 = createIcon(
  'M22.4473 22.4c-.8.8-2 .8-2.8 0l-2.8001-2.8-.8.7c-.4.4-1 .4-1.4 0-.4-.4-.4-1 0-1.4l.7-.7-5.79995-5.8c-.4-.4-1-1.9 0-2.9.99995-1 2.49995-.4 2.89995 0l5.8 5.8.7001-.7c.4-.4 1-.4 1.4 0 .4.4.4 1 0 1.4l-.7.7 2.8 2.8c.8.9.8 2.1 0 2.9ZM11.5472 10.5h-1v1l5.8 5.8 1-1c-.1 0-5.8-5.8-5.8-5.8Z',
  { height: 32, width: 32 }
)
