// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconTrash32 = createIcon(
  'M15 9.5c-.5523 0-1 .44772-1 1h4c0-.55228-.4477-1-1-1h-2Zm4 1c0-1.10457-.8954-2-2-2h-2c-1.1046 0-2 .89543-2 2h-3v1h1v10c0 1.1046.8954 2 2 2h6c1.1046 0 2-.8954 2-2v-10h1v-1h-3Zm1 1h-8v10c0 .5523.4477 1 1 1h6c.5523 0 1-.4477 1-1v-10Zm-6 7v-4h1v4h-1Zm3 0v-4h1v4h-1Z',
  { height: 32, width: 32 }
)
