// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconDraft32 = createIcon(
  'M10 8.5h7.7071l.1465.14645 4 3.99995.1464.1465V23.5H10v-15zm1 1v13h10v-9h-4v-4h-6zm7 .7071L20.2929 12.5H18v-2.2929z',
  { height: 32, width: 32 }
)
