// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../create-icon'

export const IconGrid32 = createIcon(
  'M11 11h3v3h-3v-3Zm-1-1h5v5h-5v-5Zm1 8h3v3h-3v-3Zm-1-1h5v5h-5v-5Zm11-6h-3v3h3v-3Zm-3-1h-1v5h5v-5h-4Zm0 8h3v3h-3v-3Zm-1-1h5v5h-5v-5Z',
  { height: 32, width: 32 }
)
