// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../../create-icon.js'

export const IconList32 = createIcon(
  'M23 10H9v1h14zM9 15.5h14v1H9zM9 21h14v1H9z',
  { height: 32, width: 32 }
)
