// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../../create-icon.js'

export const IconFolder32 = createIcon(
  'M9 10h7v2H9zm-1 2V9h9v3h7v11H8V12m9 1H9v9h14v-9z',
  { height: 32, width: 32 }
)
