// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../../create-icon.js'

export const IconLayoutAlignRight32 = createIcon(
  'M22 22.5h1v-13h-1zm-12-8h10v-2H10zm10 5h-6v-2h6z',
  { height: 32, width: 32 }
)
