// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../../create-icon.js'

export const IconParagraphIndent32 = createIcon(
  'M11.8536 10.1464 9.35355 7.64642l-.7071.70711 1.64645 1.64645H5V11h5.2929l-1.64645 1.6464.7071.7071 2.50005-2.5.3535-.3535zM23 9.99998h-9V11h9zM23 14H9v1h14zm0 4H9v1h14zm0 4H9v1h14z',
  { height: 32, width: 32 }
)
