// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../../create-icon.js'

export const IconGrid32 = createIcon(
  'M11 11h3v3h-3zm-1-1h5v5h-5v-5m1 8h3v3h-3zm-1-1h5v5h-5v-5m11-6h-3v3h3zm-3-1h-1v5h5v-5h-4m0 8h3v3h-3zm-1-1h5v5h-5v-5',
  { height: 32, width: 32 }
)
