// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../../create-icon.js'

export const IconAutoLayoutHorizontalTop16 = createIcon(
  'M3 11h2V3H3zm4 2h2V3H7zm6-4h-2V3h2z',
  { height: 16, width: 16 }
)
