// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
import { createIcon } from '../../create-icon.js'

export const IconLayerSlice16 = createIcon(
  'M10 3H6v1h4zM4 4V3H3v1zM3 6h1v4H3zm9 0h1v4h-1zm1-2h-1V3h1zm-7 8h4v1H6zm-2 0H3v1h1zm8 1v-1h1v1z',
  { height: 16, width: 16 }
)
